/* Library libcerf:
 *   Compute complex error functions, based on a new implementation of
 *   Faddeeva's w_of_z. Also provide Dawson and Voigt functions.
 *
 * File statusquotest.c
 *   Test against values generated by libcerf itself.
 *   These tests contribute nothing to guarantee correctness of our computations.
 *   They just protect against future corruption, compiler bugs etc.
 *
 * Copyright:
 *   (C) 2012 Massachusetts Institute of Technology
 *   (C) 2013 Forschungszentrum Jülich GmbH
 *
 * Licence:
 *   ../LICENSE
 *
 * Authors:
 *   Steven G. Johnson, Massachusetts Institute of Technology, 2012, core author
 *   Joachim Wuttke, Forschungszentrum Jülich, 2013, package maintainer
 *
 * Website:
 *   http://apps.jcns.fz-juelich.de/libcerf
 *
 * Revision history:
 *   ../CHANGELOG
 */

#include "cerf.h"
#include "testtool.h"

int main()
{
    result_t result = {0, 0};

    /***************   erfcx   *****************/

    // Further tests, namely erfcx vs Re(cerfcx), are in realtest.c.

    // change of algorithm at -26.7
    RTEST(result, 1e-13, erfcx(-26.7000000001), Inf);
    RTEST(result, 1e-13, erfcx(-26.6999999999), Inf);

    RTEST(result, 1e-13, erfcx(-19.5), 2.76380080745855e+165);
    RTEST(result, 1e-13, erfcx(-12.3), 1.01260988545376e+66);

    // change of algorithm at -6.1
    RTEST(result, 1e-13, erfcx(-6.10000000003), 2.89152976642548e+16);
    RTEST(result, 1e-13, erfcx(-6.10000000001), 2.89152976571995e+16);
    RTEST(result, 1e-13, erfcx(-6.09999999999), 2.89152976501441e+16);
    RTEST(result, 1e-13, erfcx(-6.09999999997), 2.89152976430888e+16);

    RTEST(result, 1e-13, erfcx(-3), 16205.9888539996);
    RTEST(result, 1e-13, erfcx(-1), 5.00898008076228);

    // change of algorithm at 0
    RTEST(result, 1e-13, erfcx(-1e-1), 1.12364335419921);
    RTEST(result, 1e-13, erfcx(-1e-4), 1.00011284791746);
    RTEST(result, 1e-13, erfcx(-1e-8), 1.00000001128379);
    RTEST(result, 1e-13, erfcx(-1e-12), 1.00000000000113);
    RTEST(result, 1e-13, erfcx(-1e-20), 1);
    RTEST(result, 1e-13, erfcx(0), 1);
    RTEST(result, 1e-13, erfcx(1e-20), 1);
    RTEST(result, 1e-13, erfcx(1e-12), 0.999999999998872);
    RTEST(result, 1e-13, erfcx(1e-8), 0.999999988716208);
    RTEST(result, 1e-13, erfcx(1e-4), 0.999887172082539);
    RTEST(result, 1e-13, erfcx(1e-1), 0.896456979969127);

    RTEST(result, 1e-13, erfcx(1), 0.427583576155807);
    RTEST(result, 1e-13, erfcx(3), 0.17900115118139);
    RTEST(result, 1e-13, erfcx(6), 0.0927765678005384);
    RTEST(result, 1e-13, erfcx(10), 0.0561409927438226);
    RTEST(result, 1e-13, erfcx(20), 0.0281743487410513);
    RTEST(result, 1e-13, erfcx(30), 0.0187958888614168);

    // change of algorithm at 50
    RTEST(result, 1e-13, erfcx(49.99999999999), 0.011281536265326);
    RTEST(result, 1e-13, erfcx(50.00000000001), 0.0112815362653215);

    RTEST(result, 1e-13, erfcx(1e2), 0.00564161378298943);
    RTEST(result, 1e-13, erfcx(1e3), 0.000564189301453388);
    RTEST(result, 1e-13, erfcx(1e4), 5.64189580726808e-05);
    RTEST(result, 1e-13, erfcx(1e5), 5.64189583519547e-06);
    RTEST(result, 1e-13, erfcx(1e6), 5.64189583547474e-07);
    RTEST(result, 1e-13, erfcx(1e7), 5.64189583547753e-08);

    // change of algorithm at 5e7
    RTEST(result, 1e-13, erfcx(5e7), 1.12837916709551e-08);
    RTEST(result, 1e-13, erfcx(5.000000000001e7), 1.12837916709529e-08);

    RTEST(result, 1e-13, erfcx(1e8), 5.64189583547756e-09);
    RTEST(result, 1e-13, erfcx(1e20), 5.64189583547756e-21);
    RTEST(result, 1e-13, erfcx(1e40), 5.64189583547756e-41);
    RTEST(result, 1e-13, erfcx(1e80), 5.64189583547756e-81);
    RTEST(result, 1e-13, erfcx(1e120), 5.64189583547756e-121);
    RTEST(result, 1e-13, erfcx(1e160), 5.64189583547756e-161);

    /***************   Dawson   *****************/

    RTEST(result, 1e-13, dawson(  0.0e+00),    0.000000000000000e+00);

    // rough logarithmic grid
    RTEST(result, 1e-13, dawson(-1.0e-275),  -1.000000000000000e-275);
    RTEST(result, 1e-13, dawson( 1.0e-275),   1.000000000000000e-275);
    RTEST(result, 1e-13, dawson(-1.0e-225),  -1.000000000000000e-225);
    RTEST(result, 1e-13, dawson( 1.0e-225),   1.000000000000000e-225);
    RTEST(result, 1e-13, dawson(-1.0e-175),  -1.000000000000000e-175);
    RTEST(result, 1e-13, dawson( 1.0e-175),   1.000000000000000e-175);
    RTEST(result, 1e-13, dawson(-1.0e-125),  -1.000000000000000e-125);
    RTEST(result, 1e-13, dawson( 1.0e-125),   1.000000000000000e-125);
    RTEST(result, 1e-13, dawson( -1.0e-75),   -1.000000000000000e-75);
    RTEST(result, 1e-13, dawson(  1.0e-75),    1.000000000000000e-75);
    RTEST(result, 1e-13, dawson( -1.0e-25),   -1.000000000000000e-25);
    RTEST(result, 1e-13, dawson(  1.0e-25),    1.000000000000000e-25);
    RTEST(result, 1e-13, dawson( -1.0e+25),   -5.000000000000000e-26);
    RTEST(result, 1e-13, dawson(  1.0e+25),    5.000000000000000e-26);
    RTEST(result, 1e-13, dawson( -1.0e+75),   -5.000000000000001e-76);
    RTEST(result, 1e-13, dawson(  1.0e+75),    5.000000000000001e-76);
    RTEST(result, 1e-13, dawson(-1.0e+125),  -5.000000000000000e-126);
    RTEST(result, 1e-13, dawson( 1.0e+125),   5.000000000000000e-126);
    RTEST(result, 1e-13, dawson(-1.0e+175),  -5.000000000000001e-176);
    RTEST(result, 1e-13, dawson( 1.0e+175),   5.000000000000001e-176);
    RTEST(result, 1e-13, dawson(-1.0e+225),  -5.000000000000001e-226);
    RTEST(result, 1e-13, dawson( 1.0e+225),   5.000000000000001e-226);
    RTEST(result, 1e-13, dawson(-1.0e+275),  -5.000000000000000e-276);
    RTEST(result, 1e-13, dawson( 1.0e+275),   5.000000000000000e-276);

    // medium logarithmic grid
    RTEST(result, 1e-13, dawson( -1.0e-15),   -1.000000000000000e-15);
    RTEST(result, 1e-13, dawson(  1.0e-15),    1.000000000000000e-15);
    RTEST(result, 1e-13, dawson( -1.0e-13),   -1.000000000000000e-13);
    RTEST(result, 1e-13, dawson(  1.0e-13),    1.000000000000000e-13);
    RTEST(result, 1e-13, dawson( -1.0e-11),   -9.999999999999999e-12);
    RTEST(result, 1e-13, dawson(  1.0e-11),    9.999999999999999e-12);
    RTEST(result, 1e-13, dawson( -1.0e-09),   -1.000000000000000e-09);
    RTEST(result, 1e-13, dawson(  1.0e-09),    1.000000000000000e-09);
    RTEST(result, 1e-13, dawson( -1.0e-07),   -9.999999999999933e-08);
    RTEST(result, 1e-13, dawson(  1.0e-07),    9.999999999999933e-08);
    RTEST(result, 1e-13, dawson( -1.0e-05),   -9.999999999333333e-06);
    RTEST(result, 1e-13, dawson(  1.0e-05),    9.999999999333333e-06);
    RTEST(result, 1e-13, dawson( -1.0e-03),   -9.999993333336000e-04);
    RTEST(result, 1e-13, dawson(  1.0e-03),    9.999993333336000e-04);
    RTEST(result, 1e-13, dawson( -1.0e-01),   -9.933599239785290e-02);
    RTEST(result, 1e-13, dawson(  1.0e-01),    9.933599239785290e-02);
    RTEST(result, 1e-13, dawson( -1.0e+01),   -5.025384718759854e-02);
    RTEST(result, 1e-13, dawson(  1.0e+01),    5.025384718759854e-02);
    RTEST(result, 1e-13, dawson( -1.0e+03),   -5.000002500003750e-04);
    RTEST(result, 1e-13, dawson(  1.0e+03),    5.000002500003750e-04);
    RTEST(result, 1e-13, dawson( -1.0e+05),   -5.000000000250000e-06);
    RTEST(result, 1e-13, dawson(  1.0e+05),    5.000000000250000e-06);
    RTEST(result, 1e-13, dawson( -1.0e+07),   -5.000000000000026e-08);
    RTEST(result, 1e-13, dawson(  1.0e+07),    5.000000000000026e-08);
    RTEST(result, 1e-13, dawson( -1.0e+09),   -5.000000000000000e-10);
    RTEST(result, 1e-13, dawson(  1.0e+09),    5.000000000000000e-10);
    RTEST(result, 1e-13, dawson( -1.0e+11),   -5.000000000000000e-12);
    RTEST(result, 1e-13, dawson(  1.0e+11),    5.000000000000000e-12);
    RTEST(result, 1e-13, dawson( -1.0e+13),   -5.000000000000000e-14);
    RTEST(result, 1e-13, dawson(  1.0e+13),    5.000000000000000e-14);
    RTEST(result, 1e-13, dawson( -1.0e+15),   -5.000000000000000e-16);
    RTEST(result, 1e-13, dawson(  1.0e+15),    5.000000000000000e-16);

    // fine logarithmic grid
    RTEST(result, 1e-13, dawson( -1.0e-03),   -9.999993333336000e-04);
    RTEST(result, 1e-13, dawson(  1.0e-03),    9.999993333336000e-04);
    RTEST(result, 1e-13, dawson( -1.5e-03),   -1.499997750002025e-03);
    RTEST(result, 1e-13, dawson(  1.5e-03),    1.499997750002025e-03);
    RTEST(result, 1e-13, dawson( -2.2e-03),   -2.199992901347076e-03);
    RTEST(result, 1e-13, dawson(  2.2e-03),    2.199992901347076e-03);
    RTEST(result, 1e-13, dawson( -3.3e-03),   -3.299976042104361e-03);
    RTEST(result, 1e-13, dawson(  3.3e-03),    3.299976042104361e-03);
    RTEST(result, 1e-13, dawson( -4.7e-03),   -4.699930785278250e-03);
    RTEST(result, 1e-13, dawson(  4.7e-03),    4.699930785278250e-03);
    RTEST(result, 1e-13, dawson( -6.8e-03),   -6.799790382543772e-03);
    RTEST(result, 1e-13, dawson(  6.8e-03),    6.799790382543772e-03);
    RTEST(result, 1e-13, dawson( -1.0e-02),   -9.999333359999240e-03);
    RTEST(result, 1e-13, dawson(  1.0e-02),    9.999333359999240e-03);
    RTEST(result, 1e-13, dawson( -1.5e-02),   -1.499775020248698e-02);
    RTEST(result, 1e-13, dawson(  1.5e-02),    1.499775020248698e-02);
    RTEST(result, 1e-13, dawson( -2.2e-02),   -2.199290270744517e-02);
    RTEST(result, 1e-13, dawson(  2.2e-02),    2.199290270744517e-02);
    RTEST(result, 1e-13, dawson( -3.3e-02),   -3.297605243285839e-02);
    RTEST(result, 1e-13, dawson(  3.3e-02),    3.297605243285839e-02);
    RTEST(result, 1e-13, dawson( -4.7e-02),   -4.693084578675417e-02);
    RTEST(result, 1e-13, dawson(  4.7e-02),    4.693084578675417e-02);
    RTEST(result, 1e-13, dawson( -6.8e-02),   -6.779076587058307e-02);
    RTEST(result, 1e-13, dawson(  6.8e-02),    6.779076587058307e-02);
    RTEST(result, 1e-13, dawson( -1.0e-01),   -9.933599239785290e-02);
    RTEST(result, 1e-13, dawson(  1.0e-01),    9.933599239785290e-02);
    RTEST(result, 1e-13, dawson( -1.5e-01),   -1.477701204696679e-01);
    RTEST(result, 1e-13, dawson(  1.5e-01),    1.477701204696679e-01);
    RTEST(result, 1e-13, dawson( -2.2e-01),   -2.130368833188383e-01);
    RTEST(result, 1e-13, dawson(  2.2e-01),    2.130368833188383e-01);
    RTEST(result, 1e-13, dawson( -3.3e-01),   -3.070539097862983e-01);
    RTEST(result, 1e-13, dawson(  3.3e-01),    3.070539097862983e-01);
    RTEST(result, 1e-13, dawson( -4.7e-01),   -4.065327472834942e-01);
    RTEST(result, 1e-13, dawson(  4.7e-01),    4.065327472834942e-01);
    RTEST(result, 1e-13, dawson( -6.8e-01),   -5.045130066149965e-01);
    RTEST(result, 1e-13, dawson(  6.8e-01),    5.045130066149965e-01);
    RTEST(result, 1e-13, dawson( -1.0e+00),   -5.380795069127684e-01);
    RTEST(result, 1e-13, dawson(  1.0e+00),    5.380795069127684e-01);
    RTEST(result, 1e-13, dawson( -1.5e+00),   -4.282490710853987e-01);
    RTEST(result, 1e-13, dawson(  1.5e+00),    4.282490710853987e-01);
    RTEST(result, 1e-13, dawson( -2.2e+00),   -2.645107599508320e-01);
    RTEST(result, 1e-13, dawson(  2.2e+00),    2.645107599508320e-01);
    RTEST(result, 1e-13, dawson( -3.3e+00),   -1.597885804744951e-01);
    RTEST(result, 1e-13, dawson(  3.3e+00),    1.597885804744951e-01);
    RTEST(result, 1e-13, dawson( -4.7e+00),   -1.089766845891902e-01);
    RTEST(result, 1e-13, dawson(  4.7e+00),    1.089766845891902e-01);
    RTEST(result, 1e-13, dawson( -6.8e+00),   -7.435180005364808e-02);
    RTEST(result, 1e-13, dawson(  6.8e+00),    7.435180005364808e-02);
    RTEST(result, 1e-13, dawson( -1.0e+01),   -5.025384718759854e-02);
    RTEST(result, 1e-13, dawson(  1.0e+01),    5.025384718759854e-02);
    RTEST(result, 1e-13, dawson( -1.5e+01),   -3.340790680863923e-02);
    RTEST(result, 1e-13, dawson(  1.5e+01),    3.340790680863923e-02);
    RTEST(result, 1e-13, dawson( -2.2e+01),   -2.275082445761012e-02);
    RTEST(result, 1e-13, dawson(  2.2e+01),    2.275082445761012e-02);
    RTEST(result, 1e-13, dawson( -3.3e+01),   -1.515848137422974e-02);
    RTEST(result, 1e-13, dawson(  3.3e+01),    1.515848137422974e-02);
    RTEST(result, 1e-13, dawson( -4.7e+01),   -1.064070745357484e-02);
    RTEST(result, 1e-13, dawson(  4.7e+01),    1.064070745357484e-02);
    RTEST(result, 1e-13, dawson( -6.8e+01),   -7.353736519000915e-03);
    RTEST(result, 1e-13, dawson(  6.8e+01),    7.353736519000915e-03);
    RTEST(result, 1e-13, dawson( -1.0e+02),   -5.000250037509379e-03);
    RTEST(result, 1e-13, dawson(  1.0e+02),    5.000250037509379e-03);
    RTEST(result, 1e-13, dawson( -1.5e+02),   -3.333407412346228e-03);
    RTEST(result, 1e-13, dawson(  1.5e+02),    3.333407412346228e-03);
    RTEST(result, 1e-13, dawson( -2.2e+02),   -2.272750752042480e-03);
    RTEST(result, 1e-13, dawson(  2.2e+02),    2.272750752042480e-03);
    RTEST(result, 1e-13, dawson( -3.3e+02),   -1.515158471865865e-03);
    RTEST(result, 1e-13, dawson(  3.3e+02),    1.515158471865865e-03);
    RTEST(result, 1e-13, dawson( -4.7e+02),   -1.063832195194684e-03);
    RTEST(result, 1e-13, dawson(  4.7e+02),    1.063832195194684e-03);
    RTEST(result, 1e-13, dawson( -6.8e+02),   -7.352949127341079e-04);
    RTEST(result, 1e-13, dawson(  6.8e+02),    7.352949127341079e-04);
    RTEST(result, 1e-13, dawson( -1.0e+03),   -5.000002500003750e-04);
    RTEST(result, 1e-13, dawson(  1.0e+03),    5.000002500003750e-04);
    RTEST(result, 1e-13, dawson( -1.5e+03),   -3.333334074074568e-04);
    RTEST(result, 1e-13, dawson(  1.5e+03),    3.333334074074568e-04);
    RTEST(result, 1e-13, dawson( -2.2e+03),   -2.272727507513221e-04);
    RTEST(result, 1e-13, dawson(  2.2e+03),    2.272727507513221e-04);
    RTEST(result, 1e-13, dawson( -3.3e+03),   -1.515151584717710e-04);
    RTEST(result, 1e-13, dawson(  3.3e+03),    1.515151584717710e-04);
    RTEST(result, 1e-13, dawson( -4.7e+03),   -1.063829811313487e-04);
    RTEST(result, 1e-13, dawson(  4.7e+03),    1.063829811313487e-04);
    RTEST(result, 1e-13, dawson( -6.8e+03),   -7.352941255979039e-05);
    RTEST(result, 1e-13, dawson(  6.8e+03),    7.352941255979039e-05);

    /***************   im_w_of_x   *****************/

    RTEST(result, 1e-13, im_w_of_x(  0.0e+00),   0.000000000000000e+00);

    // rough logarithmic grid
    RTEST(result, 1e-13, im_w_of_x(-1.0e-275), -1.128379167095513e-275);
    RTEST(result, 1e-13, im_w_of_x( 1.0e-275),  1.128379167095513e-275);
    RTEST(result, 1e-13, im_w_of_x(-1.0e-225), -1.128379167095512e-225);
    RTEST(result, 1e-13, im_w_of_x( 1.0e-225),  1.128379167095512e-225);
    RTEST(result, 1e-13, im_w_of_x(-1.0e-175), -1.128379167095513e-175);
    RTEST(result, 1e-13, im_w_of_x( 1.0e-175),  1.128379167095513e-175);
    RTEST(result, 1e-13, im_w_of_x(-1.0e-125), -1.128379167095513e-125);
    RTEST(result, 1e-13, im_w_of_x( 1.0e-125),  1.128379167095513e-125);
    RTEST(result, 1e-13, im_w_of_x( -1.0e-75),  -1.128379167095512e-75);
    RTEST(result, 1e-13, im_w_of_x(  1.0e-75),   1.128379167095512e-75);
    RTEST(result, 1e-13, im_w_of_x( -1.0e-25),  -1.128379167095513e-25);
    RTEST(result, 1e-13, im_w_of_x(  1.0e-25),   1.128379167095513e-25);
    RTEST(result, 1e-13, im_w_of_x( -1.0e+25),  -5.641895835477563e-26);
    RTEST(result, 1e-13, im_w_of_x(  1.0e+25),   5.641895835477563e-26);
    RTEST(result, 1e-13, im_w_of_x( -1.0e+75),  -5.641895835477564e-76);
    RTEST(result, 1e-13, im_w_of_x(  1.0e+75),   5.641895835477564e-76);
    RTEST(result, 1e-13, im_w_of_x(-1.0e+125), -5.641895835477563e-126);
    RTEST(result, 1e-13, im_w_of_x( 1.0e+125),  5.641895835477563e-126);
    RTEST(result, 1e-13, im_w_of_x(-1.0e+175), -5.641895835477563e-176);
    RTEST(result, 1e-13, im_w_of_x( 1.0e+175),  5.641895835477563e-176);
    RTEST(result, 1e-13, im_w_of_x(-1.0e+225), -5.641895835477563e-226);
    RTEST(result, 1e-13, im_w_of_x( 1.0e+225),  5.641895835477563e-226);
    RTEST(result, 1e-13, im_w_of_x(-1.0e+275), -5.641895835477563e-276);
    RTEST(result, 1e-13, im_w_of_x( 1.0e+275),  5.641895835477563e-276);

    // medium logarithmic grid
    RTEST(result, 1e-13, im_w_of_x( -1.0e-15),  -1.128379167095513e-15);
    RTEST(result, 1e-13, im_w_of_x(  1.0e-15),   1.128379167095513e-15);
    RTEST(result, 1e-13, im_w_of_x( -1.0e-13),  -1.128379167095513e-13);
    RTEST(result, 1e-13, im_w_of_x(  1.0e-13),   1.128379167095513e-13);
    RTEST(result, 1e-13, im_w_of_x( -1.0e-11),  -1.128379167095512e-11);
    RTEST(result, 1e-13, im_w_of_x(  1.0e-11),   1.128379167095512e-11);
    RTEST(result, 1e-13, im_w_of_x( -1.0e-09),  -1.128379167095513e-09);
    RTEST(result, 1e-13, im_w_of_x(  1.0e-09),   1.128379167095513e-09);
    RTEST(result, 1e-13, im_w_of_x( -1.0e-07),  -1.128379167095505e-07);
    RTEST(result, 1e-13, im_w_of_x(  1.0e-07),   1.128379167095505e-07);
    RTEST(result, 1e-13, im_w_of_x( -1.0e-05),  -1.128379167020287e-05);
    RTEST(result, 1e-13, im_w_of_x(  1.0e-05),   1.128379167020287e-05);
    RTEST(result, 1e-13, im_w_of_x( -1.0e-03),  -1.128378414843035e-03);
    RTEST(result, 1e-13, im_w_of_x(  1.0e-03),   1.128378414843035e-03);
    RTEST(result, 1e-13, im_w_of_x( -1.0e-01),  -1.120886643644954e-01);
    RTEST(result, 1e-13, im_w_of_x(  1.0e-01),   1.120886643644954e-01);
    RTEST(result, 1e-13, im_w_of_x( -1.0e+01),  -5.670539423288760e-02);
    RTEST(result, 1e-13, im_w_of_x(  1.0e+01),   5.670539423288760e-02);
    RTEST(result, 1e-13, im_w_of_x( -1.0e+03),  -5.641898656429711e-04);
    RTEST(result, 1e-13, im_w_of_x(  1.0e+03),   5.641898656429711e-04);
    RTEST(result, 1e-13, im_w_of_x( -1.0e+05),  -5.641895835759658e-06);
    RTEST(result, 1e-13, im_w_of_x(  1.0e+05),   5.641895835759658e-06);
    RTEST(result, 1e-13, im_w_of_x( -1.0e+07),  -5.641895835477592e-08);
    RTEST(result, 1e-13, im_w_of_x(  1.0e+07),   5.641895835477592e-08);
    RTEST(result, 1e-13, im_w_of_x( -1.0e+09),  -5.641895835477563e-10);
    RTEST(result, 1e-13, im_w_of_x(  1.0e+09),   5.641895835477563e-10);
    RTEST(result, 1e-13, im_w_of_x( -1.0e+11),  -5.641895835477562e-12);
    RTEST(result, 1e-13, im_w_of_x(  1.0e+11),   5.641895835477562e-12);
    RTEST(result, 1e-13, im_w_of_x( -1.0e+13),  -5.641895835477563e-14);
    RTEST(result, 1e-13, im_w_of_x(  1.0e+13),   5.641895835477563e-14);
    RTEST(result, 1e-13, im_w_of_x( -1.0e+15),  -5.641895835477563e-16);
    RTEST(result, 1e-13, im_w_of_x(  1.0e+15),   5.641895835477563e-16);

    // fine logarithmic grid
    RTEST(result, 1e-13, im_w_of_x( -1.0e-03),  -1.128378414843035e-03);
    RTEST(result, 1e-13, im_w_of_x(  1.0e-03),   1.128378414843035e-03);
    RTEST(result, 1e-13, im_w_of_x( -1.5e-03),  -1.692566211792428e-03);
    RTEST(result, 1e-13, im_w_of_x(  1.5e-03),   1.692566211792428e-03);
    RTEST(result, 1e-13, im_w_of_x( -2.2e-03),  -2.482426157638054e-03);
    RTEST(result, 1e-13, im_w_of_x(  2.2e-03),   2.482426157638054e-03);
    RTEST(result, 1e-13, im_w_of_x( -3.3e-03),  -3.723624217824865e-03);
    RTEST(result, 1e-13, im_w_of_x(  3.3e-03),   3.723624217824865e-03);
    RTEST(result, 1e-13, im_w_of_x( -4.7e-03),  -5.303303984898830e-03);
    RTEST(result, 1e-13, im_w_of_x(  4.7e-03),   5.303303984898830e-03);
    RTEST(result, 1e-13, im_w_of_x( -6.8e-03),  -7.672741808278817e-03);
    RTEST(result, 1e-13, im_w_of_x(  6.8e-03),   7.672741808278817e-03);
    RTEST(result, 1e-13, im_w_of_x( -1.0e-02),  -1.128303944826631e-02);
    RTEST(result, 1e-13, im_w_of_x(  1.0e-02),   1.128303944826631e-02);
    RTEST(result, 1e-13, im_w_of_x( -1.5e-02),  -1.692314888178881e-02);
    RTEST(result, 1e-13, im_w_of_x(  1.5e-02),   1.692314888178881e-02);
    RTEST(result, 1e-13, im_w_of_x( -2.2e-02),  -2.481633323903963e-02);
    RTEST(result, 1e-13, im_w_of_x(  2.2e-02),   2.481633323903963e-02);
    RTEST(result, 1e-13, im_w_of_x( -3.3e-02),  -3.720949057828670e-02);
    RTEST(result, 1e-13, im_w_of_x(  3.3e-02),   3.720949057828670e-02);
    RTEST(result, 1e-13, im_w_of_x( -4.7e-02),  -5.295578867994562e-02);
    RTEST(result, 1e-13, im_w_of_x(  4.7e-02),   5.295578867994562e-02);
    RTEST(result, 1e-13, im_w_of_x( -6.8e-02),  -7.649368792981542e-02);
    RTEST(result, 1e-13, im_w_of_x(  6.8e-02),   7.649368792981542e-02);
    RTEST(result, 1e-13, im_w_of_x( -1.0e-01),  -1.120886643644954e-01);
    RTEST(result, 1e-13, im_w_of_x(  1.0e-01),   1.120886643644954e-01);
    RTEST(result, 1e-13, im_w_of_x( -1.5e-01),  -1.667407254571674e-01);
    RTEST(result, 1e-13, im_w_of_x(  1.5e-01),   1.667407254571674e-01);
    RTEST(result, 1e-13, im_w_of_x( -2.2e-01),  -2.403863809599346e-01);
    RTEST(result, 1e-13, im_w_of_x(  2.2e-01),   2.403863809599346e-01);
    RTEST(result, 1e-13, im_w_of_x( -3.3e-01),  -3.464732349780839e-01);
    RTEST(result, 1e-13, im_w_of_x(  3.3e-01),   3.464732349780839e-01);
    RTEST(result, 1e-13, im_w_of_x( -4.7e-01),  -4.587230827767997e-01);
    RTEST(result, 1e-13, im_w_of_x(  4.7e-01),   4.587230827767997e-01);
    RTEST(result, 1e-13, im_w_of_x( -6.8e-01),  -5.692819661930826e-01);
    RTEST(result, 1e-13, im_w_of_x(  6.8e-01),   5.692819661930826e-01);
    RTEST(result, 1e-13, im_w_of_x( -1.0e+00),  -6.071577058413937e-01);
    RTEST(result, 1e-13, im_w_of_x(  1.0e+00),   6.071577058413937e-01);
    RTEST(result, 1e-13, im_w_of_x( -1.5e+00),  -4.832273301407691e-01);
    RTEST(result, 1e-13, im_w_of_x(  1.5e+00),   4.832273301407691e-01);
    RTEST(result, 1e-13, im_w_of_x( -2.2e+00),  -2.984684310011209e-01);
    RTEST(result, 1e-13, im_w_of_x(  2.2e+00),   2.984684310011209e-01);
    RTEST(result, 1e-13, im_w_of_x( -3.3e+00),  -1.803021053471850e-01);
    RTEST(result, 1e-13, im_w_of_x(  3.3e+00),   1.803021053471850e-01);
    RTEST(result, 1e-13, im_w_of_x( -4.7e+00),  -1.229670205895808e-01);
    RTEST(result, 1e-13, im_w_of_x(  4.7e+00),   1.229670205895808e-01);
    RTEST(result, 1e-13, im_w_of_x( -6.8e+00),  -8.389702221658751e-02);
    RTEST(result, 1e-13, im_w_of_x(  6.8e+00),   8.389702221658751e-02);
    RTEST(result, 1e-13, im_w_of_x( -1.0e+01),  -5.670539423288760e-02);
    RTEST(result, 1e-13, im_w_of_x(  1.0e+01),   5.670539423288760e-02);
    RTEST(result, 1e-13, im_w_of_x( -1.5e+01),  -3.769678605913683e-02);
    RTEST(result, 1e-13, im_w_of_x(  1.5e+01),   3.769678605913683e-02);
    RTEST(result, 1e-13, im_w_of_x( -2.2e+01),  -2.567155635221433e-02);
    RTEST(result, 1e-13, im_w_of_x(  2.2e+01),   2.567155635221433e-02);
    RTEST(result, 1e-13, im_w_of_x( -3.3e+01),  -1.710451458748619e-02);
    RTEST(result, 1e-13, im_w_of_x(  3.3e+01),   1.710451458748619e-02);
    RTEST(result, 1e-13, im_w_of_x( -4.7e+01),  -1.200675261377179e-02);
    RTEST(result, 1e-13, im_w_of_x(  4.7e+01),   1.200675261377179e-02);
    RTEST(result, 1e-13, im_w_of_x( -6.8e+01),  -8.297803088350106e-03);
    RTEST(result, 1e-13, im_w_of_x(  6.8e+01),   8.297803088350106e-03);
    RTEST(result, 1e-13, im_w_of_x( -1.0e+02),  -5.642177972594138e-03);
    RTEST(result, 1e-13, im_w_of_x(  1.0e+02),   5.642177972594138e-03);
    RTEST(result, 1e-13, im_w_of_x( -1.5e+02),  -3.761347479533245e-03);
    RTEST(result, 1e-13, im_w_of_x(  1.5e+02),   3.761347479533245e-03);
    RTEST(result, 1e-13, im_w_of_x( -2.2e+02),  -2.564524600605394e-03);
    RTEST(result, 1e-13, im_w_of_x(  2.2e+02),   2.564524600605394e-03);
    RTEST(result, 1e-13, im_w_of_x( -3.3e+02),  -1.709673254501715e-03);
    RTEST(result, 1e-13, im_w_of_x(  3.3e+02),   1.709673254501715e-03);
    RTEST(result, 1e-13, im_w_of_x( -4.7e+02),  -1.200406086343168e-03);
    RTEST(result, 1e-13, im_w_of_x(  4.7e+02),   1.200406086343168e-03);
    RTEST(result, 1e-13, im_w_of_x( -6.8e+02),  -8.296914612004802e-04);
    RTEST(result, 1e-13, im_w_of_x(  6.8e+02),   8.296914612004802e-04);
    RTEST(result, 1e-13, im_w_of_x( -1.0e+03),  -5.641898656429711e-04);
    RTEST(result, 1e-13, im_w_of_x(  1.0e+03),   5.641898656429711e-04);
    RTEST(result, 1e-13, im_w_of_x( -1.5e+03),  -3.761264726155353e-04);
    RTEST(result, 1e-13, im_w_of_x(  1.5e+03),   3.761264726155353e-04);
    RTEST(result, 1e-13, im_w_of_x( -2.2e+03),  -2.564498371962829e-04);
    RTEST(result, 1e-13, im_w_of_x(  2.2e+03),   2.564498371962829e-04);
    RTEST(result, 1e-13, im_w_of_x( -3.3e+03),  -1.709665483187216e-04);
    RTEST(result, 1e-13, im_w_of_x(  3.3e+03),   1.709665483187216e-04);
    RTEST(result, 1e-13, im_w_of_x( -4.7e+03),  -1.200403396421289e-04);
    RTEST(result, 1e-13, im_w_of_x(  4.7e+03),   1.200403396421289e-04);
    RTEST(result, 1e-13, im_w_of_x( -6.8e+03),  -8.296905730123859e-05);
    RTEST(result, 1e-13, im_w_of_x(  6.8e+03),   8.296905730123859e-05);

    /***************   terminate   *****************/

    printf("%i/%i tests failed\n", result.failed, result.total);
    return result.failed;
}
