/* Library libcerf:
 *   Compute complex error functions, based on a new implementation of
 *   Faddeeva's w_of_z. Also provide Dawson and Voigt functions.
 *
 * File statusquotest.c
 *   Test against values generated by libcerf itself.
 *   These tests contribute nothing to guarantee correctness of our computations.
 *   They just protect against future corruption, compiler bugs etc.
 *
 * Copyright:
 *   (C) 2012 Massachusetts Institute of Technology
 *   (C) 2013 Forschungszentrum Jülich GmbH
 *
 * Licence:
 *   ../LICENSE
 *
 * Authors:
 *   Steven G. Johnson, Massachusetts Institute of Technology, 2012, core author
 *   Joachim Wuttke, Forschungszentrum Jülich, 2013, package maintainer
 *
 * Website:
 *   http://apps.jcns.fz-juelich.de/libcerf
 *
 * Revision history:
 *   ../CHANGELOG
 */

#include "cerf.h"
#include "testtool.h"

int main()
{
    result_t result = {0, 0};

    /***************   erfcx   *****************/

    // Further tests, namely erfcx vs Re(cerfcx), are in realtest.c.

    // change of algorithm at -26.7
    RTEST(result, 1e-13, erfcx(-26.7000000001), Inf);
    RTEST(result, 1e-13, erfcx(-26.6999999999), Inf);

    RTEST(result, 1e-13, erfcx(-19.5), 2.76380080745855e+165);
    RTEST(result, 1e-13, erfcx(-12.3), 1.01260988545376e+66);

    // change of algorithm at -6.1
    RTEST(result, 1e-13, erfcx(-6.10000000003), 2.89152976642548e+16);
    RTEST(result, 1e-13, erfcx(-6.10000000001), 2.89152976571995e+16);
    RTEST(result, 1e-13, erfcx(-6.09999999999), 2.89152976501441e+16);
    RTEST(result, 1e-13, erfcx(-6.09999999997), 2.89152976430888e+16);

    RTEST(result, 1e-13, erfcx(-3), 16205.9888539996);
    RTEST(result, 1e-13, erfcx(-1), 5.00898008076228);

    // change of algorithm at 0
    RTEST(result, 1e-13, erfcx(-1e-1), 1.12364335419921);
    RTEST(result, 1e-13, erfcx(-1e-4), 1.00011284791746);
    RTEST(result, 1e-13, erfcx(-1e-8), 1.00000001128379);
    RTEST(result, 1e-13, erfcx(-1e-12), 1.00000000000113);
    RTEST(result, 1e-13, erfcx(-1e-20), 1);
    RTEST(result, 1e-13, erfcx(0), 1);
    RTEST(result, 1e-13, erfcx(1e-20), 1);
    RTEST(result, 1e-13, erfcx(1e-12), 0.999999999998872);
    RTEST(result, 1e-13, erfcx(1e-8), 0.999999988716208);
    RTEST(result, 1e-13, erfcx(1e-4), 0.999887172082539);
    RTEST(result, 1e-13, erfcx(1e-1), 0.896456979969127);

    RTEST(result, 1e-13, erfcx(1), 0.427583576155807);
    RTEST(result, 1e-13, erfcx(3), 0.17900115118139);
    RTEST(result, 1e-13, erfcx(6), 0.0927765678005384);
    RTEST(result, 1e-13, erfcx(10), 0.0561409927438226);
    RTEST(result, 1e-13, erfcx(20), 0.0281743487410513);
    RTEST(result, 1e-13, erfcx(30), 0.0187958888614168);

    // change of algorithm at 50
    RTEST(result, 1e-13, erfcx(49.99999999999), 0.011281536265326);
    RTEST(result, 1e-13, erfcx(50.00000000001), 0.0112815362653215);

    RTEST(result, 1e-13, erfcx(1e2), 0.00564161378298943);
    RTEST(result, 1e-13, erfcx(1e3), 0.000564189301453388);
    RTEST(result, 1e-13, erfcx(1e4), 5.64189580726808e-05);
    RTEST(result, 1e-13, erfcx(1e5), 5.64189583519547e-06);
    RTEST(result, 1e-13, erfcx(1e6), 5.64189583547474e-07);
    RTEST(result, 1e-13, erfcx(1e7), 5.64189583547753e-08);

    // change of algorithm at 5e7
    RTEST(result, 1e-13, erfcx(5e7), 1.12837916709551e-08);
    RTEST(result, 1e-13, erfcx(5.000000000001e7), 1.12837916709529e-08);

    RTEST(result, 1e-13, erfcx(1e8), 5.64189583547756e-09);
    RTEST(result, 1e-13, erfcx(1e20), 5.64189583547756e-21);
    RTEST(result, 1e-13, erfcx(1e40), 5.64189583547756e-41);
    RTEST(result, 1e-13, erfcx(1e80), 5.64189583547756e-81);
    RTEST(result, 1e-13, erfcx(1e120), 5.64189583547756e-121);
    RTEST(result, 1e-13, erfcx(1e160), 5.64189583547756e-161);

    /***************   Dawson   *****************/

    RTEST(result, 1e-13, dawson(                        0),                         0);

    // rough logarithmic grid
    RTEST(result, 1e-13, dawson(                  -1e-275),                   -1e-275);
    RTEST(result, 1e-13, dawson(                   1e-275),                    1e-275);
    RTEST(result, 1e-13, dawson(                  -1e-225),                   -1e-225);
    RTEST(result, 1e-13, dawson(                   1e-225),                    1e-225);
    RTEST(result, 1e-13, dawson(                  -1e-175),                   -1e-175);
    RTEST(result, 1e-13, dawson(                   1e-175),                    1e-175);
    RTEST(result, 1e-13, dawson(                  -1e-125),                   -1e-125);
    RTEST(result, 1e-13, dawson(                   1e-125),                    1e-125);
    RTEST(result, 1e-13, dawson(                   -1e-75),                    -1e-75);
    RTEST(result, 1e-13, dawson(                    1e-75),                     1e-75);
    RTEST(result, 1e-13, dawson(                   -1e-25),                    -1e-25);
    RTEST(result, 1e-13, dawson(                    1e-25),                     1e-25);
    RTEST(result, 1e-13, dawson(                   -1e+25),                    -5e-26);
    RTEST(result, 1e-13, dawson(                    1e+25),                     5e-26);
    RTEST(result, 1e-13, dawson(                   -1e+75),                    -5e-76);
    RTEST(result, 1e-13, dawson(                    1e+75),                     5e-76);
    RTEST(result, 1e-13, dawson(                  -1e+125),                   -5e-126);
    RTEST(result, 1e-13, dawson(                   1e+125),                    5e-126);
    RTEST(result, 1e-13, dawson(                  -1e+175),                   -5e-176);
    RTEST(result, 1e-13, dawson(                   1e+175),                    5e-176);
    RTEST(result, 1e-13, dawson(                  -1e+225),                   -5e-226);
    RTEST(result, 1e-13, dawson(                   1e+225),                    5e-226);
    RTEST(result, 1e-13, dawson(                  -1e+275),                   -5e-276);
    RTEST(result, 1e-13, dawson(                   1e+275),                    5e-276);

    // medium logarithmic grid
    RTEST(result, 1e-13, dawson(                   -1e-15),                    -1e-15);
    RTEST(result, 1e-13, dawson(                    1e-15),                     1e-15);
    RTEST(result, 1e-13, dawson(                   -1e-13),                    -1e-13);
    RTEST(result, 1e-13, dawson(                    1e-13),                     1e-13);
    RTEST(result, 1e-13, dawson(                   -1e-11),                    -1e-11);
    RTEST(result, 1e-13, dawson(                    1e-11),                     1e-11);
    RTEST(result, 1e-13, dawson(                   -1e-09),                    -1e-09);
    RTEST(result, 1e-13, dawson(                    1e-09),                     1e-09);
    RTEST(result, 1e-13, dawson(                   -1e-07),     -9.99999999999993e-08);
    RTEST(result, 1e-13, dawson(                    1e-07),      9.99999999999993e-08);
    RTEST(result, 1e-13, dawson(                   -1e-05),     -9.99999999933333e-06);
    RTEST(result, 1e-13, dawson(                    1e-05),      9.99999999933333e-06);
    RTEST(result, 1e-13, dawson(                   -0.001),       -0.0009999993333336);
    RTEST(result, 1e-13, dawson(                    0.001),        0.0009999993333336);
    RTEST(result, 1e-13, dawson(                     -0.1),       -0.0993359923978529);
    RTEST(result, 1e-13, dawson(                      0.1),        0.0993359923978529);
    RTEST(result, 1e-13, dawson(                      -10),       -0.0502538471875985);
    RTEST(result, 1e-13, dawson(                       10),        0.0502538471875985);
    RTEST(result, 1e-13, dawson(                    -1000),     -0.000500000250000375);
    RTEST(result, 1e-13, dawson(                     1000),      0.000500000250000375);
    RTEST(result, 1e-13, dawson(                  -100000),        -5.00000000025e-06);
    RTEST(result, 1e-13, dawson(                   100000),         5.00000000025e-06);
    RTEST(result, 1e-13, dawson(                -10000000),     -5.00000000000003e-08);
    RTEST(result, 1e-13, dawson(                 10000000),      5.00000000000003e-08);
    RTEST(result, 1e-13, dawson(              -1000000000),                    -5e-10);
    RTEST(result, 1e-13, dawson(               1000000000),                     5e-10);
    RTEST(result, 1e-13, dawson(            -100000000000),                    -5e-12);
    RTEST(result, 1e-13, dawson(             100000000000),                     5e-12);
    RTEST(result, 1e-13, dawson(          -10000000000000),                    -5e-14);
    RTEST(result, 1e-13, dawson(           10000000000000),                     5e-14);
    RTEST(result, 1e-13, dawson(                   -1e+15),                    -5e-16);
    RTEST(result, 1e-13, dawson(                    1e+15),                     5e-16);

    // fine logarithmic grid
    RTEST(result, 1e-13, dawson(                   -0.001),       -0.0009999993333336);
    RTEST(result, 1e-13, dawson(                    0.001),        0.0009999993333336);
    RTEST(result, 1e-13, dawson(     -0.00158489319246111),      -0.00158489053841598);
    RTEST(result, 1e-13, dawson(      0.00158489319246111),       0.00158489053841598);
    RTEST(result, 1e-13, dawson(     -0.00251188643150958),      -0.00251187586558163);
    RTEST(result, 1e-13, dawson(      0.00251188643150958),       0.00251187586558163);
    RTEST(result, 1e-13, dawson(     -0.00398107170553498),      -0.00398102964197868);
    RTEST(result, 1e-13, dawson(      0.00398107170553498),       0.00398102964197868);
    RTEST(result, 1e-13, dawson(     -0.00630957344480194),      -0.00630940598837315);
    RTEST(result, 1e-13, dawson(      0.00630957344480194),       0.00630940598837315);
    RTEST(result, 1e-13, dawson(                    -0.01),      -0.00999933335999926);
    RTEST(result, 1e-13, dawson(                     0.01),       0.00999933335999926);
    RTEST(result, 1e-13, dawson(      -0.0158489319246112),        -0.015846278143455);
    RTEST(result, 1e-13, dawson(       0.0158489319246112),         0.015846278143455);
    RTEST(result, 1e-13, dawson(      -0.0251188643150958),       -0.0251083010266654);
    RTEST(result, 1e-13, dawson(       0.0251188643150958),        0.0251083010266654);
    RTEST(result, 1e-13, dawson(      -0.0398107170553498),         -0.03976867988698);
    RTEST(result, 1e-13, dawson(       0.0398107170553498),          0.03976867988698);
    RTEST(result, 1e-13, dawson(      -0.0630957344480194),       -0.0629285417162005);
    RTEST(result, 1e-13, dawson(       0.0630957344480194),        0.0629285417162005);
    RTEST(result, 1e-13, dawson(                     -0.1),       -0.0993359923978529);
    RTEST(result, 1e-13, dawson(                      0.1),        0.0993359923978529);
    RTEST(result, 1e-13, dawson(       -0.158489319246111),        -0.155861747790692);
    RTEST(result, 1e-13, dawson(        0.158489319246111),         0.155861747790692);
    RTEST(result, 1e-13, dawson(       -0.251188643150958),        -0.240884614545736);
    RTEST(result, 1e-13, dawson(        0.251188643150958),         0.240884614545736);
    RTEST(result, 1e-13, dawson(       -0.398107170553498),        -0.358593393789975);
    RTEST(result, 1e-13, dawson(        0.398107170553498),         0.358593393789975);
    RTEST(result, 1e-13, dawson(       -0.630957344480194),         -0.48738176583921);
    RTEST(result, 1e-13, dawson(        0.630957344480194),          0.48738176583921);
    RTEST(result, 1e-13, dawson(                       -1),        -0.538079506912768);
    RTEST(result, 1e-13, dawson(                        1),         0.538079506912768);
    RTEST(result, 1e-13, dawson(        -1.58489319246111),        -0.404177318232523);
    RTEST(result, 1e-13, dawson(         1.58489319246111),         0.404177318232523);
    RTEST(result, 1e-13, dawson(        -2.51188643150958),        -0.221721001957305);
    RTEST(result, 1e-13, dawson(         2.51188643150958),         0.221721001957305);
    RTEST(result, 1e-13, dawson(        -3.98107170553498),        -0.130009929948415);
    RTEST(result, 1e-13, dawson(         3.98107170553498),         0.130009929948415);
    RTEST(result, 1e-13, dawson(        -6.30957344480194),       -0.0802800167663789);
    RTEST(result, 1e-13, dawson(         6.30957344480194),        0.0802800167663789);
    RTEST(result, 1e-13, dawson(                      -10),       -0.0502538471875985);
    RTEST(result, 1e-13, dawson(                       10),        0.0502538471875985);
    RTEST(result, 1e-13, dawson(        -15.8489319246111),        -0.031611043170009);
    RTEST(result, 1e-13, dawson(         15.8489319246111),         0.031611043170009);
    RTEST(result, 1e-13, dawson(        -25.1188643150958),       -0.0199211701107007);
    RTEST(result, 1e-13, dawson(         25.1188643150958),        0.0199211701107007);
    RTEST(result, 1e-13, dawson(        -39.8107170553498),       -0.0125633981464574);
    RTEST(result, 1e-13, dawson(         39.8107170553498),        0.0125633981464574);
    RTEST(result, 1e-13, dawson(        -63.0957344480194),      -0.00792546160546764);
    RTEST(result, 1e-13, dawson(         63.0957344480194),       0.00792546160546764);
    RTEST(result, 1e-13, dawson(                     -100),      -0.00500025003750937);
    RTEST(result, 1e-13, dawson(                      100),       0.00500025003750937);
    RTEST(result, 1e-13, dawson(        -158.489319246112),      -0.00315484952331212);
    RTEST(result, 1e-13, dawson(         158.489319246112),       0.00315484952331212);
    RTEST(result, 1e-13, dawson(        -251.188643150958),      -0.00199055162707611);
    RTEST(result, 1e-13, dawson(         251.188643150958),       0.00199055162707611);
    RTEST(result, 1e-13, dawson(        -398.107170553498),      -0.00125594717802527);
    RTEST(result, 1e-13, dawson(         398.107170553498),       0.00125594717802527);
    RTEST(result, 1e-13, dawson(        -630.957344480195),     -0.000792447591502231);
    RTEST(result, 1e-13, dawson(         630.957344480195),      0.000792447591502231);

    /***************   im_w_of_x   *****************/

    RTEST(result, 1e-13, im_w_of_x(                        0),                         0);

    // rough logarithmic grid
    RTEST(result, 1e-13, im_w_of_x(                  -1e-275),    -1.12837916709551e-275);
    RTEST(result, 1e-13, im_w_of_x(                   1e-275),     1.12837916709551e-275);
    RTEST(result, 1e-13, im_w_of_x(                  -1e-225),    -1.12837916709551e-225);
    RTEST(result, 1e-13, im_w_of_x(                   1e-225),     1.12837916709551e-225);
    RTEST(result, 1e-13, im_w_of_x(                  -1e-175),    -1.12837916709551e-175);
    RTEST(result, 1e-13, im_w_of_x(                   1e-175),     1.12837916709551e-175);
    RTEST(result, 1e-13, im_w_of_x(                  -1e-125),    -1.12837916709551e-125);
    RTEST(result, 1e-13, im_w_of_x(                   1e-125),     1.12837916709551e-125);
    RTEST(result, 1e-13, im_w_of_x(                   -1e-75),     -1.12837916709551e-75);
    RTEST(result, 1e-13, im_w_of_x(                    1e-75),      1.12837916709551e-75);
    RTEST(result, 1e-13, im_w_of_x(                   -1e-25),     -1.12837916709551e-25);
    RTEST(result, 1e-13, im_w_of_x(                    1e-25),      1.12837916709551e-25);
    RTEST(result, 1e-13, im_w_of_x(                   -1e+25),     -5.64189583547756e-26);
    RTEST(result, 1e-13, im_w_of_x(                    1e+25),      5.64189583547756e-26);
    RTEST(result, 1e-13, im_w_of_x(                   -1e+75),     -5.64189583547756e-76);
    RTEST(result, 1e-13, im_w_of_x(                    1e+75),      5.64189583547756e-76);
    RTEST(result, 1e-13, im_w_of_x(                  -1e+125),    -5.64189583547756e-126);
    RTEST(result, 1e-13, im_w_of_x(                   1e+125),     5.64189583547756e-126);
    RTEST(result, 1e-13, im_w_of_x(                  -1e+175),    -5.64189583547756e-176);
    RTEST(result, 1e-13, im_w_of_x(                   1e+175),     5.64189583547756e-176);
    RTEST(result, 1e-13, im_w_of_x(                  -1e+225),    -5.64189583547756e-226);
    RTEST(result, 1e-13, im_w_of_x(                   1e+225),     5.64189583547756e-226);
    RTEST(result, 1e-13, im_w_of_x(                  -1e+275),    -5.64189583547756e-276);
    RTEST(result, 1e-13, im_w_of_x(                   1e+275),     5.64189583547756e-276);

    // medium logarithmic grid
    RTEST(result, 1e-13, im_w_of_x(                   -1e-15),     -1.12837916709551e-15);
    RTEST(result, 1e-13, im_w_of_x(                    1e-15),      1.12837916709551e-15);
    RTEST(result, 1e-13, im_w_of_x(                   -1e-13),     -1.12837916709551e-13);
    RTEST(result, 1e-13, im_w_of_x(                    1e-13),      1.12837916709551e-13);
    RTEST(result, 1e-13, im_w_of_x(                   -1e-11),     -1.12837916709551e-11);
    RTEST(result, 1e-13, im_w_of_x(                    1e-11),      1.12837916709551e-11);
    RTEST(result, 1e-13, im_w_of_x(                   -1e-09),     -1.12837916709551e-09);
    RTEST(result, 1e-13, im_w_of_x(                    1e-09),      1.12837916709551e-09);
    RTEST(result, 1e-13, im_w_of_x(                   -1e-07),      -1.1283791670955e-07);
    RTEST(result, 1e-13, im_w_of_x(                    1e-07),       1.1283791670955e-07);
    RTEST(result, 1e-13, im_w_of_x(                   -1e-05),     -1.12837916702029e-05);
    RTEST(result, 1e-13, im_w_of_x(                    1e-05),      1.12837916702029e-05);
    RTEST(result, 1e-13, im_w_of_x(                   -0.001),      -0.00112837841484304);
    RTEST(result, 1e-13, im_w_of_x(                    0.001),       0.00112837841484304);
    RTEST(result, 1e-13, im_w_of_x(                     -0.1),        -0.112088664364495);
    RTEST(result, 1e-13, im_w_of_x(                      0.1),         0.112088664364495);
    RTEST(result, 1e-13, im_w_of_x(                      -10),       -0.0567053942328876);
    RTEST(result, 1e-13, im_w_of_x(                       10),        0.0567053942328876);
    RTEST(result, 1e-13, im_w_of_x(                    -1000),     -0.000564189865642971);
    RTEST(result, 1e-13, im_w_of_x(                     1000),      0.000564189865642971);
    RTEST(result, 1e-13, im_w_of_x(                  -100000),     -5.64189583575966e-06);
    RTEST(result, 1e-13, im_w_of_x(                   100000),      5.64189583575966e-06);
    RTEST(result, 1e-13, im_w_of_x(                -10000000),     -5.64189583547759e-08);
    RTEST(result, 1e-13, im_w_of_x(                 10000000),      5.64189583547759e-08);
    RTEST(result, 1e-13, im_w_of_x(              -1000000000),     -5.64189583547756e-10);
    RTEST(result, 1e-13, im_w_of_x(               1000000000),      5.64189583547756e-10);
    RTEST(result, 1e-13, im_w_of_x(            -100000000000),     -5.64189583547756e-12);
    RTEST(result, 1e-13, im_w_of_x(             100000000000),      5.64189583547756e-12);
    RTEST(result, 1e-13, im_w_of_x(          -10000000000000),     -5.64189583547756e-14);
    RTEST(result, 1e-13, im_w_of_x(           10000000000000),      5.64189583547756e-14);
    RTEST(result, 1e-13, im_w_of_x(                   -1e+15),     -5.64189583547756e-16);
    RTEST(result, 1e-13, im_w_of_x(                    1e+15),      5.64189583547756e-16);

    // fine logarithmic grid
    RTEST(result, 1e-13, im_w_of_x(                   -0.001),      -0.00112837841484304);
    RTEST(result, 1e-13, im_w_of_x(                    0.001),       0.00112837841484304);
    RTEST(result, 1e-13, im_w_of_x(     -0.00158489319246111),      -0.00178835746567538);
    RTEST(result, 1e-13, im_w_of_x(      0.00158489319246111),       0.00178835746567538);
    RTEST(result, 1e-13, im_w_of_x(     -0.00251188643150958),      -0.00283434839705232);
    RTEST(result, 1e-13, im_w_of_x(      0.00251188643150958),       0.00283434839705232);
    RTEST(result, 1e-13, im_w_of_x(     -0.00398107170553498),      -0.00449211091159845);
    RTEST(result, 1e-13, im_w_of_x(      0.00398107170553498),       0.00449211091159845);
    RTEST(result, 1e-13, im_w_of_x(     -0.00630957344480194),      -0.00711940227402793);
    RTEST(result, 1e-13, im_w_of_x(      0.00630957344480194),       0.00711940227402793);
    RTEST(result, 1e-13, im_w_of_x(                    -0.01),       -0.0112830394482663);
    RTEST(result, 1e-13, im_w_of_x(                     0.01),        0.0112830394482663);
    RTEST(result, 1e-13, im_w_of_x(      -0.0158489319246112),       -0.0178806101330756);
    RTEST(result, 1e-13, im_w_of_x(       0.0158489319246112),        0.0178806101330756);
    RTEST(result, 1e-13, im_w_of_x(      -0.0251188643150958),       -0.0283316837996521);
    RTEST(result, 1e-13, im_w_of_x(       0.0251188643150958),        0.0283316837996521);
    RTEST(result, 1e-13, im_w_of_x(      -0.0398107170553498),       -0.0448741498873586);
    RTEST(result, 1e-13, im_w_of_x(       0.0398107170553498),        0.0448741498873586);
    RTEST(result, 1e-13, im_w_of_x(      -0.0630957344480194),       -0.0710072554882615);
    RTEST(result, 1e-13, im_w_of_x(       0.0630957344480194),        0.0710072554882615);
    RTEST(result, 1e-13, im_w_of_x(                     -0.1),        -0.112088664364495);
    RTEST(result, 1e-13, im_w_of_x(                      0.1),         0.112088664364495);
    RTEST(result, 1e-13, im_w_of_x(       -0.158489319246111),        -0.175871149154112);
    RTEST(result, 1e-13, im_w_of_x(        0.158489319246111),         0.175871149154112);
    RTEST(result, 1e-13, im_w_of_x(       -0.251188643150958),        -0.271809180727242);
    RTEST(result, 1e-13, im_w_of_x(        0.251188643150958),         0.271809180727242);
    RTEST(result, 1e-13, im_w_of_x(       -0.398107170553498),        -0.404629315010686);
    RTEST(result, 1e-13, im_w_of_x(        0.398107170553498),         0.404629315010686);
    RTEST(result, 1e-13, im_w_of_x(       -0.630957344480194),        -0.549951430995187);
    RTEST(result, 1e-13, im_w_of_x(        0.630957344480194),         0.549951430995187);
    RTEST(result, 1e-13, im_w_of_x(                       -1),        -0.607157705841394);
    RTEST(result, 1e-13, im_w_of_x(                        1),         0.607157705841394);
    RTEST(result, 1e-13, im_w_of_x(        -1.58489319246111),        -0.456065265706112);
    RTEST(result, 1e-13, im_w_of_x(         1.58489319246111),         0.456065265706112);
    RTEST(result, 1e-13, im_w_of_x(        -2.51188643150958),        -0.250185359516167);
    RTEST(result, 1e-13, im_w_of_x(         2.51188643150958),         0.250185359516167);
    RTEST(result, 1e-13, im_w_of_x(        -3.98107170553498),        -0.146700496469339);
    RTEST(result, 1e-13, im_w_of_x(         3.98107170553498),         0.146700496469339);
    RTEST(result, 1e-13, im_w_of_x(        -6.30957344480194),       -0.0905862984532604);
    RTEST(result, 1e-13, im_w_of_x(         6.30957344480194),        0.0905862984532604);
    RTEST(result, 1e-13, im_w_of_x(                      -10),       -0.0567053942328875);
    RTEST(result, 1e-13, im_w_of_x(                       10),        0.0567053942328875);
    RTEST(result, 1e-13, im_w_of_x(        -15.8489319246111),        -0.035669242563195);
    RTEST(result, 1e-13, im_w_of_x(         15.8489319246111),         0.035669242563195);
    RTEST(result, 1e-13, im_w_of_x(        -25.1188643150958),       -0.0224786333370805);
    RTEST(result, 1e-13, im_w_of_x(         25.1188643150958),        0.0224786333370805);
    RTEST(result, 1e-13, im_w_of_x(        -39.8107170553498),       -0.0141762767363889);
    RTEST(result, 1e-13, im_w_of_x(         39.8107170553498),        0.0141762767363889);
    RTEST(result, 1e-13, im_w_of_x(        -63.0957344480194),      -0.00894292576522504);
    RTEST(result, 1e-13, im_w_of_x(         63.0957344480194),       0.00894292576522504);
    RTEST(result, 1e-13, im_w_of_x(                     -100),      -0.00564217797259413);
    RTEST(result, 1e-13, im_w_of_x(                      100),       0.00564217797259413);
    RTEST(result, 1e-13, im_w_of_x(        -158.489319246112),      -0.00355986647742661);
    RTEST(result, 1e-13, im_w_of_x(         158.489319246112),       0.00355986647742661);
    RTEST(result, 1e-13, im_w_of_x(        -251.188643150958),      -0.00224609698702076);
    RTEST(result, 1e-13, im_w_of_x(         251.188643150958),       0.00224609698702076);
    RTEST(result, 1e-13, im_w_of_x(        -398.107170553498),      -0.00141718463065611);
    RTEST(result, 1e-13, im_w_of_x(         398.107170553498),       0.00141718463065611);
    RTEST(result, 1e-13, im_w_of_x(        -630.957344480195),     -0.000894181353266133);
    RTEST(result, 1e-13, im_w_of_x(         630.957344480195),      0.000894181353266133);

    /***************   terminate   *****************/

    printf("%i/%i tests failed\n", result.failed, result.total);
    return result.failed;
}
