#!/bin/env python

"""
Compute Taylor coefficients of w(z).
"""

from mpmath import *
import sys
import hp_funcs as hp
import runtool as rt
import functool as fut

mp.dps = 48
mp.pretty = True

def forward(z, N):
    W = []
    W.append(hp.wofz(z.real, z.imag, True))
    W.append(-2*z*W[0] + mpc(0,2)/sqrt(pi))
    for k in range(2,N):
        W.append(-2*(z*W[k-1]+(k-1)*W[k-2]))
        # print("%2i %22.15e" % (k, abs(W[k])))
    R = []
    fac = 1
    for k in range(N):
        R.append(W[k] * fac)
        fac /= (k+1)
    return R

if __name__ == '__main__':
    if len(sys.argv)<3:
        print(f"Usage: {sys.argv[0]} Re(z) Im(z)")
        sys.exit(0)
    z = mpc(sys.argv[1], sys.argv[2])
    N = 32
    W = forward(z, N)

    fut.print_begin_autogenerated()
    print("alignas(64) static const double TaylorCoeffs[%i] = {" % (N*2))
    for w in W:
        print(" %s, %s," % (fut.double2hexstring(w.real), fut.double2hexstring(w.imag)), end="")
    print("};")
    fut.print_end_autogenerated()
