stages:
  - build

mac_x64:
  tags:
  - mac_x64_cloud
  stage: build
  script: &macbuild
    - uname -a
    - OPTDIR=/Users/Shared/Software/scg
    - mkdir build
    - cd build
    - cmake -DCMAKE_PREFIX_PATH="$OPTDIR" -DCMAKE_INSTALL_PREFIX="$OPTDIR" -DCMAKE_BUILD_TYPE=Release -S..
    - make
    - ctest --output-on-failure
    - cpack .
    - if [ "$CI_COMMIT_REF_NAME" == "main" ]; then make install; fi
  artifacts:
    paths:
    - build/*zip
    expire_in: 10 days

mac_arm:
  tags:
  - mac_arm
  stage: build
  script: *macbuild

windows:
  tags:
  - Windows
  stage: build
  script:
    - mkdir -Force "build"
    - cd build
    - cmake -G "Visual Studio 17 2022" -A x64 -T host=x64 -DCERF_CPP=ON -DLIB_MAN=OFF -DCMAKE_INSTALL_PREFIX=C:\opt\x64 -B. ..
    - cmake --build . --config Release
    - Get-Location
    - dir
    - dir Release
    - ctest -C Release --output-on-failure
    - cpack .
    - if ("$CI_COMMIT_REF_NAME" -eq "main") { cmake --install . ; }
  artifacts:
    paths:
    - build/*zip
    expire_in: 10 days

Debian_gcc:
  tags:
  - Debian
  before_script:
    - export CC=gcc; export CXX=g++
    - COMPILE_OPTIONS=""
  stage: build
  script: &debian_build
    - uname -a
    - cmake --version
    - clang --version
    - pwd && ls
    - mkdir build
    - cd build
    - cmake -GNinja -DWERROR=ON ${COMPILE_OPTIONS} ..
    - cmake --build .
    - ctest -j6 --output-on-failure

Debian_g++:
  tags:
  - Debian
  before_script:
    - export CC=gcc; export CXX=g++
    - COMPILE_OPTIONS="-DCERF_AS_CPP=ON"
  stage: build
  script: *debian_build

Debian_clang:
  tags:
  - Debian
  before_script:
    - export CC=clang; export CXX=clang++
  stage: build
  script:
    <<: *debian_build
    - if [ "$CI_COMMIT_REF_NAME" == "main" ]; then cmake --install .; fi

Debian_clang++:
  tags:
  - Debian
  before_script:
    - export CC=clang; export CXX=clang++
  stage: build
  script:
    <<: *debian_build
