/* Library libcerf:
 *   Compute complex error functions, based on a new implementation of
 *   Faddeeva's w_of_z. Also provide Dawson and Voigt functions.
 *
 * File im_w_of_x.c:
 *   Compute scaled Dawson integral im_w_of_x(x) = 2*dawson(x)/sqrt(pi),
 *   equivalent to the imaginary part of the Faddeeva function w(x) for real x.
 *
 * Copyright:
 *   (C) 2012 Massachusetts Institute of Technology
 *   (C) 2013, 2024 Forschungszentrum Jülich GmbH
 *
 * Licence:
 *   Permission is hereby granted, free of charge, to any person obtaining
 *   a copy of this software and associated documentation files (the
 *   "Software"), to deal in the Software without restriction, including
 *   without limitation the rights to use, copy, modify, merge, publish,
 *   distribute, sublicense, and/or sell copies of the Software, and to
 *   permit persons to whom the Software is furnished to do so, subject to
 *   the following conditions:
 *
 *   The above copyright notice and this permission notice shall be
 *   included in all copies or substantial portions of the Software.
 *
 *   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 *   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 *   MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *   NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 *   LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 *   OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 *   WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * Authors:
 *   Steven G. Johnson, Massachusetts Institute of Technology, 2012
 *   Joachim Wuttke, Forschungszentrum Jülich, 2013, 2024
 *
 * Website:
 *   http://apps.jcns.fz-juelich.de/libcerf
 *
 * Revision history:
 *   The numerics in this file has been entirely reworked for greater accuracy
 *   by Joachim Wuttke in September 2024. For large |x|, continuous fractions
 *   were replaced with asymptotic expansions. The small |x| range where Taylor
 *   series is used was expanded. In the middle range, the subdivision in subranges
 *   was redone. To avoid a division, the transformation x -> 1/(1+x) was dropped.
 *   For speed and accuracy, Chebychev subranges are 64th fractions of octaves.
 *   Chebyshev coefficients were recomputed using a Python/mpmath script included
 *   in the source repository. Lookup tables were aligned as as suggested by
 *   Alexander Kleinsorge.
 *   As a result, inaccuracies rarely exceed 3 epsilon.
 *
 *   See also ../CHANGELOG
 *
 * Manual page:
 *   man 3 im_w_of_x
 */

#include "cerf.h"
#include <math.h>
#include "defs.h" // defines _cerf_cmplx, NaN, C, cexp, ...
//#include <stdio.h>

// for analysing the algorithm:
IMPORT extern int faddeeva_algorithm;
IMPORT extern int faddeeva_nofterms;

//--- The following code is generated by devtool/pro_imwofx_chebcoeffs.py
// clang-format off
static const double ChebCoeffs8[288] ALIGN(64) = {
        0x0.8427afe4a6ca98p-67, // x in subrange 0:0 (0.5..0.507812)
     0x0.81428edbee7da8p-67, // x in subrange 0:1 (0.507812..0.515625)
     0x0.fc7e406530bdd8p-68, // x in subrange 0:2 (0.515625..0.523438)
     0x0.f63d2475111d28p-68, // x in subrange 0:3 (0.523438..0.53125)
     0x0.efc43597dfad00p-68, // x in subrange 0:4 (0.53125..0.539062)
     0x0.e915ed83d0fe68p-68, // x in subrange 0:5 (0.539062..0.546875)
     0x0.e234d2eaa22e18p-68, // x in subrange 0:6 (0.546875..0.554688)
     0x0.db23786c45c690p-68, // x in subrange 0:7 (0.554688..0.5625)
     0x0.d3e47b8703c960p-68, // x in subrange 0:8 (0.5625..0.570312)
     0x0.cc7a838588d6b0p-68, // x in subrange 0:9 (0.570312..0.578125)
     0x0.c4e8406b6051a0p-68, // x in subrange 0:10 (0.578125..0.585938)
     0x0.bd3069e0550a18p-68, // x in subrange 0:11 (0.585938..0.59375)
     0x0.b555be1b335f98p-68, // x in subrange 0:12 (0.59375..0.601562)
     0x0.ad5b00cc6703d0p-68, // x in subrange 0:13 (0.601562..0.609375)
     0x0.a542fa08ed7748p-68, // x in subrange 0:14 (0.609375..0.617188)
     0x0.9d107536151888p-68, // x in subrange 0:15 (0.617188..0.625)
     0x0.94c63ff67f1fe0p-68, // x in subrange 0:16 (0.625..0.632812)
     0x0.8c672918d92f58p-68, // x in subrange 0:17 (0.632812..0.640625)
     0x0.83f5ff88c13400p-68, // x in subrange 0:18 (0.640625..0.648438)
     0x0.f6eb2284886ee0p-69, // x in subrange 0:19 (0.648438..0.65625)
     0x0.e5d15490ccdf58p-69, // x in subrange 0:20 (0.65625..0.664062)
     0x0.d4a4273e40b3a8p-69, // x in subrange 0:21 (0.664062..0.671875)
     0x0.c369249273f490p-69, // x in subrange 0:22 (0.671875..0.679688)
     0x0.b225cc94d4fe18p-69, // x in subrange 0:23 (0.679688..0.6875)
     0x0.a0df935c3eed40p-69, // x in subrange 0:24 (0.6875..0.695312)
     0x0.8f9bdf26973698p-69, // x in subrange 0:25 (0.695312..0.703125)
     0x0.fcc00cf6675d70p-70, // x in subrange 0:26 (0.703125..0.710938)
     0x0.da629cb176a240p-70, // x in subrange 0:27 (0.710938..0.71875)
     0x0.b829d0de5998a8p-70, // x in subrange 0:28 (0.71875..0.726562)
     0x0.961fe2cd5caa80p-70, // x in subrange 0:29 (0.726562..0.734375)
     0x0.e89dbccf0a0c58p-71, // x in subrange 0:30 (0.734375..0.742188)
     0x0.a5813de5d7ecc0p-71, // x in subrange 0:31 (0.742188..0.75)
     0x0.c5fb2fd08c4b80p-72, // x in subrange 0:32 (0.75..0.757812)
     0x0.8496b16d3e8220p-73, // x in subrange 0:33 (0.757812..0.765625)
     -0x0.ffa0b41a40fca0p-74, // x in subrange 0:34 (0.765625..0.773438)
     -0x0.c07b768063e128p-72, // x in subrange 0:35 (0.773438..0.78125)
     -0x0.9fa5ca74587270p-71, // x in subrange 0:36 (0.78125..0.789062)
     -0x0.de1b4fc3ac21e8p-71, // x in subrange 0:37 (0.789062..0.796875)
     -0x0.8dc6ef4bcc00a0p-70, // x in subrange 0:38 (0.796875..0.804688)
     -0x0.abf6cb49f26d98p-70, // x in subrange 0:39 (0.804688..0.8125)
     -0x0.c99593e27aaee8p-70, // x in subrange 0:40 (0.8125..0.820312)
     -0x0.e69beb4334d028p-70, // x in subrange 0:41 (0.820312..0.828125)
     -0x0.81815fc8573f80p-69, // x in subrange 0:42 (0.828125..0.835938)
     -0x0.8f61a648655ee0p-69, // x in subrange 0:43 (0.835938..0.84375)
     -0x0.9ceb8e984804f0p-69, // x in subrange 0:44 (0.84375..0.851562)
     -0x0.aa1c06727e4f80p-69, // x in subrange 0:45 (0.851562..0.859375)
     -0x0.b6f02473612bc8p-69, // x in subrange 0:46 (0.859375..0.867188)
     -0x0.c36528a46eab08p-69, // x in subrange 0:47 (0.867188..0.875)
     -0x0.cf787cf5050c18p-69, // x in subrange 0:48 (0.875..0.882812)
     -0x0.db27b5a0986788p-69, // x in subrange 0:49 (0.882812..0.890625)
     -0x0.e67091827664f0p-69, // x in subrange 0:50 (0.890625..0.898438)
     -0x0.f150fa5733b2f0p-69, // x in subrange 0:51 (0.898438..0.90625)
     -0x0.fbc704ebe723d8p-69, // x in subrange 0:52 (0.90625..0.914062)
     -0x0.82e8789daf2510p-68, // x in subrange 0:53 (0.914062..0.921875)
     -0x0.87b6953cbf9bc0p-68, // x in subrange 0:54 (0.921875..0.929688)
     -0x0.8c4d2386894a60p-68, // x in subrange 0:55 (0.929688..0.9375)
     -0x0.90ab843c1c4fd8p-68, // x in subrange 0:56 (0.9375..0.945312)
     -0x0.94d12d97e95f10p-68, // x in subrange 0:57 (0.945312..0.953125)
     -0x0.98bdab31191808p-68, // x in subrange 0:58 (0.953125..0.960938)
     -0x0.9c709dd6b18670p-68, // x in subrange 0:59 (0.960938..0.96875)
     -0x0.9fe9bb62b88700p-68, // x in subrange 0:60 (0.96875..0.976562)
     -0x0.a328ce8584e0b0p-68, // x in subrange 0:61 (0.976562..0.984375)
     -0x0.a62db68972c270p-68, // x in subrange 0:62 (0.984375..0.992188)
     -0x0.a8f8670f331858p-68, // x in subrange 0:63 (0.992188..1)
     -0x0.acba28a10a62d8p-60, // x in subrange 1:0 (1..1.01562)
     -0x0.b0f349175dd1a8p-60, // x in subrange 1:1 (1.01562..1.03125)
     -0x0.b4468da85dff18p-60, // x in subrange 1:2 (1.03125..1.04688)
     -0x0.b6b729b5c3c320p-60, // x in subrange 1:3 (1.04688..1.0625)
     -0x0.b84968ea722de8p-60, // x in subrange 1:4 (1.0625..1.07812)
     -0x0.b9029fdfc0efa8p-60, // x in subrange 1:5 (1.07812..1.09375)
     -0x0.b8e91b9b05db40p-60, // x in subrange 1:6 (1.09375..1.10938)
     -0x0.b80410096a2b28p-60, // x in subrange 1:7 (1.10938..1.125)
     -0x0.b65b85a0b2a088p-60, // x in subrange 1:8 (1.125..1.14062)
     -0x0.b3f8464beaf6d0p-60, // x in subrange 1:9 (1.14062..1.15625)
     -0x0.b0e3c9cadf9650p-60, // x in subrange 1:10 (1.15625..1.17188)
     -0x0.ad2821aafea290p-60, // x in subrange 1:11 (1.17188..1.1875)
     -0x0.a8cfe4ff9ec168p-60, // x in subrange 1:12 (1.1875..1.20312)
     -0x0.a3e61bfeca0f98p-60, // x in subrange 1:13 (1.20312..1.21875)
     -0x0.9e762ba68ae928p-60, // x in subrange 1:14 (1.21875..1.23438)
     -0x0.988bc18d5b2558p-60, // x in subrange 1:15 (1.23438..1.25)
     -0x0.9232bffec22940p-60, // x in subrange 1:16 (1.25..1.26562)
     -0x0.8b772a836813e0p-60, // x in subrange 1:17 (1.26562..1.28125)
     -0x0.846512f1f1cd38p-60, // x in subrange 1:18 (1.28125..1.29688)
     -0x0.fa110e47c153e0p-61, // x in subrange 1:19 (1.29688..1.3125)
     -0x0.eadafeceece570p-61, // x in subrange 1:20 (1.3125..1.32812)
     -0x0.db3f9b8a93b538p-61, // x in subrange 1:21 (1.32812..1.34375)
     -0x0.cb561c5b9b5950p-61, // x in subrange 1:22 (1.34375..1.35938)
     -0x0.bb352f41282770p-61, // x in subrange 1:23 (1.35938..1.375)
     -0x0.aaf2dcb92a2978p-61, // x in subrange 1:24 (1.375..1.39062)
     -0x0.9aa46e4c727b70p-61, // x in subrange 1:25 (1.39062..1.40625)
     -0x0.8a5e575aca2028p-61, // x in subrange 1:26 (1.40625..1.42188)
     -0x0.f468406d0fdf50p-62, // x in subrange 1:27 (1.42188..1.4375)
     -0x0.d470a7347e5750p-62, // x in subrange 1:28 (1.4375..1.45312)
     -0x0.b4f8dcfcb961c0p-62, // x in subrange 1:29 (1.45312..1.46875)
     -0x0.9621a49fdc53b0p-62, // x in subrange 1:30 (1.46875..1.48438)
     -0x0.f012e615938448p-63, // x in subrange 1:31 (1.48438..1.5)
     -0x0.b598ba27cf7838p-63, // x in subrange 1:32 (1.5..1.51562)
     -0x0.fa1027a1a8bd90p-64, // x in subrange 1:33 (1.51562..1.53125)
     -0x0.8d1ea7c8893760p-64, // x in subrange 1:34 (1.53125..1.54688)
     -0x0.92bf210f941958p-66, // x in subrange 1:35 (1.54688..1.5625)
     0x0.fbce502fc3e140p-66, // x in subrange 1:36 (1.5625..1.57812)
     0x0.9d8c6d7dfbb5a0p-64, // x in subrange 1:37 (1.57812..1.59375)
     0x0.f6e58b2f844a90p-64, // x in subrange 1:38 (1.59375..1.60938)
     0x0.a569a838f10180p-63, // x in subrange 1:39 (1.60938..1.625)
     0x0.cc99c286dfaf88p-63, // x in subrange 1:40 (1.625..1.64062)
     0x0.f0f688af5285b8p-63, // x in subrange 1:41 (1.64062..1.65625)
     0x0.893bebd4ca0e20p-62, // x in subrange 1:42 (1.65625..1.67188)
     0x0.988ce4594abd88p-62, // x in subrange 1:43 (1.67188..1.6875)
     0x0.a66e40288f15a8p-62, // x in subrange 1:44 (1.6875..1.70312)
     0x0.b2e1fcb79a2b10p-62, // x in subrange 1:45 (1.70312..1.71875)
     0x0.bdebe68af279a0p-62, // x in subrange 1:46 (1.71875..1.73438)
     0x0.c7917babc08d98p-62, // x in subrange 1:47 (1.73438..1.75)
     0x0.cfd9ccf9280ec8p-62, // x in subrange 1:48 (1.75..1.76562)
     0x0.d6cd5e9957d720p-62, // x in subrange 1:49 (1.76562..1.78125)
     0x0.dc7607cbdb8b38p-62, // x in subrange 1:50 (1.78125..1.79688)
     0x0.e0ded25c61c868p-62, // x in subrange 1:51 (1.79688..1.8125)
     0x0.e413d9f2779c60p-62, // x in subrange 1:52 (1.8125..1.82812)
     0x0.e6222b77b70938p-62, // x in subrange 1:53 (1.82812..1.84375)
     0x0.e717a4ca9d6a28p-62, // x in subrange 1:54 (1.84375..1.85938)
     0x0.e702d4f0ba3240p-62, // x in subrange 1:55 (1.85938..1.875)
     0x0.e5f2dcf7313f78p-62, // x in subrange 1:56 (1.875..1.89062)
     0x0.e3f751acb03158p-62, // x in subrange 1:57 (1.89062..1.90625)
     0x0.e1201e5bfdf798p-62, // x in subrange 1:58 (1.90625..1.92188)
     0x0.dd7d68aa40ec98p-62, // x in subrange 1:59 (1.92188..1.9375)
     0x0.d91f75b803ac20p-62, // x in subrange 1:60 (1.9375..1.95312)
     0x0.d416909fec6180p-62, // x in subrange 1:61 (1.95312..1.96875)
     0x0.ce72f26a0dedc8p-62, // x in subrange 1:62 (1.96875..1.98438)
     0x0.c844ab86bde590p-62, // x in subrange 1:63 (1.98438..2)
     0x0.be1bb90e28c310p-54, // x in subrange 2:0 (2..2.03125)
     0x0.af3eb8593c7c60p-54, // x in subrange 2:1 (2.03125..2.0625)
     0x0.9f47a672aff1e0p-54, // x in subrange 2:2 (2.0625..2.09375)
     0x0.8ea35a266657e0p-54, // x in subrange 2:3 (2.09375..2.125)
     0x0.fb69caea29adc0p-55, // x in subrange 2:4 (2.125..2.15625)
     0x0.d9a938f950b658p-55, // x in subrange 2:5 (2.15625..2.1875)
     0x0.b89ef8ab538c70p-55, // x in subrange 2:6 (2.1875..2.21875)
     0x0.98cdd3c3829860p-55, // x in subrange 2:7 (2.21875..2.25)
     0x0.f542fc8447cb70p-56, // x in subrange 2:8 (2.25..2.28125)
     0x0.bcde72c43d0a60p-56, // x in subrange 2:9 (2.28125..2.3125)
     0x0.88edd2423c9cd0p-56, // x in subrange 2:10 (2.3125..2.34375)
     0x0.b3921903a43b88p-57, // x in subrange 2:11 (2.34375..2.375)
     0x0.be8eb8ab272258p-58, // x in subrange 2:12 (2.375..2.40625)
     0x0.a90b4d653fa600p-60, // x in subrange 2:13 (2.40625..2.4375)
     -0x0.abcaebcf2ea120p-59, // x in subrange 2:14 (2.4375..2.46875)
     -0x0.c271509de9c870p-58, // x in subrange 2:15 (2.46875..2.5)
     -0x0.8e1c3ba93613d8p-57, // x in subrange 2:16 (2.5..2.53125)
     -0x0.b229816605ed98p-57, // x in subrange 2:17 (2.53125..2.5625)
     -0x0.ce050625a25a28p-57, // x in subrange 2:18 (2.5625..2.59375)
     -0x0.e264b2e8057460p-57, // x in subrange 2:19 (2.59375..2.625)
     -0x0.f0094df4e5e2b8p-57, // x in subrange 2:20 (2.625..2.65625)
     -0x0.f7b8b20d51ca58p-57, // x in subrange 2:21 (2.65625..2.6875)
     -0x0.fa38c5e6b5af38p-57, // x in subrange 2:22 (2.6875..2.71875)
     -0x0.f84b3740855198p-57, // x in subrange 2:23 (2.71875..2.75)
     -0x0.f2a9f72144fc28p-57, // x in subrange 2:24 (2.75..2.78125)
     -0x0.ea046ff6ca87d8p-57, // x in subrange 2:25 (2.78125..2.8125)
     -0x0.defd6a78585b88p-57, // x in subrange 2:26 (2.8125..2.84375)
     -0x0.d2299337f4c018p-57, // x in subrange 2:27 (2.84375..2.875)
     -0x0.c40e90bcf4fa48p-57, // x in subrange 2:28 (2.875..2.90625)
     -0x0.b52298b915f468p-57, // x in subrange 2:29 (2.90625..2.9375)
     -0x0.a5cc7255288818p-57, // x in subrange 2:30 (2.9375..2.96875)
     -0x0.9663d399a0d3c0p-57, // x in subrange 2:31 (2.96875..3)
     -0x0.87320880976fd0p-57, // x in subrange 2:32 (3..3.03125)
     -0x0.f0e5a660cd1468p-58, // x in subrange 2:33 (3.03125..3.0625)
     -0x0.d4aaec3ea37ae8p-58, // x in subrange 2:34 (3.0625..3.09375)
     -0x0.b9fbb4b4f50668p-58, // x in subrange 2:35 (3.09375..3.125)
     -0x0.a10b8b8f85b668p-58, // x in subrange 2:36 (3.125..3.15625)
     -0x0.89fc2dd13c6e78p-58, // x in subrange 2:37 (3.15625..3.1875)
     -0x0.e9bff54d1f7110p-59, // x in subrange 2:38 (3.1875..3.21875)
     -0x0.c3789eecea82c8p-59, // x in subrange 2:39 (3.21875..3.25)
     -0x0.a11787ba7d3a60p-59, // x in subrange 2:40 (3.25..3.28125)
     -0x0.82807a7339c7c8p-59, // x in subrange 2:41 (3.28125..3.3125)
     -0x0.cf135023946f98p-60, // x in subrange 2:42 (3.3125..3.34375)
     -0x0.9ffe1e5771d998p-60, // x in subrange 2:43 (3.34375..3.375)
     -0x0.ee95f38e128280p-61, // x in subrange 2:44 (3.375..3.40625)
     -0x0.a8f49e90cd1f50p-61, // x in subrange 2:45 (3.40625..3.4375)
     -0x0.dc1f341874a8a8p-62, // x in subrange 2:46 (3.4375..3.46875)
     -0x0.f370a3741888b8p-63, // x in subrange 2:47 (3.46875..3.5)
     -0x0.a29bc438a77e90p-64, // x in subrange 2:48 (3.5..3.53125)
     0x0.c889c3d59b9910p-65, // x in subrange 2:49 (3.53125..3.5625)
     0x0.9aa7af1569b218p-63, // x in subrange 2:50 (3.5625..3.59375)
     0x0.ebcd6a51c94dd0p-63, // x in subrange 2:51 (3.59375..3.625)
     0x0.946e2adf896210p-62, // x in subrange 2:52 (3.625..3.65625)
     0x0.aa6b0ed45d3d50p-62, // x in subrange 2:53 (3.65625..3.6875)
     0x0.b939d93e871240p-62, // x in subrange 2:54 (3.6875..3.71875)
     0x0.c212c915c6dd18p-62, // x in subrange 2:55 (3.71875..3.75)
     0x0.c60ad2fe77e180p-62, // x in subrange 2:56 (3.75..3.78125)
     0x0.c6152b0a4d7460p-62, // x in subrange 2:57 (3.78125..3.8125)
     0x0.c3053fa5b12668p-62, // x in subrange 2:58 (3.8125..3.84375)
     0x0.bd9101c0f09e38p-62, // x in subrange 2:59 (3.84375..3.875)
     0x0.b6535bc9a14a00p-62, // x in subrange 2:60 (3.875..3.90625)
     0x0.adcebe3ca20fa8p-62, // x in subrange 2:61 (3.90625..3.9375)
     0x0.a46fad65dd17b8p-62, // x in subrange 2:62 (3.9375..3.96875)
     0x0.9a8f403a2f07b0p-62, // x in subrange 2:63 (3.96875..4)
     0x0.8b66158058a100p-54, // x in subrange 3:0 (4..4.0625)
     0x0.ef2ac1ce187a68p-55, // x in subrange 3:1 (4.0625..4.125)
     0x0.ca54a6bd18f360p-55, // x in subrange 3:2 (4.125..4.1875)
     0x0.a964e8e0564600p-55, // x in subrange 3:3 (4.1875..4.25)
     0x0.8cc1c7f033cf00p-55, // x in subrange 3:4 (4.25..4.3125)
     0x0.e8bdb39c9964a8p-56, // x in subrange 3:5 (4.3125..4.375)
     0x0.bfda301ccc17a0p-56, // x in subrange 3:6 (4.375..4.4375)
     0x0.9df87c38987610p-56, // x in subrange 3:7 (4.4375..4.5)
     0x0.8221916ad0eea0p-56, // x in subrange 3:8 (4.5..4.5625)
     0x0.d6c622aababe78p-57, // x in subrange 3:9 (4.5625..4.625)
     0x0.b1bcf16b367640p-57, // x in subrange 3:10 (4.625..4.6875)
     0x0.93a07ca076fd60p-57, // x in subrange 3:11 (4.6875..4.75)
     0x0.f6471ff73db640p-58, // x in subrange 3:12 (4.75..4.8125)
     0x0.ce613d9b724328p-58, // x in subrange 3:13 (4.8125..4.875)
     0x0.adc8a15e888090p-58, // x in subrange 3:14 (4.875..4.9375)
     0x0.930d69ffec7cb0p-58, // x in subrange 3:15 (4.9375..5)
     0x0.fa1118501394a8p-59, // x in subrange 3:16 (5..5.0625)
     0x0.d59d8ae271e350p-59, // x in subrange 3:17 (5.0625..5.125)
     0x0.b74a3968463890p-59, // x in subrange 3:18 (5.125..5.1875)
     0x0.9dee47d9077b10p-59, // x in subrange 3:19 (5.1875..5.25)
     0x0.889de23bcc7aa8p-59, // x in subrange 3:20 (5.25..5.3125)
     0x0.ed3a8c3d511288p-60, // x in subrange 3:21 (5.3125..5.375)
     0x0.ceace5a75ee9c8p-60, // x in subrange 3:22 (5.375..5.4375)
     0x0.b4a217a89bd488p-60, // x in subrange 3:23 (5.4375..5.5)
     0x0.9e58028a3d82f8p-60, // x in subrange 3:24 (5.5..5.5625)
     0x0.8b31417d7d90d8p-60, // x in subrange 3:25 (5.5625..5.625)
     0x0.f55b00b8896c98p-61, // x in subrange 3:26 (5.625..5.6875)
     0x0.d8c70e55e5bf70p-61, // x in subrange 3:27 (5.6875..5.75)
     0x0.bff92e95b9c808p-61, // x in subrange 3:28 (5.75..5.8125)
     0x0.aa6198c62915b8p-61, // x in subrange 3:29 (5.8125..5.875)
     0x0.978889c90a08c8p-61, // x in subrange 3:30 (5.875..5.9375)
     0x0.8709c855dadf38p-61, // x in subrange 3:31 (5.9375..6)
     0x0.f1222cb88ecde0p-62, // x in subrange 3:32 (6..6.0625)
     0x0.d7aeb46366ecd8p-62, // x in subrange 3:33 (6.0625..6.125)
     0x0.c140adddd23590p-62, // x in subrange 3:34 (6.125..6.1875)
     0x0.ad71aa0114cfd0p-62, // x in subrange 3:35 (6.1875..6.25)
     0x0.9bea4657bfd250p-62, // x in subrange 3:36 (6.25..6.3125)
     0x0.8c5fbb7f207510p-62, // x in subrange 3:37 (6.3125..6.375)
     0x0.fd23b71de443a8p-63, // x in subrange 3:38 (6.375..6.4375)
     0x0.e492d4ebec06c8p-63, // x in subrange 3:39 (6.4375..6.5)
     0x0.cead7df98ef608p-63, // x in subrange 3:40 (6.5..6.5625)
     0x0.bb213d8b8ae920p-63, // x in subrange 3:41 (6.5625..6.625)
     0x0.a9a694e0ea99d0p-63, // x in subrange 3:42 (6.625..6.6875)
     0x0.99ff626a1779e8p-63, // x in subrange 3:43 (6.6875..6.75)
     0x0.8bf58a019b6130p-63, // x in subrange 3:44 (6.75..6.8125)
     0x0.feb3a5cae5db30p-64, // x in subrange 3:45 (6.8125..6.875)
     0x0.e805e49c09f848p-64, // x in subrange 3:46 (6.875..6.9375)
     0x0.d399765e7341d8p-64, // x in subrange 3:47 (6.9375..7)
     0x0.c12eda129ee170p-64, // x in subrange 3:48 (7..7.0625)
     0x0.b08e39893bb748p-64, // x in subrange 3:49 (7.0625..7.125)
     0x0.a18666e77b8430p-64, // x in subrange 3:50 (7.125..7.1875)
     0x0.93ebff1b3fe538p-64, // x in subrange 3:51 (7.1875..7.25)
     0x0.8798ab8afc11e8p-64, // x in subrange 3:52 (7.25..7.3125)
     0x0.f8d4fc7ffef410p-65, // x in subrange 3:53 (7.3125..7.375)
     0x0.e486c922a308a0p-65, // x in subrange 3:54 (7.375..7.4375)
     0x0.d21159f34c6508p-65, // x in subrange 3:55 (7.4375..7.5)
     0x0.c1453a95b5a3f8p-65, // x in subrange 3:56 (7.5..7.5625)
     0x0.b1f82dc4406c80p-65, // x in subrange 3:57 (7.5625..7.625)
     0x0.a4048dbb713b00p-65, // x in subrange 3:58 (7.625..7.6875)
     0x0.9748c146c52600p-65, // x in subrange 3:59 (7.6875..7.75)
     0x0.8ba6c28fe20720p-65, // x in subrange 3:60 (7.75..7.8125)
     0x0.8103b53ece9900p-65, // x in subrange 3:61 (7.8125..7.875)
     0x0.ee8f13ac202d98p-66, // x in subrange 3:62 (7.875..7.9375)
     0x0.dcb959066d0390p-66, // x in subrange 3:63 (7.9375..8)
     0x0.c4bcd323096e10p-58, // x in subrange 4:0 (8..8.125)
     0x0.a9265ad3ba2448p-58, // x in subrange 4:1 (8.125..8.25)
     0x0.91d46d893b19b8p-58, // x in subrange 4:2 (8.25..8.375)
     0x0.fc1ce0b431fbe0p-59, // x in subrange 4:3 (8.375..8.5)
     0x0.da7b25d6fc69d0p-59, // x in subrange 4:4 (8.5..8.625)
     0x0.bdcc4faab4bc40p-59, // x in subrange 4:5 (8.625..8.75)
     0x0.a544c7c3c0e188p-59, // x in subrange 4:6 (8.75..8.875)
     0x0.903c676b5f91b8p-59, // x in subrange 4:7 (8.875..9)
     0x0.fc4faa285df4a0p-60, // x in subrange 4:8 (9..9.125)
     0x0.dd266bd1542d08p-60, // x in subrange 4:9 (9.125..9.25)
     0x0.c23bd5fc2e3398p-60, // x in subrange 4:10 (9.25..9.375)
     0x0.aaee44220fdee0p-60, // x in subrange 4:11 (9.375..9.5)
     0x0.96b61c4c023690p-60, // x in subrange 4:12 (9.5..9.625)
     0x0.85214be5d45498p-60, // x in subrange 4:13 (9.625..9.75)
     0x0.eb9f3533173cc8p-61, // x in subrange 4:14 (9.75..9.875)
     0x0.d0df5205bca378p-61, // x in subrange 4:15 (9.875..10)
     0x0.b978f3b26813b8p-61, // x in subrange 4:16 (10..10.125)
     0x0.a4f6d619c81d70p-61, // x in subrange 4:17 (10.125..10.25)
     0x0.92f51369e86880p-61, // x in subrange 4:18 (10.25..10.375)
     0x0.831e5fc92bf180p-61, // x in subrange 4:19 (10.375..10.5)
     0x0.ea537b55478f08p-62, // x in subrange 4:20 (10.5..10.625)
     0x0.d1b129db805148p-62, // x in subrange 4:21 (10.625..10.75)
     0x0.bbea363bd95800p-62, // x in subrange 4:22 (10.75..10.875)
     0x0.a8a1fcff2eca18p-62, // x in subrange 4:23 (10.875..11)
     0x0.9788908b905498p-62, // x in subrange 4:24 (11..11.125)
     0x0.8858d8e391ee70p-62, // x in subrange 4:25 (11.125..11.25)
     0x0.f5adfe6611ffd0p-63, // x in subrange 4:26 (11.25..11.375)
     0x0.dd9e30dc8d4338p-63, // x in subrange 4:27 (11.375..11.5)
     0x0.c828091945e948p-63, // x in subrange 4:28 (11.5..11.625)
     0x0.b4fcf37c36b6b0p-63, // x in subrange 4:29 (11.625..11.75)
     0x0.a3d868f6b36788p-63, // x in subrange 4:30 (11.75..11.875)
     0x0.947e8d117ed8b0p-63, // x in subrange 4:31 (11.875..12)
};
static const double ChebCoeffs[288 * 8] ALIGN(64) = {
 0x0.f6809795a1f940p-1, 0x0.a4a6a8a1c31838p-8, -0x0.ce3846c4544bd8p-16, -0x0.a1f622978c5010p-26, 0x0.e29f88a0005f18p-33, -0x0.d4954384857bb0p-45, -0x0.929ea588d2a528p-50, 0x0.e59bb7b81bec50p-61, // x in subrange 0:0 (0.5..0.507812)
 0x0.f90cbdfc4295b0p-1, 0x0.a16befcc13a438p-8, -0x0.cf209ab38f57e0p-16, -0x0.93d0ac5b2e1b60p-26, 0x0.e2098cc04db048p-33, -0x0.85a1c2b554aa60p-44, -0x0.90fe7893cda3c8p-50, 0x0.f5f2ac485b04e0p-61, // x in subrange 0:1 (0.507812..0.515625)
 0x0.fb8bf275790688p-1, 0x0.9e2dc00d21d670p-8, -0x0.cff3be018f17a8p-16, -0x0.85b5a63b86a860p-26, 0x0.e15195d8de0ee0p-33, -0x0.a0a83258cf4f70p-44, -0x0.8f42058204fd90p-50, 0x0.82f58a6929b840p-60, // x in subrange 0:2 (0.515625..0.523438)
 0x0.fdfe27cef96d58p-1, 0x0.9aec6e06042e28p-8, -0x0.d0b1c1eca8eb08p-16, -0x0.ef4e596125e148p-27, 0x0.e0780c11038700p-33, -0x0.bb58b341b09a88p-44, -0x0.8d69f50f378648p-50, 0x0.8ac09d395fff00p-60, // x in subrange 0:3 (0.523438..0.53125)
 0x0.8031a91434f3e0p0, 0x0.97a84e0c8909d0p-8, -0x0.d15abad8ea4a20p-16, -0x0.d34eaaf7be2b70p-27, 0x0.df7d5e08cf9e18p-33, -0x0.d5ae2841fb2078p-44, -0x0.8b76f655e0dcb0p-50, 0x0.9258c64528aec8p-60, // x in subrange 0:4 (0.53125..0.539062)
 0x0.815db3790e2e30p0, 0x0.9461b41eb450a8p-8, -0x0.d1eec045ba1600p-16, -0x0.b7705e84817928p-27, 0x0.de6200b00a9548p-33, -0x0.efa3959424b0d8p-44, -0x0.8969be8b741038p-50, 0x0.99bc50d3233570p-60, // x in subrange 0:5 (0.539062..0.546875)
 0x0.82832e75cb4998p0, 0x0.9118f3d667c7c0p-8, -0x0.d26decc2e272a0p-16, -0x0.9bb782505af8d0p-27, 0x0.dd266f1bbc6218p-33, -0x0.849a10fcd55928p-43, -0x0.874308bb0daa80p-50, 0x0.a0e99c2c3da7f8p-60, // x in subrange 0:6 (0.546875..0.554688)
 0x0.83a21610f4a3e8p0, 0x0.8dce605d3867b0p-8, -0x0.d2d85de50725d8p-16, -0x0.802814e1878858p-27, 0x0.dbcb2a5a579b40p-33, -0x0.912d8be642b250p-43, -0x0.8503957eba3b30p-50, 0x0.a7df1bff5d8d10p-60, // x in subrange 0:7 (0.554688..0.5625)
 0x0.84ba66f6eb7810p0, 0x0.8a824c6072f8d0p-8, -0x0.d32e34398c9700p-16, -0x0.c98c087e6e4df8p-28, 0x0.da50b94696ec78p-33, -0x0.9d89f3019c50f0p-43, -0x0.82ac2ab76edb48p-50, 0x0.ae9b58bc938a70p-60, // x in subrange 0:8 (0.5625..0.570312)
 0x0.85cc1e78e57b08p0, 0x0.87350a05522b80p-8, -0x0.d36f9339f3aa08p-16, -0x0.932a5a75cd5ed0p-28, 0x0.d8b7a8591df270p-33, -0x0.a9ad1093a32370p-43, -0x0.803d9343d16290p-50, 0x0.b51cefe7c77de0p-60, // x in subrange 0:9 (0.570312..0.578125)
 0x0.86d73a8bd118e8p0, 0x0.83e6eadd684fd0p-8, -0x0.d39ca13eaecf60p-16, -0x0.ba656afe616da0p-29, 0x0.d7008978eea728p-33, -0x0.b594c21ee600d8p-43, -0x0.fb713d6bdc8a90p-51, 0x0.bb629462ce6ad8p-60, // x in subrange 0:10 (0.578125..0.585938)
 0x0.87dbb9c722ba30p0, 0x0.80983fdb3ebf28p-8, -0x0.d3b5877174bcf8p-16, -0x0.9eb229387b49e0p-30, 0x0.d52bf3cac4c798p-33, -0x0.c13ef8d10df488p-43, -0x0.f63c420ff476e0p-51, 0x0.c16b0eaedf82b0p-60, // x in subrange 0:11 (0.585938..0.59375)
 0x0.88d99b638b7fa8p0, 0x0.fa92b28e59f068p-9, -0x0.d3ba71bf156008p-16, 0x0.d60dcd59dec618p-32, 0x0.d33a837f68d490p-33, -0x0.cca9b9e91273b8p-43, -0x0.f0dde4a07be4e0p-51, 0x0.c7353d25616820p-60, // x in subrange 0:12 (0.59375..0.601562)
 0x0.89d0df3999e5a8p0, 0x0.f3f50d68d2b578p-9, -0x0.d3ab8ec8d5af98p-16, 0x0.83dcba9955e170p-29, 0x0.d12cd9a10c82b0p-33, -0x0.d7d31f1642da38p-43, -0x0.eb57dce8943528p-51, 0x0.ccc014280ca2d8p-60, // x in subrange 0:13 (0.601562..0.609375)
 0x0.8ac185c044c3d8p0, 0x0.ed582decaabd38p-9, -0x0.d3890fd5571ee0p-16, 0x0.ebe9faa0169be0p-29, 0x0.cf039bdfc29928p-33, -0x0.e2b956d0156218p-43, -0x0.e5abe9b7244d90p-51, 0x0.d20a9e48640570p-60, // x in subrange 0:14 (0.609375..0.617188)
 0x0.8bab900b6122b0p0, 0x0.e6bcb02c0e1b70p-9, -0x0.d35328c10f8438p-16, 0x0.a96ded1410e428p-28, 0x0.ccbf745d2461a0p-33, -0x0.ed5aa4a6aea3b0p-43, -0x0.dfdbd043181568p-51, 0x0.d713fc66878bc0p-60, // x in subrange 0:15 (0.617188..0.625)
 0x0.8c8effca036258p0, 0x0.e0232e9022ea38p-9, -0x0.d30a0fee565d00p-16, 0x0.dc5287de1e7948p-28, 0x0.ca61117736e9d8p-33, -0x0.f7b5618c177fc8p-43, -0x0.d9e95b8ee65b20p-51, 0x0.dbdb65c769f0a0p-60, // x in subrange 0:16 (0.625..0.632812)
 0x0.8d6bd744cc32c8p0, 0x0.d98c41c51b5c50p-9, -0x0.d2adfe350c68a8p-16, 0x0.874e2a86868290p-27, 0x0.c7e92592a26c10p-33, -0x0.80e3fe0b0d1530p-42, -0x0.d3d65bcb9949c0p-51, 0x0.e060282274e658p-60, // x in subrange 0:17 (0.632812..0.640625)
 0x0.8e42195c21dff0p0, 0x0.d2f880a6cc1850p-9, -0x0.d23f2ed1e2a5c8p-16, 0x0.a022848a058390p-27, 0x0.c55866e44e4340p-33, -0x0.85c87c5c60edf0p-42, -0x0.cda4a5bb953300p-51, 0x0.e4a1a7a6ab7a98p-60, // x in subrange 0:18 (0.640625..0.648438)
 0x0.8f11c986567790p0, 0x0.cc68802dc9cda0p-9, -0x0.d1bddf5545ca28p-16, 0x0.b8a34333e8aae8p-27, 0x0.c2af8f3a73d660p-33, -0x0.8a8778fcbdbc78p-42, -0x0.c756121558fb50p-51, 0x0.e89f5ef75dbc60p-60, // x in subrange 0:19 (0.648438..0.65625)
 0x0.8fdaebcdbb5188p0, 0x0.c5dcd35d10ca58p-9, -0x0.d12a4f91f35c50p-16, 0x0.d0cd6f2f06b968p-27, 0x0.bfef5bc53ae870p-33, -0x0.8f204c4d6c2278p-42, -0x0.c0ec7ce672e1f0p-51, 0x0.ec58df20843668p-60, // x in subrange 0:20 (0.65625..0.664062)
 0x0.909d84cea28590p0, 0x0.bf560b303930c8p-9, -0x0.d084c18b3d9f58p-16, 0x0.e89e28ff730590p-27, 0x0.bd188cdef1b328p-33, -0x0.939259e07b38c8p-42, -0x0.ba69c4f6e3b5f0p-51, 0x0.efcdcf82dd3860p-60, // x in subrange 0:21 (0.664062..0.671875)
 0x0.915999b54edcd0p0, 0x0.b8d4b68a3a40b8p-9, -0x0.cfcd7963038bb0p-16, 0x0.800954b220b810p-26, 0x0.ba2be5d3f326b0p-33, -0x0.97dd10874b07c8p-42, -0x0.b3cfcb2d29c718p-51, 0x0.f2fdedb7e93e38p-60, // x in subrange 0:22 (0.671875..0.679688)
 0x0.920f303bd2cf18p0, 0x0.b2596224beff58p-9, -0x0.cf04bd47621760p-16, 0x0.8b9420d9217b70p-26, 0x0.b72a2caa4d9400p-33, -0x0.9bffea5d71c998p-42, -0x0.ad2071f32c0960p-51, 0x0.f5e90d6de70110p-60, // x in subrange 0:23 (0.679688..0.6875)
 0x0.92be4ea7df1e48p0, 0x0.abe498800e5de8p-9, -0x0.ce2ad5602415c0p-16, 0x0.96ee2e13da0ad8p-26, 0x0.b41429e93bee18p-33, -0x0.9ffa6cd001dd00p-42, -0x0.a65d9c9c3cf280p-51, 0x0.f88f183bf2e3b8p-60, // x in subrange 0:24 (0.6875..0.695312)
 0x0.9366fbc881a490p0, 0x0.a576e1d388d568p-9, -0x0.cd400bbbf5fb28p-16, 0x0.a2163e1c6c3508p-26, 0x0.b0eaa86083acf8p-33, -0x0.a3cc28a1379ce0p-42, -0x0.9f892ecc6b9468p-51, 0x0.faf00d6e7079c8p-60, // x in subrange 0:25 (0.695312..0.703125)
 0x0.94093ef3d4ebb0p0, 0x0.9f10c3febd4318p-9, -0x0.cc44ac3d62d3e8p-16, 0x0.ad0b1f6ac0a608p-26, 0x0.adae74efc93650p-33, -0x0.a774b9e8979130p-42, -0x0.98a50be1585e90p-51, 0x0.fd0c01cbe7daa0p-60, // x in subrange 0:26 (0.703125..0.710938)
 0x0.94a52004a12580p0, 0x0.98b2c27b16a660p-9, -0x0.cb3904879fbdf8p-16, 0x0.b7cbad53bfa440p-26, 0x0.aa605e4dec8248p-33, -0x0.aaf3c80f86ad28p-42, -0x0.91b3165cc1c0f0p-51, 0x0.fee31f528348c0p-60, // x in subrange 0:27 (0.710938..0.71875)
 0x0.953aa757ef1f20p0, 0x0.925d5e4e2437b0p-9, -0x0.ca1d63eb2b3540p-16, 0x0.c256d025004f00p-26, 0x0.a70134d07f7fc8p-33, -0x0.ae4905ca678390p-42, -0x0.8ab52f50fbab88p-51, 0x0.803ad2772e38c8p-59, // x in subrange 0:28 (0.71875..0.726562)
 0x0.95c9ddca8dca08p0, 0x0.8c1115fc7d2360p-9, -0x0.c8f21b52457e70p-16, 0x0.ccab7d3cf08470p-26, 0x0.a391ca336780e0p-33, -0x0.b174310e488780p-42, -0x0.83ad35cf838fa8p-51, 0x0.80e1f3146592b8p-59, // x in subrange 0:29 (0.726562..0.734375)
 0x0.9652ccb68af728p0, 0x0.85ce657d410bc8p-9, -0x0.c7b77d2d477a00p-16, 0x0.d6c8b71f78a870p-26, 0x0.a012f160baba70p-33, -0x0.b4751303309658p-42, -0x0.f93a0cb3c24850p-52, 0x0.8167256874f3e0p-59, // x in subrange 0:30 (0.734375..0.742188)
 0x0.96d57df09fe158p0, 0x0.ff2b8c5c6c9238p-10, -0x0.c66ddd5edd21a0p-16, 0x0.e0ad8d871f9408p-26, 0x0.9c857e38ea9b88p-33, -0x0.b74b7ff3182440p-42, -0x0.eb0cf4aa056960p-52, 0x0.81caa74ec38a88p-59, // x in subrange 0:31 (0.742188..0.75)
 0x0.9751fbc5922530p0, 0x0.f2cf5d910d6b08p-10, -0x0.c515912828ec98p-16, 0x0.ea591d72b3fef0p-26, 0x0.98ea455b4b7748p-33, -0x0.b9f757359e7948p-42, -0x0.dcd6cefe847d68p-52, 0x0.820cc0645dce50p-59, // x in subrange 0:32 (0.75..0.757812)
 0x0.97c850f789c528p0, 0x0.e68926ac3751d0p-10, -0x0.c3aeef14d54e00p-16, 0x0.f3ca912f81ba80p-26, 0x0.95421bef09ac98p-33, -0x0.bc7883188b7768p-42, -0x0.ce9b3ed27e0eb0p-52, 0x0.822dc1d2b13418p-59, // x in subrange 0:33 (0.757812..0.765625)
 0x0.983888bb5cd9c8p0, 0x0.da59ca4f333ea0p-10, -0x0.c23a4ee7197590p-16, 0x0.fd0120601a14d0p-26, 0x0.918dd76c9c2130p-33, -0x0.becef8c52f62f0p-42, -0x0.c05ddde36b6280p-52, 0x0.822e061756c480p-59, // x in subrange 0:34 (0.765625..0.773438)
 0x0.98a2aeb5d18d08p0, 0x0.ce422595f7b630p-10, -0x0.c0b80983b670b0p-16, 0x0.82fe07ffdbdab8p-25, 0x0.8dce4d67c38c90p-33, -0x0.c0fab822b31ea8p-42, -0x0.b2223b88fe4d50p-52, 0x0.820df0c90c0d90p-59, // x in subrange 0:35 (0.773438..0.78125)
 0x0.9906cef8d701e0p0, 0x0.c2431005a05780p-10, -0x0.bf2878ddf1bb10p-16, 0x0.875d5931239d48p-25, 0x0.8a04535a25b0b0p-33, -0x0.c2fbcbb56c38b8p-42, -0x0.a3ebdbb9b9db78p-52, 0x0.81cdee59fac350p-59, // x in subrange 0:36 (0.78125..0.789062)
 0x0.9964f600b5c740p0, 0x0.b65d5b7c25b358p-10, -0x0.bd8bf7e3924088p-16, 0x0.8b9e33988f65c8p-25, 0x0.8630be6e933a68p-33, -0x0.c4d2487b490800p-42, -0x0.95be36166f65f8p-52, 0x0.816e73d7702ce0p-59, // x in subrange 0:37 (0.789062..0.796875)
 0x0.99bd30b1387740p0, 0x0.aa91d421551f40p-10, -0x0.bbe2e268e4c1c8p-16, 0x0.8fc04db237df20p-25, 0x0.8254634d069e08p-33, -0x0.c67e4dc569f138p-42, -0x0.879cb4fce600d8p-52, 0x0.80effea7263400p-59, // x in subrange 0:38 (0.796875..0.804688)
 0x0.9a0f8c52cd2218p0, 0x0.9ee1405907e6b0p-10, -0x0.ba2d9514cc7af8p-16, 0x0.93c3649cbf27b0p-25, 0x0.fce02bced3ad38p-34, -0x0.c800050efdb6c0p-42, -0x0.f3156943dce920p-53, 0x0.80531442409260p-59, // x in subrange 0:39 (0.804688..0.8125)
 0x0.9a5c168fa02420p0, 0x0.934c60b698ef58p-10, -0x0.b86c6d4ce4daf8p-16, 0x0.97a73c12d623e8p-25, 0x0.f509528e6102c8p-34, -0x0.c957a1d1777740p-42, -0x0.d7170466444bd0p-53, 0x0.ff3083dc425958p-60, // x in subrange 0:40 (0.8125..0.820312)
 0x0.9aa2dd70b10638p0, 0x0.87d3eff1979a50p-10, -0x0.b69fc921b90340p-16, 0x0.9b6b9e63321ec8p-25, 0x0.ed25deb7a6b508p-34, -0x0.ca85615635b480p-42, -0x0.bb44b6010ee4f0p-53, 0x0.fd8038e66e58b0p-60, // x in subrange 0:41 (0.820312..0.828125)
 0x0.9ae3ef5ae20690p0, 0x0.f8f145b76cbf58p-11, -0x0.b4c8073b15b5f0p-16, 0x0.9f105c66f9f5f0p-25, 0x0.e5377194735428p-34, -0x0.cb898a85b265c8p-42, -0x0.9fa4d75ca43cb8p-53, 0x0.fb967fa3d9b368p-60, // x in subrange 0:42 (0.828125..0.835938)
 0x0.9b1f5b0c02e748p0, 0x0.e27650afe6b2e8p-11, -0x0.b2e586c47a3f48p-16, 0x0.a2954d76b27110p-25, 0x0.dd3fa97a396e08p-34, -0x0.cc646db454b6a8p-42, -0x0.843d9edde4f2d0p-53, 0x0.f9749debb128d8p-60, // x in subrange 0:43 (0.835938..0.84375)
 0x0.9b552f97d79f68p0, 0x0.cc3852a5f154c8p-11, -0x0.b0f8a759acd180p-16, 0x0.a5fa4f5db1c3f8p-25, 0x0.d540216ce1b178p-34, -0x0.cd16646cfda578p-42, -0x0.d22a3d16879160p-54, 0x0.f71be6ceab28c8p-60, // x in subrange 0:44 (0.84375..0.851562)
 0x0.9b857c651b8988p0, 0x0.b638917964cc38p-11, -0x0.af01c8f376b0d8p-16, 0x0.a93f464c229500p-25, 0x0.cd3a70c3be8210p-34, -0x0.cd9fd139693a10p-42, -0x0.9c6285465d6028p-54, 0x0.f48db9f752ac78p-60, // x in subrange 0:45 (0.851562..0.859375)
 0x0.9bb0512a81aa40p0, 0x0.a07847062eb710p-11, -0x0.ad014bd48c74c0p-16, 0x0.ac641cc79f37d8p-25, 0x0.c5302ad0b62b80p-34, -0x0.ce011f687e87f8p-42, -0x0.ce5f4110542cd8p-55, 0x0.f1cb8307b57bf8p-60, // x in subrange 0:46 (0.859375..0.867188)
 0x0.9bd5bdebb2a718p0, 0x0.8af8a11c43bd80p-11, -0x0.aaf79076a68760p-16, 0x0.af68c39a6e2048p-25, 0x0.bd22de89b7dcb0p-34, -0x0.ce3ac2d2a91c90p-42, -0x0.ca732132818268p-56, 0x0.eed6b8f4c02030p-60, // x in subrange 0:47 (0.867188..0.875)
 0x0.9bf5d2f6490550p0, 0x0.eb7582f3d5b758p-12, -0x0.a8e4f777cdf2b8p-16, 0x0.b24d31c168de78p-25, 0x0.b51416348e8478p-34, -0x0.ce4d379c56dac0p-42, 0x0.a58e97d4df38e8p-61, 0x0.ebb0dd5f91ca68p-60, // x in subrange 0:48 (0.875..0.882812)
 0x0.9c10a0decc45d0p0, 0x0.c17f7b90b73038p-12, -0x0.a6c9e187e16cc8p-16, 0x0.b5116458974098p-25, 0x0.ad055715239c38p-34, -0x0.ce3901f6b59c08p-42, 0x0.d1f5fc9e0dc9c0p-56, 0x0.e85b7bed125f78p-60, // x in subrange 0:49 (0.882812..0.890625)
 0x0.9c26387dab7260p0, 0x0.98113f354fc2e0p-12, -0x0.a4a6af565677f8p-16, 0x0.b7b55e86887c28p-25, 0x0.a4f8211e42d810p-34, -0x0.cdfeaddecc3700p-42, 0x0.cde048d6d03cf0p-55, 0x0.e4d8299c1497a8p-60, // x in subrange 0:50 (0.890625..0.898438)
 0x0.9c36aaec37ae18p0, 0x0.de5991bba75448p-13, -0x0.a27bc1803a4e00p-16, 0x0.ba392966748250p-25, 0x0.9cedeea4eea018p-34, -0x0.cd9ecedb0ac948p-42, 0x0.98992d5a7b9c78p-54, 0x0.e128841a4dc6e0p-60, // x in subrange 0:51 (0.898438..0.90625)
 0x0.9c4209819f58a0p0, 0x0.8da7f6c6b4ef70p-13, -0x0.a049787e762e10p-16, 0x0.bc9cd3f12fe098p-25, 0x0.94e83416541d30p-34, -0x0.cd19ffb76e5298p-42, 0x0.c96f15b6027190p-54, 0x0.dd4e31186c6078p-60, // x in subrange 0:52 (0.90625..0.914062)
 0x0.9c4865cfea52b0p0, 0x0.f8450c38c183c0p-15, -0x0.9e1034945a85f0p-16, 0x0.bee072e4fcc7e8p-25, 0x0.8ce85fb06c8c18p-34, -0x0.cc70e24053d550p-42, 0x0.f968b64f2ca0f8p-54, 0x0.d94add9d95ab48p-60, // x in subrange 0:53 (0.914062..0.921875)
 0x0.9c49d1a0f7eed8p0, -0x0.83391fe15964e0p-16, -0x0.9bd055be744f10p-16, 0x0.c10420ac4408c8p-25, 0x0.84efd93d586d80p-34, -0x0.cba41efc174810p-42, 0x0.943ea3478cc630p-53, 0x0.d5203d5a925b30p-60, // x in subrange 0:54 (0.921875..0.929688)
 0x0.9c465ef37f1878p0, -0x0.bb7c119f663650p-14, -0x0.998a3ba1afd6c0p-16, 0x0.c307fd43410320p-25, 0x0.fa0003a3001f20p-35, -0x0.cab464e39ab300p-42, 0x0.ab522eec857458p-53, 0x0.d0d009fcf0e760p-60, // x in subrange 0:55 (0.929688..0.9375)
 0x0.9c3e1ff8113750p0, -0x0.a9f0659cd66af0p-13, -0x0.973e457acc0878p-16, 0x0.c4ec2e1cabb470p-25, 0x0.ea34671907a2a0p-35, -0x0.c9a26919d1d3b0p-42, 0x0.c1eafa63661938p-53, 0x0.cc5c0282637950p-60, // x in subrange 0:56 (0.9375..0.945312)
 0x0.9c31270e205470p0, -0x0.f4fb6414f53030p-13, -0x0.94ecd20e212e90p-16, 0x0.c6b0de056c3640p-25, 0x0.da7f82ba0ac9e0p-35, -0x0.c86ee6a26e99b0p-42, 0x0.d805331fb19bb0p-53, 0x0.c7c5ea8c9e37f8p-60, // x in subrange 0:57 (0.945312..0.953125)
 0x0.9c1f86c10901f8p0, -0x0.9f6e2e95186ef0p-12, -0x0.92963f97bdfbd0p-16, 0x0.c8563d07632140p-25, 0x0.cae3ed8ea47668p-35, -0x0.c71a9e17cab840p-42, 0x0.ed9d38341699a8p-53, 0x0.c30f89b5f97d98p-60, // x in subrange 0:58 (0.953125..0.960938)
 0x0.9c0951c52084f8p0, -0x0.c3c86c63b09bf8p-12, -0x0.903aebbbdd8e90p-16, 0x0.c9dc804b526860p-25, 0x0.bb642f5dec51a0p-35, -0x0.c5a655602a6a00p-42, 0x0.8157cd5c26a8e8p-52, 0x0.be3aaae71a37f0p-60, // x in subrange 0:59 (0.960938..0.96875)
 0x0.9bee9af4c7bdd0p0, -0x0.e78b46c02d86d0p-12, -0x0.8ddb3377b8f950p-16, 0x0.cb43e1f9f25938p-25, 0x0.ac02c046787aa8p-35, -0x0.c412d762745820p-42, 0x0.8b9c8f0e329230p-52, 0x0.b9491bade14840p-60, // x in subrange 0:60 (0.96875..0.976562)
 0x0.9bcf754d834840p0, -0x0.855ad80eadc6f0p-11, -0x0.8b777312b6bc00p-16, 0x0.cc8ca11c3e8440p-25, 0x0.9cc2085d455be8p-35, -0x0.c260f3ba7a6098p-42, 0x0.959b5c34d47520p-52, 0x0.b43cab95e136b0p-60, // x in subrange 0:61 (0.976562..0.984375)
 0x0.9babf3ed1949c8p0, -0x0.96a358f3d22848p-11, -0x0.8910060ffa7390p-16, 0x0.cdb7017b0661a8p-25, 0x0.8da45f528b42f8p-35, -0x0.c0917e6ceeb828p-42, 0x0.9f52c938a41c30p-52, 0x0.af172b8297f2f8p-60, // x in subrange 0:62 (0.984375..0.992188)
 0x0.9b842a0eb561f8p0, -0x0.a79eb6291d12d8p-11, -0x0.86a5472056e340p-16, 0x0.cec34b7dcd93a0p-25, 0x0.fd5818390e66a0p-36, -0x0.bea54f9b209918p-42, 0x0.a8c183f47d2730p-52, 0x0.a9da6d0ba8aa80p-60, // x in subrange 0:63 (0.992188..1)
 0x0.9b409da707bdc8p0, -0x0.c08646040f1db0p-10, -0x0.82ffb35504d5f8p-14, 0x0.d01df9faebaf38p-22, 0x0.d104c2e5e15488p-32, -0x0.bb8f0fa06ea3d0p-37, 0x0.b65eaeecacfe20p-46, 0x0.a1d73835166338p-53, // x in subrange 1:0 (1..1.01562)
 0x0.9ad84498e51b48p0, -0x0.e0a9bb2659e818p-10, -0x0.fc351bcf7a34f8p-15, 0x0.d185db7ff3b300p-22, 0x0.971874a331b350p-32, -0x0.b714fd235354a0p-37, 0x0.c779ebaa899bb8p-46, 0x0.96e89ef0720700p-53, // x in subrange 1:1 (1.01562..1.03125)
 0x0.9a60284bea1e98p0, -0x0.ff92f5ccc68638p-10, -0x0.f25ca3be22aaa0p-15, 0x0.d27b550f2bc4d8p-22, 0x0.bd43ead4e40888p-33, -0x0.b237e4f2fd22d8p-37, 0x0.d75f99cd7c5ed8p-46, 0x0.8bbda5f4637478p-53, // x in subrange 1:2 (1.03125..1.04688)
 0x0.99d8e640892d20p0, -0x0.8ea042afde9170p-9, -0x0.e87b495653fad8p-15, 0x0.d3017075fd3d30p-22, 0x0.9efc4b81a1bc80p-34, -0x0.acff1a8fc69878p-37, 0x0.e609e73cb1b9e8p-46, 0x0.806492dba09e78p-53, // x in subrange 1:3 (1.04688..1.0625)
 0x0.99431c858c84c8p0, -0x0.9cd8d026dc5590p-9, -0x0.de9631a64d1f08p-15, 0x0.d31b70cf9dcf18p-22, -0x0.d74b466d9fabc8p-36, -0x0.a7720fbe1ecca0p-37, 0x0.f3748e652323c0p-46, 0x0.e9d6de6a7eba00p-54, // x in subrange 1:4 (1.0625..1.07812)
 0x0.989f6965c8c7e0p0, -0x0.aa730f93996d40p-9, -0x0.d4b259566d40b8p-15, 0x0.d2cccdde6f9270p-22, -0x0.81c071d7736ae8p-33, -0x0.a1984b51194ea8p-37, 0x0.ff9cceb6fc5a90p-46, 0x0.d2bfeef2bbb0f0p-54, // x in subrange 1:5 (1.07812..1.09375)
 0x0.97ee6b18559c38p0, -0x0.b76f3bb5cb9578p-9, -0x0.cad4924d8a1668p-15, 0x0.d2192f58354580p-22, -0x0.e4d95edb76eb38p-33, -0x0.9b79602788a278p-37, 0x0.8540b1a9c12340p-45, 0x0.bb9f15f9caf7a0p-54, // x in subrange 1:6 (1.09375..1.10938)
 0x0.9730bf737216f0p0, -0x0.c3cddb0724d1e0p-9, -0x0.c101818de69bf0p-15, 0x0.d104682abc0810p-22, -0x0.a205ab4e8df6a0p-32, -0x0.951ce4662a7dc8p-37, 0x0.8a113c042da6a0p-45, 0x0.a48e39eb6a2bc0p-54, // x in subrange 1:7 (1.10938..1.125)
 0x0.966703a2372610p0, -0x0.cf8fbcdd6ceda0p-9, -0x0.b73d9d4b0398d0p-15, 0x0.cf9271be75b1f8p-22, -0x0.cf991e42167808p-32, -0x0.8e8a68f8ba4ef0p-37, 0x0.8e40ce5b6de830p-45, 0x0.8da64d3c319268p-54, // x in subrange 1:8 (1.125..1.14062)
 0x0.9591d3dd369a18p0, -0x0.dab5f66fbecc90p-9, -0x0.ad8d2b3842a408p-15, 0x0.cdc7673c529fe0p-22, -0x0.fb17556318aa78p-32, -0x0.87c97163022ac8p-37, 0x0.91d0dba3bc6f68p-45, 0x0.edfe6a102513a8p-55, // x in subrange 1:9 (1.14062..1.15625)
 0x0.94b1cb2621e680p0, -0x0.e541dfc274d768p-9, -0x0.a3f43f1015caf8p-15, 0x0.cba780dbf7dcc8p-22, -0x0.923979e365e7b8p-31, -0x0.80e16bea3da200p-37, 0x0.94c37a255f2a40p-45, 0x0.c15f6438f1ff30p-55, // x in subrange 1:10 (1.15625..1.17188)
 0x0.93c78306902618p0, -0x0.ef35107d498c20p-9, -0x0.9a76b95339e9d8p-15, 0x0.c9370f3f376620p-22, -0x0.a5d0755614a6a8p-31, -0x0.f3b3543cad96b0p-38, 0x0.971b5b350e6298p-45, 0x0.959a98fa96b798p-55, // x in subrange 1:11 (1.17188..1.1875)
 0x0.92d39351f77110p0, -0x0.f8915caf274de8p-9, -0x0.9118463f4063e8p-15, 0x0.c67a76df746a78p-22, -0x0.b84c37b2fd92e0p-31, -0x0.e572b3936b3aa0p-38, 0x0.98dbc265cb94e8p-45, 0x0.d5b105bce87d30p-56, // x in subrange 1:12 (1.1875..1.20312)
 0x0.91d691eaea1d78p0, -0x0.80ac68c18a9120p-8, -0x0.87dc5cfb766e90p-15, 0x0.c3762b915d52f0p-22, -0x0.c9a9779054a2f8p-31, -0x0.d70efc9b0c22a0p-38, 0x0.9a087c45e4ba48p-45, 0x0.827dd03477dcb8p-56, // x in subrange 1:13 (1.20312..1.21875)
 0x0.90d1128ba51ca8p0, -0x0.84c6d8f4cea6f8p-8, -0x0.fd8c7df6097fc8p-16, 0x0.c02eac2321a7d8p-22, -0x0.d9e600533d5b90p-31, -0x0.c895d4df080c48p-38, 0x0.9aa5d4b8f8b350p-45, 0x0.c78606990a2560p-58, // x in subrange 1:14 (1.21875..1.23438)
 0x0.8fc3a691f95600p0, -0x0.8899399cfb75b8p-8, -0x0.ebb1ef25e49e60p-16, 0x0.bca87e1902f908p-22, -0x0.e900aa23397bd8p-31, -0x0.ba14753b0bdf90p-38, 0x0.9ab88d00ca25a8p-45, -0x0.df1dd8cfaea8b0p-59, // x in subrange 1:15 (1.23438..1.25)
 0x0.8eaedcce96a080p0, -0x0.8c24dce71269e8p-8, -0x0.da2eb785102e70p-16, 0x0.b8e8298bd665b8p-22, -0x0.f6f95101922410p-31, -0x0.ab979f54551570p-38, 0x0.9a45d1868876e0p-45, -0x0.cd2f3ffd632bd0p-57, // x in subrange 1:16 (1.25..1.26562)
 0x0.8d934157bbd748p0, -0x0.8f6b2ace916300p-8, -0x0.c9081458d513f0p-16, 0x0.b4f2352cc0b570p-22, -0x0.81e8658bef8578p-30, -0x0.9d2b940a76c4f0p-38, 0x0.99532f75f40240p-45, -0x0.ae05e1383f4158p-56, // x in subrange 1:17 (1.26562..1.28125)
 0x0.8c715d5f4c79e0p0, -0x0.926d9f6b0ee6e0p-8, -0x0.b842d67d2f7b58p-16, 0x0.b0cb227129ac90p-22, -0x0.87c46f2892f5f8p-30, -0x0.8edc0ae30eb3d8p-38, 0x0.97e68a3b64bc90p-45, -0x0.f20039115bf2c8p-56, // x in subrange 1:18 (1.28125..1.29688)
 0x0.8b49b70c495b00p0, -0x0.952dc93fcb6530p-8, -0x0.a7e3630eaeaee8p-16, 0x0.ac7769e994e730p-22, -0x0.8d121aa8a18208p-30, -0x0.80b42a725d89d8p-38, 0x0.960610f542ea80p-45, -0x0.992f353e18d4a8p-55, // x in subrange 1:19 (1.29688..1.3125)
 0x0.8a1cd157a71158p0, -0x0.97ad478e96e5f8p-8, -0x0.97edb46a15cd38p-16, 0x0.a7fb77c5bf87f0p-22, -0x0.91d329ef318b30p-30, -0x0.e57d03825cb8c0p-39, 0x0.93b833e8f22bb0p-45, -0x0.b77f1d5406ae68p-55, // x in subrange 1:20 (1.3125..1.32812)
 0x0.88eb2bec7a30e0p0, -0x0.99edc8af5987a0p-8, -0x0.88655b7d658c58p-16, 0x0.a35ba88812e938p-22, -0x0.9609c568288b88p-30, -0x0.ca0a055e02bcd0p-39, 0x0.91039a0a89dc08p-45, -0x0.d3e1b102096ee0p-55, // x in subrange 1:21 (1.32812..1.34375)
 0x0.87b5430b6ec690p0, -0x0.9bf1086d7b73e8p-8, -0x0.f29b02cb92c858p-17, 0x0.9e9c45ea2db408p-22, -0x0.99b875cc9b3d90p-30, -0x0.af21fa9c0b02c8p-39, 0x0.8def16a5fcb7b0p-45, -0x0.ee4bba8ef86c10p-55, // x in subrange 1:22 (1.34375..1.35938)
 0x0.867b8f717e2ac8p0, -0x0.9db8ce6c568c48p-8, -0x0.d551d2ab7805a0p-17, 0x0.99c183f3f6b7c0p-22, -0x0.9ce21dbd974f00p-30, -0x0.94d6386a2e16a0p-39, 0x0.8a819f3786de40p-45, -0x0.835a717546aed0p-54, // x in subrange 1:23 (1.35938..1.375)
 0x0.853e8641d3fc38p0, -0x0.9f46ec93c91d68p-8, -0x0.b8f3e57d2f75a8p-17, 0x0.94cf7e466004a8p-22, -0x0.9f89f33eda9760p-30, -0x0.f66d870adc7510p-40, 0x0.86c241805ef378p-45, -0x0.8e8bcf58d4ab50p-54, // x in subrange 1:24 (1.375..1.39062)
 0x0.83fe98f2d0fa48p0, -0x0.a09d3d85ed8a78p-8, -0x0.9d8537715f12a8p-17, 0x0.8fca359ab585e8p-22, -0x0.a1b3791ac360f8p-30, -0x0.c4a4992b0ced00p-40, 0x0.82b819e3bf5f20p-45, -0x0.98b88bf093f060p-54, // x in subrange 1:25 (1.39062..1.40625)
 0x0.82bc353e188130p0, -0x0.a1bda31ee72d18p-8, -0x0.83090749f87158p-17, 0x0.8ab58d770901a8p-22, -0x0.a36278388194d8p-30, -0x0.946c5c9e74f958p-40, 0x0.fcd4942ed39018p-46, -0x0.a1e08a3f02f7c8p-54, // x in subrange 1:26 (1.40625..1.42188)
 0x0.8177c513939db8p0, -0x0.a2aa04ffa0c060p-8, -0x0.d303b80d7b4160p-18, 0x0.85954a18065b10p-22, -0x0.a49af8ed426e20p-30, -0x0.cbb9b533a54288p-41, 0x0.f3bfe063961700p-46, -0x0.aa04ed3df0ceb8p-54, // x in subrange 1:27 (1.42188..1.4375)
 0x0.8031ae8f530a50p0, -0x0.a3644f2444a608p-8, -0x0.a1e315e1d6e3b8p-18, 0x0.806d0e90367be8p-22, -0x0.a5613c50b8a818p-30, -0x0.e42dcc57acee00p-42, 0x0.ea403c3dc69dc0p-46, -0x0.b12808963c66a8p-54, // x in subrange 1:28 (1.4375..1.45312)
 0x0.fdd4a7e46fd320p-1, -0x0.a3ee7087234f38p-8, -0x0.e564f7f023d328p-19, 0x0.f680b638eb7260p-23, -0x0.a5b9b59d02da00p-30, -0x0.e0ae2e7f13ab50p-44, 0x0.e063a3081d0738p-46, -0x0.b74d5041e9b208p-54, // x in subrange 1:29 (1.45312..1.46875)
 0x0.fb44273a937d38p-1, -0x0.a44a59d0a82028p-8, -0x0.8ae5e9c7b3d938p-19, 0x0.ec25175a4822e8p-23, -0x0.a5a903a189d868p-30, 0x0.d8a5998b7fc9c8p-43, 0x0.d637d8337fbec0p-46, -0x0.bc79473e9b3670p-54, // x in subrange 1:30 (1.46875..1.48438)
 0x0.f8b2901f3ded28p-1, -0x0.a479fc14e96218p-8, -0x0.d1227e026b2a18p-21, 0x0.e1cdad46b51900p-23, -0x0.a533ea50027628p-30, 0x0.848b75738c5598p-41, 0x0.cbca590270d280p-46, -0x0.c0b16d766ee170p-54, // x in subrange 1:31 (1.48438..1.5)
 0x0.f6208fcd78a0b0p-1, -0x0.a47f479f4c56e8p-8, 0x0.f3ad185c3d3b20p-22, 0x0.d780978272e9a0p-23, -0x0.a45f4c6a49dba8p-30, 0x0.cefa3e157bb398p-41, 0x0.c1284f366f7da8p-46, -0x0.c3fc2d04e82a08p-54, // x in subrange 1:32 (1.5..1.51562)
 0x0.f38ecbc29d2378p-1, -0x0.a45c2acca35a78p-8, 0x0.dab3ae24770c68p-20, 0x0.cd43a6985e95e8p-23, -0x0.a33025575ad680p-30, 0x0.8ab23a815eedd0p-40, 0x0.b65e84c740db00p-46, -0x0.c660c6fcfb90c0p-54, // x in subrange 1:33 (1.51562..1.53125)
 0x0.f0fde1c8427ee0p-1, -0x0.a41290f41940d8p-8, 0x0.b86b14f6c5eff0p-19, 0x0.c31c5abfd09f48p-23, -0x0.a1ab83251df5d0p-30, 0x0.abdec377119f28p-40, 0x0.ab7958aa10d2d0p-46, -0x0.c7e73fd47c6cd0p-54, // x in subrange 1:34 (1.53125..1.54688)
 0x0.ee6e680268f288p-1, -0x0.a3a4615f2ae480p-8, 0x0.ffb275f8bbcba0p-19, 0x0.b90fe2e0d4dd20p-23, -0x0.9fd680bc56ef98p-30, 0x0.cafeb739caaed8p-40, 0x0.a084b4ac67d010p-46, -0x0.c8984b98220a98p-54, // x in subrange 1:35 (1.54688..1.5625)
 0x0.ebe0ed01a75908p-1, -0x0.a3137e50de25f0p-8, 0x0.a19d7acaabf450p-18, 0x0.af231bf37287e0p-23, -0x0.9db6404b7094c0p-30, 0x0.e81043374fb880p-40, 0x0.958c04650d5cf8p-46, -0x0.c87d3a0a1908a8p-54, // x in subrange 1:36 (1.5625..1.57812)
 0x0.e955f7d91d0018p-1, -0x0.a261c41c548ea0p-8, 0x0.c188a95e88d088p-18, 0x0.a55a90b673ea80p-23, -0x0.9b4fe5ec6666c0p-30, 0x0.8189d647de8030p-39, 0x0.8a9a2d3b1e2e00p-46, -0x0.c79fe2cba67878p-54, // x in subrange 1:37 (1.57812..1.59375)
 0x0.e6ce0837ea65c8p-1, -0x0.a191084ac76058p-8, 0x0.dfa1f87ec753e8p-18, 0x0.9bba79b9dd4c70p-23, -0x0.98a89289888c90p-30, 0x0.8e059b21acb0f0p-39, 0x0.ff730f03bfa450p-47, -0x0.c60a91b0c88e50p-54, // x in subrange 1:38 (1.59375..1.60938)
 0x0.e4499685f332f0p-1, -0x0.a0a318d0eb2b28p-8, 0x0.fbf15cdf48e628p-18, 0x0.9246bdb90ae970p-23, -0x0.95c55f04553e50p-30, 0x0.997d8317ab9038p-39, 0x0.e9e7b14c6ec130p-47, -0x0.c3c7f35b01b940p-54, // x in subrange 1:39 (1.60938..1.625)
 0x0.e1c91403abf210p-1, -0x0.9f99bb53aa14e8p-8, 0x0.8b3fbf6bbf0fd0p-17, 0x0.8902f2403e1f18p-23, -0x0.92ab57a1228b28p-30, 0x0.a3f4848632f638p-39, 0x0.d4a49cd239efc0p-47, -0x0.c0e302369bff88p-54, // x in subrange 1:40 (1.625..1.64062)
 0x0.df4ceaecb660d8p-1, -0x0.9e76ac7c15d9a8p-8, 0x0.97aad59f568f60p-17, 0x0.ffe4b932747a60p-24, -0x0.8f5f77b9d55728p-30, 0x0.ad6e6ad07c2990p-39, 0x0.bfbaf641eaa700p-47, -0x0.bd66f3f3b8a258p-54, // x in subrange 1:41 (1.64062..1.65625)
 0x0.dcd57e9d0fd218p-1, -0x0.9d3b9f5a653988p-8, 0x0.a33ee23d727e28p-17, 0x0.ee2fe5f4e2eb70p-24, -0x0.8be6a5b9674108p-30, 0x0.b5efc7abed2140p-39, 0x0.ab3aa5f4ccec78p-47, -0x0.b95f2792707a90p-54, // x in subrange 1:42 (1.65625..1.67188)
 0x0.da632bb895dfa8p-1, -0x0.9bea3cd7c40db0p-8, 0x0.ae0119e755bcc8p-17, 0x0.dcecbbe85422e8p-24, -0x0.8845af61856bd0p-30, 0x0.bd7de4351a5330p-39, 0x0.973254600aed08p-47, -0x0.b4d71417294cb8p-54, // x in subrange 1:43 (1.67188..1.6875)
 0x0.d7f64854a6a6f0p-1, -0x0.9a842336b1a060p-8, 0x0.b7f6ed7849eb30p-17, 0x0.cc1ff42de620d0p-24, -0x0.8481465b1e7ee0p-30, 0x0.c41eb1e53083b8p-39, 0x0.83af685e454b58p-47, -0x0.afda37fa187160p-54, // x in subrange 1:44 (1.6875..1.70312)
 0x0.d58f2423a2f190p-1, -0x0.990ae5a19e2500p-8, 0x0.c12602fb868640p-17, 0x0.bbcdb39d6af1a8p-24, -0x0.809dfd124712d0p-30, 0x0.c9d8bb7d8295e0p-39, 0x0.e17c0e7bfc46b8p-48, -0x0.aa740962b870b8p-54, // x in subrange 1:45 (1.70312..1.71875)
 0x0.d32e08a219fce0p-1, -0x0.97800bc76e4f88p-8, 0x0.c9942ed0e9e110p-17, 0x0.abf98edb58f4f8p-24, -0x0.f94087bae35580p-31, 0x0.ceb315fdebe4d0p-39, 0x0.bcd22cfb6c1778p-48, -0x0.a4afe73dc232d8p-54, // x in subrange 1:46 (1.71875..1.73438)
 0x0.d0d33945680870p-1, -0x0.95e51185830fd0p-8, 0x0.d1476d04c93388p-17, 0x0.9ca68ec523cf68p-24, -0x0.f118ccdf255608p-31, 0x0.d2b551b99918d0p-39, 0x0.99747e3a42bee8p-48, -0x0.9e990b3a0795a0p-54, // x in subrange 1:47 (1.73438..1.75)
 0x0.ce7ef3ab926d60p-1, -0x0.943b669edb5ae0p-8, 0x0.d845dadeaca0b8p-17, 0x0.8dd7352aabfaf8p-24, -0x0.e8cd1328d3a840p-31, 0x0.d5e76b9c9a99e8p-39, 0x0.eee7c9a6817768p-49, -0x0.983a7cb660be30p-54, // x in subrange 1:48 (1.75..1.76562)
 0x0.cc316fcc2db598p-1, -0x0.92846e7fdeb280p-8, 0x0.de95b0aa5ceaf0p-17, 0x0.ff1b039722ab70p-25, -0x0.e065526ba3d460p-31, 0x0.d851beb3678e10p-39, 0x0.adbdc0ac952b38p-49, -0x0.919f04a8bb3d30p-54, // x in subrange 1:49 (1.76562..1.78125)
 0x0.c9eae02a1bfe70p-1, -0x0.90c1800e58bcc8p-8, 0x0.e43d3bbe3b0c48p-17, 0x0.e395ef1ebc6830p-25, -0x0.d7e92d514937e8p-31, 0x0.d9fcf604318980p-39, 0x0.df0670af7ae1f0p-50, -0x0.8ad1228445bd78p-54, // x in subrange 1:50 (1.78125..1.79688)
 0x0.c7ab7205f3da40p-1, -0x0.8ef3e58528ba18p-8, 0x0.e942d8c16e9598p-17, 0x0.c92143df671c68p-25, -0x0.cf5fee7ee93a58p-31, 0x0.daf1fec89a7448p-39, 0x0.d130064f6377b0p-51, -0x0.83db0222afbd98p-54, // x in subrange 1:51 (1.79688..1.8125)
 0x0.c5734d90e1e478p-1, -0x0.8d1cdc5b22f618p-8, 0x0.edacee340efd28p-17, 0x0.afbe3517b612f8p-25, -0x0.c6d0864234c238p-31, 0x0.db39fb150a4eb8p-39, -0x0.f61c7f720177d8p-55, -0x0.f98ce5650b9d88p-55, // x in subrange 1:52 (1.8125..1.82812)
 0x0.c342961fd94a20p-1, -0x0.8b3d95349e6e88p-8, 0x0.f181e73b065258p-17, 0x0.976d1dbad02750p-25, -0x0.be4188c1a20960p-31, 0x0.dade34f98bf6d0p-39, -0x0.e37b96b52e9b10p-51, -0x0.eb39bd55b551e8p-55, // x in subrange 1:53 (1.82812..1.84375)
 0x0.c1196a5ee9a738p-1, -0x0.895733df25d190p-8, 0x0.f4c82eb1097a60p-17, 0x0.802d8c0bba4ac0p-25, -0x0.b5b92caad19c28p-31, 0x0.d9e81226c14828p-39, -0x0.d580482d7df170p-50, -0x0.dcce89855cdc10p-55, // x in subrange 1:54 (1.84375..1.85938)
 0x0.bef7e48492c0f0p-1, -0x0.876acf56c09ad0p-8, 0x0.f7862a7da37fc0p-17, 0x0.d3fc9ab67302b0p-26, -0x0.ad3d4a59c65530p-31, 0x0.d86108202a2f18p-39, -0x0.9978cea10dcfa8p-49, -0x0.ce5c63d1c37d88p-55, // x in subrange 1:55 (1.85938..1.875)
 0x0.bcde1a84f0d5e0p-1, -0x0.857971d44777c0p-8, 0x0.f9c23732f6e588p-17, 0x0.a9baf3b31802a8p-26, -0x0.a4d35b73426ad8p-31, 0x0.d6529103a9b690p-39, -0x0.c5092a90c94100p-49, -0x0.bff3786ff6f0a0p-55, // x in subrange 1:56 (1.875..1.89062)
 0x0.bacc1e449e7258p-1, -0x0.838418e4362c88p-8, 0x0.fb82a3f28197e0p-17, 0x0.819100dbe71a30p-26, -0x0.9c807aec52ef50p-31, 0x0.d3c620ece9b788p-39, -0x0.ed74ec1ba01740p-49, -0x0.b1a2fdbf3ee070p-55, // x in subrange 1:57 (1.89062..1.90625)
 0x0.b8c1fdcb2aeeb8p-1, -0x0.818bb5856cec30p-8, 0x0.fccdae98de34a0p-17, 0x0.b6f0ca1b374a90p-27, -0x0.94496578d73088p-31, 0x0.d0c51bf9fb7788p-39, -0x0.89617ff33a9f18p-48, -0x0.a3792df896b7d0p-55, // x in subrange 1:58 (1.90625..1.92188)
 0x0.b6bfc37506f5f0p-1, -0x0.ff22589ea6df20p-9, 0x0.fda98030302c88p-17, 0x0.dda67eae084288p-28, -0x0.8c327a5aa1da18p-31, 0x0.cd58ccf55ae6c8p-39, -0x0.9a7ea9aa3f7370p-48, -0x0.958342a98bf110p-55, // x in subrange 1:59 (1.92188..1.9375)
 0x0.b4c57624caa710p-1, -0x0.fb2aab3da20898p-9, 0x0.fe1c29a89fcc70p-17, 0x0.aae11ec5199ca0p-29, -0x0.843fbc8aae2f48p-31, 0x0.c98a5ca84ccc50p-39, -0x0.aa184e04ee8d00p-48, -0x0.87cd71e747e730p-55, // x in subrange 1:60 (1.9375..1.95312)
 0x0.b2d31973bb14d0p-1, -0x0.f731fb931c9010p-9, 0x0.fe2ba0d607b0e0p-17, -0x0.ab990a3efe7db0p-30, -0x0.f8e9a86b975e80p-32, 0x0.c562c9d76f6a70p-39, -0x0.b8360f7fd6e5b0p-48, -0x0.f4c5da49789c18p-56, // x in subrange 1:61 (1.95312..1.96875)
 0x0.b0e8ade1771090p-1, -0x0.f339caadee7fa0p-9, 0x0.fdddbdb1b68d78p-17, -0x0.a3877b8ee8f178p-28, -0x0.e9aa210c2ae980p-32, 0x0.c0eae1ea422918p-39, -0x0.c4e0bbc16ec218p-48, -0x0.da9bc32ab55f68p-56, // x in subrange 1:62 (1.96875..1.98438)
 0x0.af063102b54ce0p-1, -0x0.ef43827cede170p-9, 0x0.fd3837deee99d8p-17, -0x0.8a4fe1c1687500p-27, -0x0.dac6d365102d48p-32, 0x0.bc2b3a3d64aa40p-39, -0x0.d0222f38ee4870p-48, -0x0.c12ef408e1a320p-56, // x in subrange 1:63 (1.98438..2)
 0x0.ac414947ee1a40p-1, -0x0.e9588ac348d848p-8, 0x0.fba7ca43850f60p-15, -0x0.d845f632d07650p-24, -0x0.c52a299e03c258p-28, 0x0.b49763eb67cdc8p-34, -0x0.de7fdbbdd0d1d0p-42, -0x0.9c97c053b9fb50p-49, // x in subrange 2:0 (2..2.03125)
 0x0.a8ab9295fed4f8p-1, -0x0.e186ec1b6f9448p-8, 0x0.f8920c38554770p-15, -0x0.99f842212a95a0p-23, -0x0.a9c80245fb3a90p-28, 0x0.a9cd68d4fa2e00p-34, -0x0.ed1633f9bef6f0p-42, -0x0.ddcb0c990cac50p-50, // x in subrange 2:1 (2.03125..2.0625)
 0x0.a534eb7e3b5380p-1, -0x0.d9d21178a64ac8p-8, 0x0.f47d6aa485b0f8p-15, -0x0.c12bfc76ef7800p-23, -0x0.90219061d89b20p-28, 0x0.9e717f73abda90p-34, -0x0.f6e25a1ef255b0p-42, -0x0.8a203cd4eecba8p-50, // x in subrange 2:2 (2.0625..2.09375)
 0x0.a1dcd1d3086fb8p-1, -0x0.d2415653f05368p-8, 0x0.ef905ce5fbfd48p-15, -0x0.e22f9378a92148p-23, -0x0.f0928c16238b50p-29, 0x0.92ba8a54304c48p-34, -0x0.fc53dc3b0faa60p-42, -0x0.fa82126c19e380p-52, // x in subrange 2:3 (2.09375..2.125)
 0x0.9ea2a8520e24a8p-1, -0x0.cadaed2df23eb8p-8, 0x0.e9eea6247c6a68p-15, -0x0.fd78037090ea28p-23, -0x0.c492d873362100p-29, 0x0.86da1248ac0618p-34, -0x0.fddf09946e8a08p-42, 0x0.8ed5e7a04516f0p-55, // x in subrange 2:4 (2.125..2.15625)
 0x0.9b85bb1c734620p-1, -0x0.c3a3f5768295d0p-8, 0x0.e3b945c8fa0718p-15, -0x0.89bdf62f4dc5b8p-22, -0x0.9c49f8c13590d0p-29, 0x0.f5f83bb1449610p-35, -0x0.fbfa3da1869050p-42, 0x0.fc5b4e27a3fa40p-52, // x in subrange 2:5 (2.15625..2.1875)
 0x0.988543d6be9b98p-1, -0x0.bca091c3c8dfd0p-8, 0x0.dd0e72ebb294c0p-15, -0x0.9258ecdf9ad360p-22, -0x0.ef61f7bbd805e0p-30, 0x0.de8e4ee02ca0d0p-35, -0x0.f71b760431f6d8p-42, 0x0.e2b56ba696f8f8p-51, // x in subrange 2:6 (2.1875..2.21875)
 0x0.95a06d6fc7ace8p-1, -0x0.b5d3fe0661bdf8p-8, 0x0.d609a16d660238p-15, -0x0.98c760da3bc630p-22, -0x0.ad6b8cb69e0508p-30, 0x0.c7b85d5c771768p-35, -0x0.efb637bc844648p-42, 0x0.9b80bd1b00b208p-50, // x in subrange 2:7 (2.21875..2.25)
 0x0.92d6578f56f418p-1, -0x0.af40a5725d28c8p-8, 0x0.cec38f70da4128p-15, -0x0.9d425d73f0add8p-22, -0x0.e4f30c4f7a7920p-31, 0x0.b1adc220886998p-35, -0x0.e639c5600518f0p-42, 0x0.bde51e178e1ec8p-50, // x in subrange 2:8 (2.25..2.28125)
 0x0.902619ae2144b0p-1, -0x0.a8e837df2acbf0p-8, 0x0.c75259f0a77a38p-15, -0x0.a000f3c88f2cf0p-22, -0x0.f9141f0f2a29b8p-32, 0x0.9c9bac58c1d0d0p-35, -0x0.db0fa5fce19438p-42, 0x0.d8fc2793714810p-50, // x in subrange 2:9 (2.28125..2.3125)
 0x0.8d8ec5d9ade0b0p-1, -0x0.a2cbbe6a7c6108p-8, 0x0.bfc997391b9898p-15, -0x0.a137c9a54fa8b8p-22, -0x0.83d4cf2a7a08d0p-33, 0x0.88a5b781330768p-35, -0x0.ce9a7a73c44cb8p-42, 0x0.ed4cc650554198p-50, // x in subrange 2:10 (2.3125..2.34375)
 0x0.8b0f6b27736120p-1, -0x0.9cebaf33aa0938p-8, 0x0.b83a761dfcd180p-15, -0x0.a118c05f3b82a8p-22, 0x0.ba179abba15688p-33, 0x0.ebcd37f5435760p-36, -0x0.c1351d822f7d20p-42, 0x0.fb6b5a4e486190p-50, // x in subrange 2:11 (2.34375..2.375)
 0x0.88a717db0f4838p-1, -0x0.9748000e1b4740p-8, 0x0.b0b3e0d73548e8p-15, -0x0.9fd2b1ddb15438p-22, 0x0.e55f7c5a4e99a8p-32, 0x0.c8e1e2a1a63048p-36, -0x0.b3320973751cf0p-42, 0x0.81fa78ee028148p-49, // x in subrange 2:12 (2.375..2.40625)
 0x0.8654db43f12918p-1, -0x0.91e038118962b8p-8, 0x0.a942a2852cd130p-15, -0x0.9d9141f49d3340p-22, 0x0.ac5a1acb988f08p-31, 0x0.a89ff7e2302170p-36, -0x0.a4dafd7660ee68p-42, 0x0.83c57cc347bbf8p-49, // x in subrange 2:13 (2.40625..2.4375)
 0x0.8417c757278650p-1, -0x0.8cb37ff68cfac8p-8, 0x0.a1f18e75059670p-15, -0x0.9a7cc20d4a7458p-22, 0x0.dc5bbc738736e8p-31, 0x0.8b1101520230c0p-36, -0x0.9670dbe5fb4518p-42, 0x0.8367b57ea46588p-49, // x in subrange 2:14 (2.4375..2.46875)
 0x0.81eef20a34c608p-1, -0x0.87c0b134c594b0p-8, 0x0.9ac9a85562a5b8p-15, -0x0.96ba250e1d4ca8p-22, 0x0.81c646c0fe5018p-30, 0x0.e06663ad3ec190p-37, -0x0.882bba67749668p-42, 0x0.8130c0335d8ba8p-49, // x in subrange 2:15 (2.46875..2.5)
 0x0.ffb2ece7e1dab8p-2, -0x0.830663de017920p-8, 0x0.93d24ca533b870p-15, -0x0.926b016f6eec20p-22, 0x0.91612c98bcd850p-30, 0x0.aff60e1a95f1c8p-37, -0x0.f47639200407b8p-43, 0x0.fadaed8597acb0p-50, // x in subrange 2:16 (2.5..2.53125)
 0x0.fbaceb7108b058p-2, -0x0.fd05f66e3acdf0p-9, 0x0.8d1158beac6968p-15, -0x0.8dad9f7485be98p-22, 0x0.9d670130ec5268p-30, 0x0.84a9b8a2e72740p-37, -0x0.d98ca398172f30p-43, 0x0.f0cd9c79ddfd40p-50, // x in subrange 2:17 (2.53125..2.5625)
 0x0.f7ca2f8af6ce50p-2, -0x0.f4696227c37910p-9, 0x0.868b51f8965df0p-15, -0x0.889d1191803a10p-22, 0x0.a63c9aa3cb57c8p-30, 0x0.bc99a5aa7afad0p-38, -0x0.bfd9deeb92a0e0p-43, 0x0.e4c1e8e71b0a70p-50, // x in subrange 2:18 (2.5625..2.59375)
 0x0.f40917c5ac4e68p-2, -0x0.ec333ffde8bbb0p-9, 0x0.80438b6f32b410p-15, -0x0.8351552054b490p-22, 0x0.ac4246723f7b48p-30, 0x0.f28141dcbf8078p-39, -0x0.a78ec0c8a4a7e8p-43, 0x0.d73551d7e06a68p-50, // x in subrange 2:19 (2.59375..2.625)
 0x0.f068123b9841d8p-2, -0x0.e45f98742a80d0p-9, 0x0.f47894371f8000p-16, -0x0.fbbef34c4d6890p-23, 0x0.afd311f47cd898p-30, 0x0.fae9e03f7f9328p-40, -0x0.90cf076a82e678p-43, 0x0.c89998d4faeba0p-50, // x in subrange 2:20 (2.625..2.65625)
 0x0.ece59d238d06b0p-2, -0x0.dcea574aa580f0p-9, 0x0.e8edcde8b05dc8p-16, -0x0.f0b39a1b3ac528p-23, 0x0.b14443dc061498p-30, 0x0.c6e178df9abaa8p-42, -0x0.f765548b083760p-44, 0x0.b954434da2a088p-50, // x in subrange 2:21 (2.65625..2.6875)
 0x0.e9804727a879e0p-2, -0x0.d5cf593b7fef50p-9, 0x0.dde7ddcb09cdf8p-16, -0x0.e5a016c2734aa8p-23, 0x0.b0e501dbffdbb8p-30, -0x0.f22495ebfc6008p-41, -0x0.d08e675b9c2ba0p-44, 0x0.a9be7292c0e5f8p-50, // x in subrange 2:22 (2.6875..2.71875)
 0x0.e636af892d3d70p-2, -0x0.cf0a77cb111968p-9, 0x0.d36680f9d09cc0p-16, -0x0.da9f2171456508p-23, 0x0.aefe1d6ab2ef70p-30, -0x0.8401df4922bd78p-39, -0x0.ad223554234c58p-44, 0x0.9a25063e0809e0p-50, // x in subrange 2:23 (2.71875..2.75)
 0x0.e3078618b7ced8p-2, -0x0.c897935023a9d0p-9, 0x0.c9684e706616f8p-16, -0x0.cfc71868c3c470p-23, 0x0.abd2028dfc4470p-30, -0x0.bed52e5a0a60e0p-39, -0x0.8d1a2af2dd51b0p-44, 0x0.8ac8fcd7e2cc90p-50, // x in subrange 2:24 (2.75..2.78125)
 0x0.dff18b09a2cc30p-2, -0x0.c2729b5a7f95a8p-9, 0x0.bfeae8dbae8b00p-16, -0x0.c52a66173bbf50p-23, 0x0.a79cc3bf55fe20p-30, -0x0.ee454b58237628p-39, -0x0.e0c57a943634e0p-45, 0x0.f7c00dbc7ad920p-51, // x in subrange 2:25 (2.78125..2.8125)
 0x0.dcf38ea6d4b7d8p-2, -0x0.bc97959df8a950p-9, 0x0.b6eb2baa33ac28p-16, -0x0.bad7e5ac8b7d18p-23, 0x0.a2943e2627aca0p-30, -0x0.89c58776d78610p-38, -0x0.adbb9eeb52d5e0p-45, 0x0.db2a81c521e310p-51, // x in subrange 2:26 (2.8125..2.84375)
 0x0.da0c70ee998818p-2, -0x0.b702a387ae4de0p-9, 0x0.ae65537586ba40p-16, -0x0.b0db44c64093b8p-23, 0x0.9ce851ab6845f8p-30, -0x0.97e9338db09d30p-38, -0x0.80c9d80069b638p-45, 0x0.c0141480caebe8p-51, // x in subrange 2:27 (2.84375..2.875)
 0x0.d73b211a959d88p-2, -0x0.b1b006a21436f0p-9, 0x0.a65521eeae73b8p-16, -0x0.a73d6117b4dfc8p-23, 0x0.96c328bbd91e78p-30, -0x0.a21bcc7b540a18p-38, -0x0.b32d3421425ea0p-46, 0x0.a6adddc0b72420p-51, // x in subrange 2:28 (2.875..2.90625)
 0x0.d47e9d18503ea8p-2, -0x0.ac9c23eadc25d0p-9, 0x0.9eb5fd83358db8p-16, -0x0.9e04a132355488p-23, 0x0.90498bea2253c0p-30, -0x0.a8e29dd7f62848p-38, -0x0.defd7f72e466f8p-47, 0x0.8f193712da7ec8p-51, // x in subrange 2:29 (2.90625..2.9375)
 0x0.d1d5f0f64ae058p-2, -0x0.a7c3863c06c370p-9, 0x0.97830cf95c7b48p-16, -0x0.953547cb1f35f8p-23, 0x0.899b3e042b88d0p-30, -0x0.acb96c70da40b0p-38, -0x0.d6df31141d7de8p-48, 0x0.f2d35579fcc348p-52, // x in subrange 2:30 (2.9375..2.96875)
 0x0.cf403649197a00p-2, -0x0.a322dfe7526a00p-9, 0x0.90b74f484e09f0p-16, -0x0.8cd1c1118534d0p-23, 0x0.82d35d93edf240p-30, -0x0.ae120ef295df30p-38, -0x0.a03ecee87c7030p-51, 0x0.cb4db91c2dd0f8p-52, // x in subrange 2:31 (2.96875..3)
 0x0.ccbc938b77aee0p-2, -0x0.9eb70ba105f6c0p-9, 0x0.8a4daff54d4530p-16, -0x0.84dae9d2413fd8p-23, 0x0.f8119251c52c70p-31, -0x0.ad544513c2d350p-38, 0x0.8de8d4c705ca58p-48, 0x0.a79cc476e05b20p-52, // x in subrange 2:32 (3..3.03125)
 0x0.ca4a3b7be73a00p-2, -0x0.9a7d0cd4c45c68p-9, 0x0.84411840efb288p-16, -0x0.faa0a0a0d93d38p-24, 0x0.ea9d085385ab48p-31, -0x0.aaddc393691c20p-38, 0x0.89226ee18c0268p-47, 0x0.87ab063efa3b88p-52, // x in subrange 2:33 (3.03125..3.0625)
 0x0.c7e86c79fe0ea0p-2, -0x0.96720f7cba5d98p-9, 0x0.fd18fadfc638c0p-17, -0x0.ec60ddb285e830p-24, 0x0.dd6834995ad8a8p-31, -0x0.a7026bdee1de28p-38, 0x0.be22b13e33d538p-47, 0x0.d6ab64b3230718p-53, // x in subrange 2:34 (3.0625..3.09375)
 0x0.c5966fe52e0b98p-2, -0x0.929367911ef9c8p-9, 0x0.f255d8f380f150p-17, -0x0.def1c06b8bb9f0p-24, 0x0.d08c0058dd5528p-31, -0x0.a20ca6d3ec8348p-38, 0x0.e78023f70a1410p-47, 0x0.a4df3ae15bf940p-53, // x in subrange 2:35 (3.09375..3.125)
 0x0.c353997e7cddf0p-2, -0x0.8ede9023b2eda8p-9, 0x0.e82f26cc90e438p-17, -0x0.d24d1c64e42b48p-24, 0x0.c41bdf87264a30p-31, -0x0.9c3ddacba15390p-38, 0x0.835815c5ed5608p-46, 0x0.f30fb2ef3793e0p-54, // x in subrange 2:36 (3.125..3.15625)
 0x0.c11f46ce5872b8p-2, -0x0.8b512a38b47918p-9, 0x0.de9b913cae3350p-17, -0x0.c66bb50cddf398p-24, 0x0.b8267fc0ac3e20p-31, -0x0.95cef5e156f820p-38, 0x0.8e87e5420956d8p-46, 0x0.a861dd562a8d38p-54, // x in subrange 2:37 (3.15625..3.1875)
 0x0.bef8de8f72c5a0p-2, -0x0.87e8fb6ca0cda0p-9, 0x0.d59220e43624d8p-17, -0x0.bb4584e0a2bce8p-24, 0x0.acb66bcdfbc9c0p-31, -0x0.8ef10636051c20p-38, 0x0.95f0e364c40b10p-46, 0x0.d17ec7015fe398p-55, // x in subrange 2:38 (3.1875..3.21875)
 0x0.bcdfd01f567698p-2, -0x0.84a3ec7420e7d8p-9, 0x0.cd0a4223b608d0p-17, -0x0.b0d1facea6aba8p-24, 0x0.a1d2a2e5549018p-31, -0x0.87cddabedb50e0p-38, 0x0.9a26d31c7155f8p-46, 0x0.ccb3738d104820p-56, // x in subrange 2:39 (3.21875..3.25)
 0x0.bad392f533d680p-2, -0x0.81800781a76b80p-9, 0x0.c4fbca63fc3d00p-17, -0x0.a7082e8a87e288p-24, 0x0.977f232e209680p-31, -0x0.8088a7f76d42f8p-38, 0x0.9bafb0b4a53b18p-46, 0x0.d5df483b9074b0p-59, // x in subrange 2:40 (3.25..3.28125)
 0x0.b8d3a61f3b7668p-2, -0x0.fcf6ed3524e5d8p-10, 0x0.bd5efb1c8f9c70p-17, -0x0.9ddf0c9fd4c1e0p-24, 0x0.8dbd6760b96570p-31, -0x0.f27d592199ad18p-39, 0x0.9b03d6b5c05100p-46, -0x0.ed84f0b84cc7f8p-57, // x in subrange 2:41 (3.28125..3.3125)
 0x0.b6df8fc6b71e68p-2, -0x0.f72903c8301ca0p-10, 0x0.b62c82f6c74e68p-17, -0x0.954d7b113eac88p-24, 0x0.848cd7a3cac528p-31, -0x0.e40fa5d7f61398p-39, 0x0.988e5fba0c7d28p-46, -0x0.eb7dca0d794540p-56, // x in subrange 2:42 (3.3125..3.34375)
 0x0.b4f6dcbaf3ceb0p-2, -0x0.f1931bddbce548p-10, 0x0.af5d7d622eb1a8p-17, -0x0.8d4a774dceaa60p-24, 0x0.f7d65c03ca1ff0p-32, -0x0.d5ee99a9e2ac90p-39, 0x0.94adb7f4874560p-46, -0x0.a37e7d29a11188p-55, // x in subrange 2:43 (3.34375..3.375)
 0x0.b3192002f67510p-2, -0x0.ec32340dc1ba68p-10, 0x0.a8eb70e5961180p-17, -0x0.85cd2e3e91bf50p-24, 0x0.e7a99dfd4b6428p-32, -0x0.c8384f1544dde8p-39, 0x0.8fb4528048fc98p-46, -0x0.c6479161e0de78p-55, // x in subrange 2:44 (3.375..3.40625)
 0x0.b145f275e0c150p-2, -0x0.e7037d184d3eb0p-10, 0x0.a2d04c6f4a9bf8p-17, -0x0.fd9a1e4b420be0p-25, 0x0.d88a2de90efcf0p-32, -0x0.bb03ad4dc01b98p-39, 0x0.89e977f52ab130p-46, -0x0.dfa2d638df4390p-55, // x in subrange 2:45 (3.40625..3.4375)
 0x0.af7cf259db6858p-2, -0x0.e20456afb1b558p-10, 0x0.9d0663de880a98p-17, -0x0.f083b3f81b81e8p-25, 0x0.ca6d39f878ad98p-32, -0x0.ae6169ddb06140p-39, 0x0.838a25236b30e0p-46, -0x0.f0f86e6a4a9b68p-55, // x in subrange 2:46 (3.4375..3.46875)
 0x0.adbdc3094eb118p-2, -0x0.dd324c60d61bb0p-10, 0x0.97886bf85e88a8p-17, -0x0.e44753df4dba90p-25, 0x0.bd46d85b688730p-32, -0x0.a25cf4f42e9a18p-39, 0x0.f993e466a16020p-47, -0x0.fb8f3531e69608p-55, // x in subrange 2:47 (3.46875..3.5)
 0x0.ac080c9e28d238p-2, -0x0.d88b129da0ab68p-10, 0x0.925175f30b23a0p-17, -0x0.d8d5f92884cf38p-25, 0x0.b10a6825e0d180p-32, -0x0.96fd4fe6a527a0p-39, 0x0.eba7f75fb623f0p-47, -0x0.80466f679216f8p-54, // x in subrange 2:48 (3.5..3.53125)
 0x0.aa5b7ba2eb06b8p-2, -0x0.d40c83ec3171a0p-10, 0x0.8d5ceabc268810p-17, -0x0.ce216c9d3a0bc0p-25, 0x0.a5aae24d4e7ea0p-32, -0x0.8c45cdf93a6070p-39, 0x0.dd97906e432930p-47, -0x0.807b62904f2480p-54, // x in subrange 2:49 (3.53125..3.5625)
 0x0.a8b7c0c931e528p-2, -0x0.cfb49e3c98d278p-10, 0x0.88a686181678b8p-17, -0x0.c41c48e2a75910p-25, 0x0.9b1b1c6b664608p-32, -0x0.8236bff2783858p-39, 0x0.cf9c4d485fe5e0p-47, -0x0.fdb33a2c999c58p-55, // x in subrange 2:50 (3.5625..3.59375)
 0x0.a71c90a56b11b0p-2, -0x0.cb818065d83138p-10, 0x0.842a51b3d81580p-17, -0x0.bab9faee7ec760p-25, 0x0.914dfee6980a30p-32, -0x0.f19c16ad60bc18p-40, 0x0.c1e40305b52210p-47, -0x0.f78b3e9a3caaa8p-55, // x in subrange 2:51 (3.59375..3.625)
 0x0.a589a36f6982c0p-2, -0x0.c77167ca459308p-10, 0x0.ffc9407afcffc0p-18, -0x0.b1eebf738e6068p-25, 0x0.8836b00c2b6eb8p-32, -0x0.e00f5cd2cefd20p-40, 0x0.b4924afa0a37d8p-47, -0x0.ef2c7e5fc521a0p-55, // x in subrange 2:52 (3.625..3.65625)
 0x0.a3feb4c789f618p-2, -0x0.c382ae22d92ff8p-10, 0x0.f7a41127368d78p-18, -0x0.a9af9deb74c350p-25, 0x0.ff916b1f9b5cd0p-33, -0x0.cfbc6482b38a08p-40, 0x0.a7c1f26472e930p-47, -0x0.e52b7a1a95a9a8p-55, // x in subrange 2:53 (3.65625..3.6875)
 0x0.a27b83801a9d00p-2, -0x0.bfb3c77078fe80p-10, 0x0.efdec2305667e0p-18, -0x0.a1f261cc255900p-25, 0x0.eff01b923918a0p-33, -0x0.c09618b2594738p-40, 0x0.9b864b1e005ce8p-47, -0x0.da05c78bcdffe0p-55, // x in subrange 2:54 (3.6875..3.71875)
 0x0.a0ffd16abb3bb0p-2, -0x0.bc034011fe2a30p-10, 0x0.e873766110d980p-18, -0x0.9aad9263586090p-25, 0x0.e17283d58300b8p-33, -0x0.b28de22c82afb0p-40, 0x0.8fec5c854d3770p-47, -0x0.ce24577b0c95c0p-55, // x in subrange 2:55 (3.71875..3.75)
 0x0.9f8b63296dc3a0p-2, -0x0.b86fbafd6f37c0p-10, 0x0.e15cbdf27efc40p-18, -0x0.93d869bf371b60p-25, 0x0.d402e4a1f93f80p-33, -0x0.a5943185a486f8p-40, 0x0.84fbf4c3dd0660p-47, -0x0.c1ddb2babc6f48p-55, // x in subrange 2:56 (3.75..3.78125)
 0x0.9e1e000312aca8p-2, -0x0.b4f7f01abbcfa8p-10, 0x0.da958e64d99588p-18, -0x0.8d6acafaa3e440p-25, 0x0.c78cbbcfc492e0p-33, -0x0.9998f0e5b53200p-40, 0x0.f571367721f5d8p-48, -0x0.b578232cd5f208p-55, // x in subrange 2:57 (3.78125..3.8125)
 0x0.9cb771bb0fd670p-2, -0x0.b19aaabe2999b8p-10, 0x0.d4193acedf9950p-18, -0x0.875d3834621df0p-25, 0x0.bbfccb195fda50p-33, -0x0.8e8be07c961ec0p-40, 0x0.e244cae48a4fb8p-48, -0x0.a92bc06f8f10b0p-55, // x in subrange 2:58 (3.8125..3.84375)
 0x0.9b57846be46e90p-2, -0x0.ae56c840916840p-10, 0x0.cde36ca67dcee8p-18, -0x0.81a8c86b0a9568p-25, 0x0.b1411863f63990p-33, -0x0.845ce05125d860p-40, 0x0.d06d606a0e1480p-48, -0x0.9d245a4615a470p-55, // x in subrange 2:59 (3.84375..3.875)
 0x0.99fe06647021a0p-2, -0x0.ab2b36b386a9a8p-10, 0x0.c7f01d02dd94a0p-18, -0x0.f88e3ad81e9058p-26, 0x0.a748e8e8f02630p-33, -0x0.f5f853dc885210p-41, 0x0.bfe17de07c0600p-48, -0x0.91833ce3fa2060p-55, // x in subrange 2:60 (3.875..3.90625)
 0x0.98aac807b7a5b0p-2, -0x0.a816f3af868140p-10, 0x0.c23b8e5613af30p-18, -0x0.ee64b3f3f336a8p-26, 0x0.9e04b86bd41570p-33, -0x0.e4b4f87e6d75b8p-41, 0x0.b09486c6c69488p-48, -0x0.8660ccfe8fe160p-55, // x in subrange 2:61 (3.90625..3.9375)
 0x0.975d9baef469b0p-2, -0x0.a5190b3a562100p-10, 0x0.bcc2469b2b4dd0p-18, -0x0.e4ca308ad1da00p-26, 0x0.95662d7b4e7728p-33, -0x0.d4d27770685168p-41, 0x0.a2779fd42a0a00p-48, -0x0.f79bf5e81462c0p-56, // x in subrange 2:62 (3.9375..3.96875)
 0x0.9616558dc0d760p-2, -0x0.a23096c3c76478p-10, 0x0.b78109f42c5988p-18, -0x0.dbb4c19a086d20p-26, 0x0.8d600b940ce760p-33, -0x0.c635116488ef50p-41, 0x0.957a6d2b339828p-48, -0x0.e3ab1af6e249a8p-56, // x in subrange 2:63 (3.96875..4)
 0x0.9436207ec3b2f0p-2, -0x0.9dfa47b58bddf0p-9, 0x0.b001bc6333e608p-16, -0x0.cefa56ef485c30p-23, 0x0.825a3d1357dae0p-29, -0x0.b271bf2689a768p-36, 0x0.83edaf0a0a10c0p-42, -0x0.c82421a0cba9a8p-49, // x in subrange 3:0 (4..4.0625)
 0x0.91c904bc5f2088p-2, -0x0.98a00ad68ffc70p-9, 0x0.a6ac65b3838188p-16, -0x0.bf8437f709b4c0p-23, 0x0.eaa75ce5393f48p-30, -0x0.9ba368b44e17d0p-36, 0x0.dfb95dfa22a678p-43, -0x0.a7c9c7b7a22b10p-49, // x in subrange 3:1 (4.0625..4.125)
 0x0.8f70c05c37b158p-2, -0x0.938dabb7a05be0p-9, 0x0.9e0741094eaf00p-16, -0x0.b193e92b271b68p-23, 0x0.d3e37a2b7368a8p-30, -0x0.8847d7cba2bae0p-36, 0x0.be22e2b1560a88p-43, -0x0.8c3af7e407f690p-49, // x in subrange 3:2 (4.125..4.1875)
 0x0.8d2c3e8c27f218p-2, -0x0.8ebdeeb7a8bd20p-9, 0x0.96013398c02bb8p-16, -0x0.a4f8e77a172860p-23, 0x0.bfea84850bcdc8p-30, -0x0.ef9c6667c712e0p-37, 0x0.a216949d47a318p-43, -0x0.ea14b047771190p-50, // x in subrange 3:3 (4.1875..4.25)
 0x0.8afa7e6288e110p-2, -0x0.8a2c186c34af50p-9, 0x0.8e8b3c147805e8p-16, -0x0.9989e9677fb368p-23, 0x0.ae52fe0e6ce718p-30, -0x0.d3790e87e3e5b0p-37, 0x0.8aae13eab04478p-43, -0x0.c3668116c17b28p-50, // x in subrange 3:4 (4.25..4.3125)
 0x0.88da90fd350cf0p-2, -0x0.85d3de1c581500p-9, 0x0.87982359298098p-16, -0x0.8f23ad9a76efe0p-23, 0x0.9ec4d988f6c0f0p-30, -0x0.bb5a2916f3b838p-37, 0x0.ee41c6e545f4b8p-44, -0x0.a357fea8624908p-50, // x in subrange 3:5 (4.3125..4.375)
 0x0.86cb97d9f3de80p-2, -0x0.81b1588038f650p-9, 0x0.811c3a34adf500p-16, -0x0.85a7fbe89ddae8p-23, 0x0.90f68a6a761490p-30, -0x0.a69702842699a0p-37, 0x0.cd8850d5c75260p-44, -0x0.88e204cd077ff0p-50, // x in subrange 3:6 (4.375..4.4375)
 0x0.84ccc360000ff0p-2, -0x0.fb81f0cacd9a80p-10, 0x0.f61a4429190378p-17, -0x0.f9f9a3cbdb6600p-24, 0x0.84aa836b445750p-30, -0x0.94a451c825d6d0p-37, 0x0.b21121c378ea78p-44, -0x0.e62bcc7844e598p-51, // x in subrange 3:7 (4.4375..4.5)
 0x0.82dd5193ba1f78p-2, -0x0.f3fef9d0ff0ec8p-10, 0x0.eac33d74cadce8p-17, -0x0.ea17688df4a8e0p-24, 0x0.f35a3808c811b0p-31, -0x0.850f556379e8e8p-37, 0x0.9aee98564cffa0p-44, -0x0.c24591df585570p-51, // x in subrange 3:8 (4.5..4.5625)
 0x0.80fc8ceeb91468p-2, -0x0.ecd3d604ec81c0p-10, 0x0.e022dec3572858p-17, -0x0.db823df9bd4890p-24, 0x0.dfa5a36d4cd210p-31, -0x0.eef3167a8bf848p-38, 0x0.875d614105fa18p-44, -0x0.a4ad3cbe153a98p-51, // x in subrange 3:9 (4.5625..4.625)
 0x0.fe5396aeb5a098p-3, -0x0.e5fb0c66b6c398p-10, 0x0.d62a5c0db1db58p-17, -0x0.ce181d626ef7e0p-24, 0x0.cdedb152dcd2d8p-31, -0x0.d72a1258af00a0p-38, 0x0.ed7bbb7a73afd0p-45, -0x0.8c3903441f31e0p-51, // x in subrange 3:10 (4.625..4.6875)
 0x0.fac8da6773e4a8p-3, -0x0.df6f943c201dc0p-10, 0x0.cccc67779fd4b8p-17, -0x0.c1bb3e1ff07720p-24, 0x0.bdf3dea77d24b8p-31, -0x0.c242dc292f5aa8p-38, 0x0.d11c227763ccb8p-45, -0x0.efe6e50a9996f0p-52, // x in subrange 3:11 (4.6875..4.75)
 0x0.f757b9292300d8p-3, -0x0.d92cc9e0440598p-10, 0x0.c3fd024ee4ce18p-17, -0x0.b6517415bb57a8p-24, 0x0.af82d3abe45c08p-31, -0x0.afd2b867d7a020p-38, 0x0.b8c89301bf9070p-45, -0x0.ce28b91ee155f8p-52, // x in subrange 3:12 (4.75..4.8125)
 0x0.f3ff18ea38bcc0p-3, -0x0.d32e64eedfb838p-10, 0x0.bbb154f0a2b880p-17, -0x0.abc3a9dae449d8p-24, 0x0.a26cd6038b87e0p-31, -0x0.9f80d483a0f290p-38, 0x0.a3d51fbac18c48p-45, -0x0.b1f368c1f0b4a0p-52, // x in subrange 3:13 (4.8125..4.875)
 0x0.f0bdf01adab600p-3, -0x0.cd706f98d18d20p-10, 0x0.b3df8c696506e8p-17, -0x0.a1fd715a2f4090p-24, 0x0.968a8507599460p-31, -0x0.9102f17eec9310p-38, 0x0.91b5b8e26e03f0p-45, -0x0.9a41d52da1ea60p-52, // x in subrange 3:14 (4.875..4.9375)
 0x0.ed93446a311e90p-3, -0x0.c7ef3ef7e9a4e8p-10, 0x0.ac7ebcdc31bb60p-17, -0x0.98eca6bbd755b8p-24, 0x0.8bb9d21499ca38p-31, -0x0.841ab43299a008p-38, 0x0.81f7f1ae62efc8p-45, -0x0.864223e8f80d98p-52, // x in subrange 3:15 (4.9375..5)
 0x0.ea7e29a8a6f228p-3, -0x0.c2a76c3f08b860p-10, 0x0.a586c7ea205430p-17, -0x0.9081223a2a9178p-24, 0x0.81dd29220d4a98p-31, -0x0.f126f8f8b00930p-39, 0x0.e87beac8119158p-46, -0x0.ea978b19bd2360p-53, // x in subrange 3:16 (5..5.0625)
 0x0.e77dc0c3e2e530p-3, -0x0.bd95cea92720c8p-10, 0x0.9ef046784ee268p-17, -0x0.88ac762b393f68p-24, 0x0.f1b5803c6ebc20p-32, -0x0.dc81524f1efc78p-39, 0x0.d074f7339e2030p-46, -0x0.cdae5ea6cbd0e0p-53, // x in subrange 3:17 (5.0625..5.125)
 0x0.e49136d9b06ad0p-3, -0x0.b8b7760e765b58p-10, 0x0.98b4754f426960p-17, -0x0.8161b7123864d8p-24, 0x0.e1380af1f4c4a0p-32, -0x0.c9f8659f72f7f0p-39, 0x0.bb5b1c2e1e8468p-46, -0x0.b4ee3cdb744b70p-53, // x in subrange 3:18 (5.125..5.1875)
 0x0.e1b7c45f6b9a60p-3, -0x0.b409a60a959370p-10, 0x0.92cd242638ba90p-17, -0x0.f52a97f0b4a4f0p-25, 0x0.d21a4f892716c8p-32, -0x0.b94b1804929b40p-39, 0x0.a8c3f03eaafab8p-46, -0x0.9fa65eb78e80c8p-53, // x in subrange 3:19 (5.1875..5.25)
 0x0.def0ac5bd06db8p-3, -0x0.af89d1a1ef41a8p-10, 0x0.8d34a6bfd76b40p-17, -0x0.e8798b479963f8p-25, 0x0.c439633178aac8p-32, -0x0.aa4170c4bf2580p-39, 0x0.98567a197f1680p-46, -0x0.8d47228b1708d0p-53, // x in subrange 3:20 (5.25..5.3125)
 0x0.dc3b3bb1502558p-3, -0x0.ab359756eb6278p-10, 0x0.87e5c7cce4ff80p-17, -0x0.dc9d771136bb48p-25, 0x0.b7766bc2ec4490p-32, -0x0.9cab1ef58f3060p-39, 0x0.89c7f42c374888p-46, -0x0.fab683c50b5560p-54, // x in subrange 3:21 (5.3125..5.375)
 0x0.d996c877488288p-3, -0x0.a70abda1c932b0p-10, 0x0.82dbbd5616bc70p-17, -0x0.d1855b0c211970p-25, 0x0.abb61319cc00c8p-32, -0x0.905e4497fc4298p-39, 0x0.f9b2720f67eed8p-47, -0x0.df04f54868d000p-54, // x in subrange 3:22 (5.375..5.4375)
 0x0.d702b160a983c8p-3, -0x0.a3072fbfc16b38p-10, 0x0.fc243cf01d93a0p-18, -0x0.c721d35d917010p-25, 0x0.a0e0105587b258p-32, -0x0.85367919411808p-39, 0x0.e2a968e9849c90p-47, -0x0.c6dabbb4fe0a48p-54, // x in subrange 3:23 (5.4375..5.5)
 0x0.d47e5d2ec0ad08p-3, -0x0.9f28facf970e18p-10, 0x0.f309b489c68a28p-18, -0x0.bd64eaf8ef9e78p-25, 0x0.96dec319d54138p-32, -0x0.f627f055e6d5a0p-40, 0x0.ce197964a30dc8p-47, -0x0.b1b4098cc89198p-54, // x in subrange 3:24 (5.5..5.5625)
 0x0.d2093a2f05a700p-3, -0x0.9b6e4b330617a8p-10, 0x0.ea605f4a9bbd78p-18, -0x0.b441f3d866c850p-25, 0x0.8d9eddb58f4fa8p-32, -0x0.e3b5e8877c0b20p-40, 0x0.bbb47b29a838f0p-47, -0x0.9f22f2f96d0e98p-54, // x in subrange 3:25 (5.5625..5.625)
 0x0.cfa2bdc2e40678p-3, -0x0.97d56a2d974ab8p-10, 0x0.e2214c327d22c0p-18, -0x0.abad642ceed518p-25, 0x0.850f1bad2efba0p-32, -0x0.d2e60be70e4338p-40, 0x0.ab37485e332d28p-47, -0x0.8ecb5621a27c78p-54, // x in subrange 3:26 (5.625..5.6875)
 0x0.cd4a63f09a0380p-3, -0x0.945cbbba4f45f8p-10, 0x0.da460e786a4d38p-18, -0x0.a39cb7d064d620p-25, 0x0.fa400540d4b3b0p-33, -0x0.c38d654bb954b0p-40, 0x0.9c67fb17982828p-47, -0x0.805f9c44bec080p-54, // x in subrange 3:27 (5.6875..5.75)
 0x0.caffaefc5c6d58p-3, -0x0.9102bc927be738p-10, 0x0.d2c8b1eb54d780p-18, -0x0.9c065561b395d8p-25, 0x0.eb8757c58a6640p-33, -0x0.b5860d16caae50p-40, 0x0.8f147bffd96918p-47, -0x0.e73c46c948b108p-55, // x in subrange 3:28 (5.75..5.8125)
 0x0.c8c2270905b148p-3, -0x0.8dc60060934650p-10, 0x0.cba3b0822eea90p-18, -0x0.94e1768b1570a0p-25, 0x0.dddb2ad6cd9f90p-33, -0x0.a8ae7c82cb5758p-40, 0x0.831151e07503d8p-47, -0x0.d09e56b7494650p-55, // x in subrange 3:29 (5.8125..5.875)
 0x0.c69159bfa8c660p-3, -0x0.8aa5301aafc2c0p-10, 0x0.c4d1e8f7d7e358p-18, -0x0.8e261306382d18p-25, 0x0.d124f1fb5bace8p-33, -0x0.9ce8faf778b670p-40, 0x0.f0714ab0270490p-48, -0x0.bc8653a573c930p-55, // x in subrange 3:30 (5.875..5.9375)
 0x0.c46cd9fd7193e8p-3, -0x0.879f0880b87c78p-10, 0x0.be4e965436b800p-18, -0x0.87ccce025cb7e0p-25, 0x0.c550513a3ffd00p-33, -0x0.921b20fac9ac60p-40, 0x0.dcd2dd7c2ae920p-48, -0x0.aaa2de4a006f88p-55, // x in subrange 3:31 (5.9375..6)
 0x0.c2543f874b40f8p-3, -0x0.84b258bab82468p-10, 0x0.b8154847ccbb80p-18, -0x0.81cee59e19e1a0p-25, 0x0.ba4adf0e19dac0p-33, -0x0.882d6d2c87f700p-40, 0x0.cb0d8ca66cbf98p-48, -0x0.9aae168d1dd1e0p-55, // x in subrange 3:32 (6..6.0625)
 0x0.c04726c2d206b8p-3, -0x0.81de011447eda8p-10, 0x0.b221dc4271a8f0p-18, -0x0.f84c4863713f08p-26, 0x0.b003ee190f9ce8p-33, -0x0.fe15d0c59c7880p-41, 0x0.baeea0feda2500p-48, -0x0.8c6bcb34b058e0p-55, // x in subrange 3:33 (6.0625..6.125)
 0x0.be45307421d680p-3, -0x0.fe41e3a4975570p-11, 0x0.ac707730d3c618p-18, -0x0.ed99a66137ac60p-26, 0x0.a66c5d8386f9b0p-33, -0x0.ed41ad08009358p-41, 0x0.ac498240a753b8p-48, -0x0.ff4ff63663a0b8p-56, // x in subrange 3:34 (6.125..6.1875)
 0x0.bc4e01801d9398p-3, -0x0.f8f45441112818p-11, 0x0.a6fd7fced851b8p-18, -0x0.e37b5ee0437168p-26, 0x0.9d766f1b249748p-33, -0x0.ddbce44c918738p-41, 0x0.9ef6e3ce2e0ef8p-48, -0x0.e86b30226a24d0p-56, // x in subrange 3:35 (6.1875..6.25)
 0x0.ba6142b2d3f1b0p-3, -0x0.f3d16e29c6ae90p-11, 0x0.a1c5997f21aa68p-18, -0x0.d9e7bd52596e00p-26, 0x0.9515a26b741430p-33, -0x0.cf6962a658c3a0p-41, 0x0.92d41114406950p-48, -0x0.d3dafddee7ebe0p-56, // x in subrange 3:36 (6.25..6.3125)
 0x0.b87ea089af5e90p-3, -0x0.eed7658c9a48f8p-11, 0x0.9cc59f99df28e0p-18, -0x0.d0d5cc1e785158p-26, 0x0.8d3e94276191b0p-33, -0x0.c22c2427a78c88p-41, 0x0.87c25454340f20p-48, -0x0.c15b35f76da750p-56, // x in subrange 3:37 (6.3125..6.375)
 0x0.b6a5cb0125d290p-3, -0x0.ea0486eb371ad8p-11, 0x0.97faa126a9bc98p-18, -0x0.c83d43b9ba9460p-26, 0x0.85e6e153835d68p-33, -0x0.b5ecdb47782c70p-41, 0x0.fb4ce714f8da60p-49, -0x0.b0b0598df00340p-56, // x in subrange 3:38 (6.375..6.4375)
 0x0.b4d67565a41888p-3, -0x0.e557358d6a37a8p-11, 0x0.9361dcf6994da8p-18, -0x0.c0167b72cf2120p-26, 0x0.fe0a1b6bfc2ed8p-34, -0x0.aa95a2ac697780p-41, 0x0.e8d07fd8e1f7a0p-49, -0x0.a1a65c77ff0060p-56, // x in subrange 3:39 (6.4375..6.5)
 0x0.b31056277620a8p-3, -0x0.e0cdea114aa098p-11, 0x0.8ef8be14f98da0p-18, -0x0.b85a5bbf122ce8p-26, 0x0.f120da44921d48p-34, -0x0.a012b8c2fdd720p-41, 0x0.d7e46a2bb16b68p-49, -0x0.940f9d9e0deb98p-56, // x in subrange 3:40 (6.5..6.5625)
 0x0.b15326b1735ed0p-3, -0x0.dc6731169ddcf0p-11, 0x0.8abcd88617c900p-18, -0x0.b10251de7224b0p-26, 0x0.e5021e8bb0b068p-34, -0x0.965243c44debd0p-41, 0x0.c8624afcc8bb68p-49, -0x0.87c4076ae7d3e0p-56, // x in subrange 3:41 (6.5625..6.625)
 0x0.af9ea3423b16e8p-3, -0x0.d821aa032751e0p-11, 0x0.86abe64c9406d0p-18, -0x0.aa0844b0958ef0p-26, 0x0.d99f5b4e5d0ee8p-34, -0x0.8d441d071a2cf8p-41, 0x0.ba27e46da158a0p-49, -0x0.f940a33f6c9aa8p-57, // x in subrange 3:42 (6.625..6.6875)
 0x0.adf28ac7d0e370p-3, -0x0.d3fc05ddc9cd48p-11, 0x0.82c3c4ae72fe10p-18, -0x0.a3668a9a478c48p-26, 0x0.ceeb3726e4c8c0p-34, -0x0.84d9a2a1194a20p-41, 0x0.ad169883d26610p-49, -0x0.e50abe2fc54ab0p-57, // x in subrange 3:43 (6.6875..6.75)
 0x0.ac4e9ebd6dbf30p-3, -0x0.cff5063e95d380p-11, 0x0.fe04e367d04538p-19, -0x0.9d17e05e24aed8p-26, 0x0.c4d96f7f5a3930p-34, -0x0.fa0b1d06486d20p-42, 0x0.a112fc45d49420p-49, -0x0.d2af66025cf278p-57, // x in subrange 3:44 (6.75..6.8125)
 0x0.aab2a30b5d7788p-3, -0x0.cc0b7c520ceac0p-11, 0x0.f6cc13b4e551e0p-19, -0x0.971760cef044d8p-26, 0x0.bb5ebed518c0e0p-34, -0x0.eb77a4b379d650p-42, 0x0.960478e7944ad0p-49, -0x0.c1fdf3aa144fa0p-57, // x in subrange 3:45 (6.8125..6.875)
 0x0.a91e5de8c3b2d0p-3, -0x0.c83e47ee0af900p-11, 0x0.efd98beef18940p-19, -0x0.91607d44f64750p-26, 0x0.b270c5a43eb2a8p-34, -0x0.dde2ef2ad4d850p-42, 0x0.8bd4f90a3320a8p-49, -0x0.b2cb4605588680p-57, // x in subrange 3:46 (6.875..6.9375)
 0x0.a79197bf26aec0p-3, -0x0.c48c56b6eb67b8p-11, 0x0.e929f28c182588p-19, -0x0.8beef6c2782598p-26, 0x0.aa05f5ad638ae0p-34, -0x0.d1390628b314a8p-42, 0x0.8270a060a03d98p-49, -0x0.a4f1117b435cf8p-57, // x in subrange 3:47 (6.9375..7)
 0x0.a60c1b0fa08dc8p-3, -0x0.c0f4a353a09a00p-11, 0x0.e2ba1f37e66470p-19, -0x0.86bed7b5686aa0p-26, 0x0.a2157f51953540p-34, -0x0.c567b7f2988820p-42, 0x0.f38b1897c338a8p-50, -0x0.984d47a1342030p-57, // x in subrange 3:48 (7..7.0625)
 0x0.a48db4599a7f70p-3, -0x0.bd7634af91ca38p-11, 0x0.dc871784f1b798p-19, -0x0.81cc6e46b65ad0p-26, 0x0.9a9740c9140f50p-34, -0x0.ba5e6a975fcaa8p-42, 0x0.e3873870c8a880p-50, -0x0.8cc19359bfb568p-57, // x in subrange 3:49 (7.0625..7.125)
 0x0.a3163202f74c60p-3, -0x0.ba101d492df490p-11, 0x0.d68e0bdfb3d8e0p-19, -0x0.fa288e52522cf8p-27, 0x0.9383b7008e3d98p-34, -0x0.b00df414519670p-42, 0x0.d4b88166af3600p-50, -0x0.8232e66ff080f8p-57, // x in subrange 3:50 (7.125..7.1875)
 0x0.a1a5644194d970p-3, -0x0.b6c17a8c3a66a8p-11, 0x0.d0cc54bcf64a88p-19, -0x0.f12651b6a3dce0p-27, 0x0.8cd3efeeeac610p-34, -0x0.a66876c8c456d0p-42, 0x0.c704a0aafd9ac8p-50, -0x0.f1122c55396208p-58, // x in subrange 3:51 (7.1875..7.25)
 0x0.a03b1d060e1140p-3, -0x0.b3897436f92430p-11, 0x0.cb3f6ffeac2b58p-19, -0x0.e88c1ea2ed4c38p-27, 0x0.86817e3b2fcd00p-34, -0x0.9d6141b58fea90p-42, 0x0.ba53c3829451d0p-50, -0x0.df5d096fa7ace8p-58, // x in subrange 3:52 (7.25..7.3125)
 0x0.9ed72fe7a85850p-3, -0x0.b0673bc956d5c0p-11, 0x0.c5e4fe8a977830p-19, -0x0.e0544ffb0902d8p-27, 0x0.80866e0ed3c268p-34, -0x0.94ecb416858c28p-42, 0x0.ae90541ad0d140p-50, -0x0.cf1fab47a2be28p-58, // x in subrange 3:53 (7.3125..7.375)
 0x0.9d797211593e40p-3, -0x0.ad5a0bfd619b38p-11, 0x0.c0bac20e879d68p-19, -0x0.d8799c5852fd70p-27, 0x0.f5ba75e9e1fff8p-35, -0x0.8d0023f2a1c028p-42, 0x0.a3a6be1874a598p-50, -0x0.c03757a90fb6a0p-58, // x in subrange 3:54 (7.375..7.4375)
 0x0.9c21ba2fd28ad0p-3, -0x0.aa6128485a1708p-11, 0x0.bbbe9aee642c08p-19, -0x0.d0f70f5e3d14a8p-27, 0x0.eb018d54e83ff8p-35, -0x0.8591c74c31e6e0p-42, 0x0.998539e896e188p-50, -0x0.b284df7a54b3f8p-58, // x in subrange 3:55 (7.4375..7.5)
 0x0.9acfe0608415b8p-3, -0x0.a77bdc63be8368p-11, 0x0.b6ee865890fed0p-19, -0x0.c9c8039aff7b00p-27, 0x0.e0d8a18d137c88p-35, -0x0.fd313f49eaab20p-43, 0x0.901b9dfd81c388p-50, -0x0.a5ec395c1ff970p-58, // x in subrange 3:56 (7.5..7.5625)
 0x0.9983be21840978p-3, -0x0.a4a97bddbcc8c8p-11, 0x0.b2489c7d8a48b8p-19, -0x0.c2e81ce7946ed8p-27, 0x0.d736de4ab05030p-35, -0x0.f018cf273634b0p-43, 0x0.875b353e0f6670p-50, -0x0.9a54289d0becf8p-58, // x in subrange 3:57 (7.5625..7.625)
 0x0.983d2e424f4cb0p-3, -0x0.a1e961b0847df0p-11, 0x0.adcb0ee7dff648p-19, -0x0.bc53433b798388p-27, 0x0.ce140e030475a0p-35, -0x0.e3cb04602ffb08p-43, 0x0.fe6d340d4919f0p-51, -0x0.8fa5eee1daddc0p-58, // x in subrange 3:58 (7.625..7.6875)
 0x0.96fc0cd554cfe8p-3, -0x0.9f3aefdffc96d8p-11, 0x0.a97426f1f96868p-19, -0x0.b6059de9d78980p-27, 0x0.c5688d562bb830p-35, -0x0.d839d846b36ff8p-43, 0x0.ef432a5fe922e8p-51, -0x0.85cd071de0d500p-58, // x in subrange 3:59 (7.6875..7.75)
 0x0.95c037223f6c38p-3, -0x0.9c9d8f1d6a6bc0p-11, 0x0.a542445745a640p-19, -0x0.affb8f3eb88958p-27, 0x0.bd2d3f98d7ea08p-35, -0x0.cd585c59f6ca28p-43, 0x0.e12201439ccb18p-51, -0x0.f96dd15233a530p-59, // x in subrange 3:60 (7.75..7.8125)
 0x0.94898b98f2db38p-3, -0x0.9a10ae70a0c4c0p-11, 0x0.a133dbdeb16b68p-19, -0x0.aa31b073dd4d30p-27, 0x0.b55b845e545278p-35, -0x0.c31aa1ede98568p-43, 0x0.d3f55a0f8625e8p-51, -0x0.e8a5a2d7a8bf08p-59, // x in subrange 3:61 (7.8125..7.875)
 0x0.9357e9c5311a50p-3, -0x0.9793c2e655ce00p-11, 0x0.9d47761c6c9110p-19, -0x0.a4a4cdf594ee90p-27, 0x0.aded2dea1decc8p-35, -0x0.b975a427cb80d0p-43, 0x0.c7aa9495c50770p-51, -0x0.d9232c77ee8d18p-59, // x in subrange 3:62 (7.875..7.9375)
 0x0.922b3242de4668p-3, -0x0.95264743465bd8p-11, 0x0.997bae4933c5b0p-19, -0x0.9f51e3f0b3b7a8p-27, 0x0.a6dc7872fb9430p-35, -0x0.b05f341163dad8p-43, 0x0.bc30a4fec8a8d8p-51, -0x0.cacaf14d799f58p-59, // x in subrange 3:63 (7.9375..8)
 0x0.9071142cb864c0p-3, -0x0.919de97e7d0ec0p-10, 0x0.9404493068fc40p-17, -0x0.97bc0b62221f40p-24, 0x0.9ce7491f05a838p-31, -0x0.a3b46ca74641a8p-38, 0x0.ac5ae5c4aea8e8p-45, -0x0.b7462083adbbf8p-52, // x in subrange 4:0 (8..8.125)
 0x0.8e33b776b1aee8p-3, -0x0.8d19a0b27ecce8p-10, 0x0.8d20bfff05a8f0p-17, -0x0.8e50a2158196f0p-24, 0x0.90b8bc6cd0c998p-31, -0x0.94717857110088p-38, 0x0.999874330762d0p-45, -0x0.a07423fae571f0p-52, // x in subrange 4:1 (8.125..8.25)
 0x0.8c07fffa2f8798p-3, -0x0.88cabbf043bc18p-10, 0x0.86a9d35db66d68p-17, -0x0.859ef284a49cf0p-24, 0x0.85aa940ef3def8p-31, -0x0.86d453d3942108p-38, 0x0.89270a38ba8878p-45, -0x0.8cce9929c66038p-52, // x in subrange 4:2 (8.25..8.375)
 0x0.89ed1ec37f65b0p-3, -0x0.84adf80dc0ea48p-10, 0x0.809736c0845368p-17, -0x0.fb2be5c38f8088p-25, 0x0.f73bda7ac0f1f8p-32, -0x0.f552a861029c78p-39, 0x0.f569bb40912ab8p-46, -0x0.f7b1b558902c60p-53, // x in subrange 4:3 (8.375..8.5)
 0x0.87e2516af286d0p-3, -0x0.80c051315c7060p-10, 0x0.f5c2bdf134ace8p-18, -0x0.ec4cd192ed4de0p-25, 0x0.e4ef4bd2b50d80p-32, -0x0.df87c01e45f738p-39, 0x0.dbf92be0af9480p-46, -0x0.da564c9aedadc0p-53, // x in subrange 4:4 (8.5..8.625)
 0x0.85e6e12341c7d8p-3, -0x0.f9fdfa34939ba0p-11, 0x0.eb02dba52ec7b0p-18, -0x0.de8562ccdfcfd8p-25, 0x0.d43fb4b856b668p-32, -0x0.cbfabd05cd9800p-39, 0x0.c5867603813f68p-46, -0x0.c0dda4a9753030p-53, // x in subrange 4:5 (8.625..8.75)
 0x0.83fa21dd9769f8p-3, -0x0.f2cecc03ef5658p-11, 0x0.e0e24049b43eb0p-18, -0x0.d1bd22358b1f50p-25, 0x0.c502ecb5c49948p-32, -0x0.ba68a5f66a55b0p-39, 0x0.b1ad05c89042c8p-46, -0x0.aab680d1f56a70p-53, // x in subrange 4:6 (8.75..8.875)
 0x0.821b7180ffafd8p-3, -0x0.ebee4c08cb0728p-11, 0x0.d7557bf4dc8d18p-18, -0x0.c5de1320918338p-25, 0x0.b713ad3c00cc48p-32, -0x0.aa973c50de6140p-39, 0x0.a016d938ffdbe0p-46, -0x0.9766ccdda93638p-53, // x in subrange 4:7 (8.875..9)
 0x0.804a373344f2f0p-3, -0x0.e55805ff3fc960p-11, 0x0.ce5219271707e8p-18, -0x0.bad46a8163d558p-25, 0x0.aa50eff9594598p-32, -0x0.9c53babaad8418p-39, 0x0.907a32305d10d0p-46, -0x0.86879d2a507be0p-53, // x in subrange 4:8 (9..9.125)
 0x0.fd0bc562ed3f90p-4, -0x0.df07d5b96017d8p-11, 0x0.c5ce83fdc6edb8p-18, -0x0.b08e4f58663fd0p-25, 0x0.9e9d6440701c98p-32, -0x0.8f71c6509d6b10p-39, 0x0.8297ad637da1d8p-46, -0x0.ef83d9f938b8f8p-54, // x in subrange 4:9 (9.125..9.25)
 0x0.f99bd76d1b6ed8p-4, -0x0.d8f9e06c1c19c0p-11, 0x0.bdc1f42f51c1e8p-18, -0x0.a6fba329843bf8p-25, 0x0.93def7e7d8e638p-32, -0x0.83ca89b51ce9e8p-39, 0x0.ec7157c3af1508p-47, -0x0.d597ea81a234f8p-54, // x in subrange 4:10 (9.25..9.375)
 0x0.f643a2dd9c4050p-4, -0x0.d32a8ea24e8468p-11, 0x0.b624597717f400p-18, -0x0.9e0dd15d4b57b0p-25, 0x0.89fe70a5886950p-32, -0x0.f277e5f0f35908p-40, 0x0.d65c0034a4f4c0p-47, -0x0.becdfbd7a19640p-54, // x in subrange 4:11 (9.375..9.5)
 0x0.f30233ed563cc0p-4, -0x0.cd9686c3aee650p-11, 0x0.aeee4a24349e28p-18, -0x0.95b7a499561b80p-25, 0x0.80e713686aaf78p-32, -0x0.df501d37cd7e08p-40, 0x0.c29da4a7c749f0p-47, -0x0.aabb24c40b1ef8p-54, // x in subrange 4:12 (9.5..9.625)
 0x0.efd6a3c82f1148p-4, -0x0.c83aa81fa40f38p-11, 0x0.a818f388664598p-18, -0x0.8ded21414d0d58p-25, 0x0.f10caf35a4be18p-33, -0x0.cde8f5ea6ebcc0p-40, 0x0.b0ef65b0417ed0p-47, -0x0.99040c3e3432e8p-54, // x in subrange 4:13 (9.625..9.75)
 0x0.ecc017b290b188p-4, -0x0.c314066de176c8p-11, 0x0.a19e0c0d768740p-18, -0x0.86a3647052a408p-25, 0x0.e197491ce62a38p-33, -0x0.be13e01931b540p-40, 0x0.a113a3c7ded458p-47, -0x0.895a7544e87888p-54, // x in subrange 4:14 (9.75..9.875)
 0x0.e9bdc040155b90p-4, -0x0.be1fe5b8687778p-11, 0x0.9b77c6bf1a3318p-18, -0x0.ffa10da8b2bca8p-26, 0x0.d3502f33599c38p-33, -0x0.afa7b172ff4920p-40, 0x0.92d4add4b55920p-47, -0x0.f6f66a79ab1608p-55, // x in subrange 4:15 (9.875..10)
 0x0.e6ced899cb45f8p-4, -0x0.b95bb6a3fb98b0p-11, 0x0.95a0c81dcc0128p-18, -0x0.f2d705d50186a0p-26, 0x0.c61ca351b91268p-33, -0x0.a27ff4a080a200p-40, 0x0.8603a3c6b6ad18p-47, -0x0.de590307793e58p-55, // x in subrange 4:16 (10..10.125)
 0x0.e3f2a5d2a9edf0p-4, -0x0.b4c5130d571658p-11, 0x0.90141c14be1f70p-18, -0x0.e6d83c5badb1f8p-26, 0x0.b9e4966ecd6388p-33, -0x0.967c51493f9660p-40, 0x0.f4ef094df91548p-48, -0x0.c879094335a7d0p-55, // x in subrange 4:17 (10.125..10.25)
 0x0.e1287648f76c08p-4, -0x0.b059baf29d36e8p-11, 0x0.8acd2cf1cf2e38p-18, -0x0.db95a9b29f3fa0p-26, 0x0.ae925b9a18d1c8p-33, -0x0.8b800907decc40p-40, 0x0.e018c1f77c4fb8p-48, -0x0.b5005cefe3a980p-55, // x in subrange 4:18 (10.25..10.375)
 0x0.de6fa1137c80c8p-4, -0x0.ac1791a15c9bc8p-11, 0x0.85c7bb42949b78p-18, -0x0.d1018fd5c34810p-26, 0x0.a412647c8f5b28p-33, -0x0.8171862de47a88p-40, 0x0.cd455745679118p-48, -0x0.a3a46a5ae0d578p-55, // x in subrange 4:19 (10.375..10.5)
 0x0.dbc7857982b728p-4, -0x0.a7fc9b226f8138p-11, 0x0.80ffd67d205bf0p-18, -0x0.c70f5a41be37e0p-26, 0x0.9a5306161f9da0p-33, -0x0.f073f36fc01808p-41, 0x0.bc3d488e438f58p-48, -0x0.94247cf3d87d68p-55, // x in subrange 4:20 (10.5..10.625)
 0x0.d92f8a74b179e8p-4, -0x0.a406f9ddb103e0p-11, 0x0.f8e3acbc809f30p-19, -0x0.bdb381684d94b0p-26, 0x0.9144449ef79298p-33, -0x0.df8a0c79f81c88p-41, 0x0.accfaed917a480p-48, -0x0.864854fa4dd470p-55, // x in subrange 4:21 (10.625..10.75)
 0x0.d6a71e3bf5b010p-4, -0x0.a034ec702c94e8p-11, 0x0.f034a9d3489490p-19, -0x0.b4e37133d32da0p-26, 0x0.88d7a59c050f88p-33, -0x0.d000ebfaaf7bf8p-41, 0x0.9ed16168e6b0e0p-48, -0x0.f3bdea1791d688p-56, // x in subrange 4:22 (10.75..10.875)
 0x0.d42db5d6b3b738p-4, -0x0.9c84cbaffed508p-11, 0x0.e7ec51f5580078p-19, -0x0.ac95723d71b958p-26, 0x0.81000758794518p-33, -0x0.c1b7f4f81858f8p-41, 0x0.921c3927c1d350p-48, -0x0.dd7b3cb73732e8p-56, // x in subrange 4:23 (10.875..11)
 0x0.d1c2ccb795ac50p-4, -0x0.98f508d9a0b900p-11, 0x0.e004c2ad49c1b0p-19, -0x0.a4c0956517dd38p-26, 0x0.f362fa2638a1b8p-34, -0x0.b491e89e500b80p-41, 0x0.868e6e4560b600p-48, -0x0.c97de7f63a4a78p-56, // x in subrange 4:24 (11..11.125)
 0x0.cf65e45e5827c0p-4, -0x0.95842be2c86160p-11, 0x0.d8788066083668p-19, -0x0.9d5ca1851f65d8p-26, 0x0.e5c25e8dbdf240p-34, -0x0.a8748406a71368p-41, 0x0.f814183d7d6170p-49, -0x0.b7847dd46fa220p-56, // x in subrange 4:25 (11.125..11.25)
 0x0.cd168400061378p-4, -0x0.9230d1ef705cb8p-11, 0x0.d1426e4767cfc8p-19, -0x0.96620304038738p-26, 0x0.d90a7f1615eb80p-34, -0x0.9d482a37e03790p-41, 0x0.e4e8f048ef1a50p-49, -0x0.a7559b7690b558p-56, // x in subrange 4:26 (11.25..11.375)
 0x0.cad43835214910p-4, -0x0.8ef9abe5efd018p-11, 0x0.ca5dc6cdc93938p-19, -0x0.8fc9bd0e585bc8p-26, 0x0.cd295f3298f140p-34, -0x0.92f798b99c5a28p-41, 0x0.d36c11f534f1d0p-49, -0x0.98bed6ed2d0a68p-56, // x in subrange 4:27 (11.375..11.5)
 0x0.c89e92ad4158a8p-4, -0x0.8bdd7d1f5da720p-11, 0x0.c3c6150a017440p-19, -0x0.898d5c49cd03f8p-26, 0x0.c20e962e1e2990p-34, -0x0.896fa55253a4b8p-41, 0x0.c37356f69c9358p-49, -0x0.8b93d44540af00p-56, // x in subrange 4:28 (11.5..11.625)
 0x0.c67529e7bc6160p-4, -0x0.88db1a31bfb678p-11, 0x0.bd772e78d998c0p-19, -0x0.83a6ead7bf0f58p-26, 0x0.b7ab27996980e0p-34, -0x0.809f03baeb1c68p-41, 0x0.b4d92743d2f048p-49, -0x0.ff5af7bab8af40p-57, // x in subrange 4:29 (11.625..11.75)
 0x0.c45798f0f75f00p-4, -0x0.85f167d1c5ba40p-11, 0x0.b76d2d634afee0p-19, -0x0.fc21cb05c343b0p-27, 0x0.adf16000bc8788p-34, -0x0.f0ec247d707d98p-42, 0x0.a77bef62897e30p-49, -0x0.e9d299eb1bd2f8p-57, // x in subrange 4:30 (11.75..11.875)
 0x0.c2457f2403df60p-4, -0x0.831f59ca083fc0p-11, 0x0.b1a46bba37e038p-19, -0x0.f18c63efa0f518p-27, 0x0.a4d4b567330588p-34, -0x0.e1cd58c7cb6d00p-42, 0x0.9b3da85164ce78p-49, -0x0.d65190802974b0p-57, // x in subrange 4:31 (11.875..12)
};
// clang-format on
//--- End of autogenerated code

//! Compute Im w(x) by Chebyshev interpolation within certain subranges.
//! Coefficients are read from the avove lookup table.
//! This allows us to compute the within-subrange coordinate t = (x - center_of_range) / half_range
//! by integer and bitwise operations without any rounding.

static double chebInterpolant(double x)
{
    int ie;
    double xm = frexp(x, &ie);
    long long ix = ldexp(xm, 53);

    static const int e2nranges = 6; // 2^6=64 Chebyshev interpolants per octave
    static const int il0 = 0; // first index in first octave
    int ir = ix >> (52 - e2nranges) & ((1 << e2nranges) - 1); // index of range
    int il = ie * (1 << e2nranges) + ir - il0; // index in lookup table
    faddeeva_nofterms = il;
    int ic = (1 << (e2nranges+1)) + 2*ir+1; // proportional to center of subrange
    double t = ldexp(xm, e2nranges + 2) - ic; // position within subrange, between -1 and +1
    //printf("x=%22.16e -> range #%i, lookup #%i: ic=%i t=%g\n", x, ir, il, ic, t);
    const double *const P = ChebCoeffs + (il * 8);

    // hard-coded for N1cheb=9
    return ((((((( ChebCoeffs8[il] * t
		   + P[7] ) * t
		 + P[6] ) * t
		+ P[5] ) * t
	       + P[4] ) * t
	      + P[3] ) * t
	     + P[2] ) * t
	    + P[1] ) * t
	+ P[0];
}

/******************************************************************************/
/*  Library function im_w_of_z                                                */
/******************************************************************************/

double im_w_of_x(double x)
{
    // Steven G. Johnson, October 2012.
    // Rewritten for better accuracy by Joachim Wuttke, Sept 2024.

    // Uses three different methods:
    // - asymptotic expansion for large |x|,
    // - Chebyshev polynomials for medium |x|,
    // - Taylor (Maclaurin) series for small |x|.

    const double ax = fabs(x); // very fast

    if (ax < .51) {
        // Use Taylor expansion (2/sqrt(pi)) * (x - 2/3 x^3  + 4/15 x^5  - 8/105 x^7 + ...)

	faddeeva_algorithm = 500;
	const double x2 = x*x;

	if (ax < .083) {
	    if (ax < 0.003) {
		faddeeva_nofterms = 4;
		return (((( - 0.085971746064420005629 ) * x2// x^7
			  + 0.30090111122547001970 ) * x2 // x^5
			 - 0.75225277806367504925 ) * x2 // x^3
			+ 1.1283791670955125739 ) * x;
	    }
	    faddeeva_nofterms = 7;
	    return ((((((( + 0.00053440090793734269229 ) * x2 // x^13
			 - 0.0034736059015927275001 ) * x2 // x^11
			+ 0.019104832458760001251 ) * x2 // x^9
		       - 0.085971746064420005629 ) * x2 // x^7
		      + 0.30090111122547001970 ) * x2 // x^5
		     - 0.75225277806367504925 ) * x2 // x^3
		    + 1.1283791670955125739 ) * x;
	}
	if (ax < .272) {
	    faddeeva_nofterms = 10;
	    return (((((((((( - 8.82395720020380130481012927e-7 ) * x2 // x^19
			    + 8.38275934019361123956e-6 ) * x2 // x^17
			   - 7.1253454391645686483238e-5 ) * x2 // x^15
			  + 0.00053440090793734269229 ) * x2 // x^13
			 - 0.0034736059015927275001 ) * x2 // x^11
			+ 0.019104832458760001251 ) * x2 // x^9
		       - 0.085971746064420005629 ) * x2 // x^7
		      + 0.30090111122547001970 ) * x2 // x^5
		     - 0.75225277806367504925 ) * x2 // x^3
		    + 1.1283791670955125739 ) * x;
	}
	faddeeva_nofterms = 13;
        return ((((((((((((( + 5.8461000084165966602290712e-10 ) * x2 // x^25
			   - 7.30762501052074563638866034e-9 ) * x2 // x^23
			  + 8.40376876209885782941868884e-8 ) * x2 // x^21
			 - 8.82395720020380130481012927e-7 ) * x2 // x^19
			+ 8.38275934019361123956e-6 ) * x2 // x^17
		       - 7.1253454391645686483238e-5 ) * x2 // x^15
		      + 0.00053440090793734269229 ) * x2 // x^13
		     - 0.0034736059015927275001 ) * x2 // x^11
		    + 0.019104832458760001251 ) * x2 // x^9
		   - 0.085971746064420005629 ) * x2 // x^7
		  + 0.30090111122547001970 ) * x2 // x^5
		 - 0.75225277806367504925 ) * x2 // x^3
		+ 1.1283791670955125739 ) * x;
    }

    if (ax < 12.) {
        // Intermediate range: Use Chebyshev interpolants.

	faddeeva_algorithm = 510;
	return copysign(chebInterpolant(ax), x);
    }

    /* else */ {
        // Use asymptotic expansion up to N = 0, 3, 6, or 10
	//
	// With N=15 or 20 we could extend the range down to 7.73 or 6.72,
	// but we expect Chebyshev to be faster.
	//
	// Coefficient are a_0 = 1/sqrt(pi), a_N = (2N-1)!!/2^N/sqrt(pi).

	const double r = 1/x;

	faddeeva_algorithm = 520;
	if (ax < 150) {
	    if (ax < 23.2) {
		faddeeva_nofterms = 11; // N=10
		return (((((((((((
				     + 3.6073371500083758e+05 ) * (r*r)
				 + 3.7971970000088164e+04 ) * (r*r)
				+ 4.4672905882456671e+03 ) * (r*r)
			       + 5.9563874509942218e+02 ) * (r*r)
			      + 9.1636730015295726e+01 ) * (r*r)
			     + 1.6661223639144676e+01 ) * (r*r)
			    + 3.7024941420321507e+00 ) * (r*r)
			   + 1.0578554691520430e+00 ) * (r*r)
			  + 4.2314218766081724e-01 ) * (r*r)
			 + 2.8209479177387814e-01 ) * (r*r)
			+ 5.6418958354775628e-01 ) * r;
	    }
	    faddeeva_nofterms = 7; // N=6
	    return (((((((
			     + 9.1636730015295726e+01 ) * (r*r)
			 + 1.6661223639144676e+01 ) * (r*r)
			+ 3.7024941420321507e+00 ) * (r*r)
		       + 1.0578554691520430e+00 ) * (r*r)
		      + 4.2314218766081724e-01 ) * (r*r)
		     + 2.8209479177387814e-01 ) * (r*r)
		    + 5.6418958354775628e-01 ) * r;
	}

	if (ax < 6.9e7) {
	    faddeeva_nofterms = 4; // N = 3
	    return ((((
			  + 1.0578554691520430e+00 ) * (r*r)
		      + 4.2314218766081724e-01 ) * (r*r)
		     + 2.8209479177387814e-01 ) * (r*r)
		    + 5.6418958354775628e-01 ) * r;
	}

	faddeeva_nofterms = 1; // N = 0: 1-term expansion, important to avoid overflow
	return 0.56418958354775629 / x;
    }

} // im_w_of_z
